extern "C"
{
	#include <lua.h>
	#include <lauxlib.h>


	// Headers with typedefs etc.
	#include "XPLMCamera.h"
	#include "XPLMDataAccess.h"
	#include "XPLMDefs.h"
	#include "XPLMDisplay.h"
	#include "XPLMGraphics.h"
	#include "XPLMInstance.h"
	#include "XPLMMap.h"
	#include "XPLMMenus.h"
	#include "XPLMNavigation.h"
	#include "XPLMPlanes.h"
	#include "XPLMProcessing.h"
	#include "XPLMScenery.h"
	#include "XPLMSound.h"
	#include "XPLMUtilities.h"
	#include "XPLMWeather.h"

	int XLuaAcquirePlanes(lua_State* L);
	int XLuaAppendMenuItem(lua_State* L);
	int XLuaAppendMenuItemWithCommand(lua_State* L);
	int XLuaAppendMenuSeparator(lua_State* L);
	int XLuaAvionicsNeedsDrawing(lua_State* L);
	int XLuaBeginWeatherUpdate(lua_State* L);
	int MakeXPLMCameraPosition_t(lua_State* L);
	int XLuaCanWriteDataRef(lua_State* L);
	int XLuaCheckMenuItem(lua_State* L);
	int XLuaCheckMenuItemState(lua_State* L);
	int XLuaClearAllMenuItems(lua_State* L);
	int XLuaClearFMSEntry(lua_State* L);
	int XLuaClearFMSFlightPlanEntry(lua_State* L);
	int XLuaCommandBegin(lua_State* L);
	int XLuaCommandButtonPress(lua_State* L);
	int XLuaCommandButtonRelease(lua_State* L);
	int XLuaCommandEnd(lua_State* L);
	int XLuaCommandKeyStroke(lua_State* L);
	int XLuaCommandOnce(lua_State* L);
	int XLuaControlCamera(lua_State* L);
	int XLuaCountAircraft(lua_State* L);
	int XLuaCountDataRefs(lua_State* L);
	int XLuaCountFMSEntries(lua_State* L);
	int XLuaCountFMSFlightPlanEntries(lua_State* L);
	int XLuaCountHotKeys(lua_State* L);
	int XLuaCountPlugins(lua_State* L);
	int XLuaCreateAvionicsEx(lua_State* L);
	int MakeXPLMCreateAvionics_t(lua_State* L);
	int XLuaCreateCommand(lua_State* L);
	int XLuaCreateFlightLoop(lua_State* L);
	int MakeXPLMCreateFlightLoop_t(lua_State* L);
	int XLuaCreateInstance(lua_State* L);
	int XLuaCreateMapLayer(lua_State* L);
	int MakeXPLMCreateMapLayer_t(lua_State* L);
	int XLuaCreateMenu(lua_State* L);
	int XLuaCreateProbe(lua_State* L);
	int MakeXPLMCustomizeAvionics_t(lua_State* L);
	int MakeXPLMDataRefInfo_t(lua_State* L);
	int XLuaDebugString(lua_State* L);
	int XLuaDegMagneticToDegTrue(lua_State* L);
	int XLuaDegTrueToDegMagnetic(lua_State* L);
	int XLuaDestroyAvionics(lua_State* L);
	int XLuaDestroyFlightLoop(lua_State* L);
	int XLuaDestroyInstance(lua_State* L);
	int XLuaDestroyMapLayer(lua_State* L);
	int XLuaDestroyMenu(lua_State* L);
	int XLuaDestroyProbe(lua_State* L);
	int XLuaDisableAIForPlane(lua_State* L);
	int XLuaDisablePlugin(lua_State* L);
	int XLuaDontControlCamera(lua_State* L);
	int MakeXPLMDrawInfoDouble_t(lua_State* L);
	int MakeXPLMDrawInfo_t(lua_State* L);
	int XLuaDrawMapIconFromSheet(lua_State* L);
	int XLuaDrawMapLabel(lua_State* L);
	int XLuaDrawNumber(lua_State* L);
	int XLuaDrawString(lua_State* L);
	int XLuaEnableFeature(lua_State* L);
	int XLuaEnableMenuItem(lua_State* L);
	int XLuaEnablePlugin(lua_State* L);
	int XLuaEndWeatherUpdate(lua_State* L);
	int XLuaEnumerateFeatures(lua_State* L);
	int XLuaEraseWeatherAtAirport(lua_State* L);
	int XLuaEraseWeatherAtLocation(lua_State* L);
	int XLuaFindAircraftMenu(lua_State* L);
	int XLuaFindCommand(lua_State* L);
	int XLuaFindDataRef(lua_State* L);
	int XLuaFindFirstNavAidOfType(lua_State* L);
	int XLuaFindLastNavAidOfType(lua_State* L);
	int XLuaFindNavAid(lua_State* L);
	int XLuaFindPluginByPath(lua_State* L);
	int XLuaFindPluginBySignature(lua_State* L);
	int XLuaFindPluginsMenu(lua_State* L);
	int MakeXPLMFixedString150_t(lua_State* L);
	int XLuaGetAvionicsBrightnessRheo(lua_State* L);
	int XLuaGetAvionicsBusVoltsRatio(lua_State* L);
	int XLuaGetAvionicsGeometry(lua_State* L);
	int XLuaGetAvionicsGeometryOS(lua_State* L);
	int XLuaGetAvionicsHandle(lua_State* L);
	int XLuaGetCycleNumber(lua_State* L);
	int XLuaGetDataRefInfo(lua_State* L);
	int XLuaGetDataRefTypes(lua_State* L);
	int XLuaGetDataRefsByIndex(lua_State* L);
	int XLuaGetDatab(lua_State* L);
	int XLuaGetDatad(lua_State* L);
	int XLuaGetDataf(lua_State* L);
	int XLuaGetDatai(lua_State* L);
	int XLuaGetDatavf(lua_State* L);
	int XLuaGetDatavi(lua_State* L);
	int XLuaGetDestinationFMSEntry(lua_State* L);
	int XLuaGetDestinationFMSFlightPlanEntry(lua_State* L);
	int XLuaGetDirectorySeparator(lua_State* L);
	int XLuaGetDisplayedFMSEntry(lua_State* L);
	int XLuaGetDisplayedFMSFlightPlanEntry(lua_State* L);
	int XLuaGetElapsedTime(lua_State* L);
	int XLuaGetFMODChannelGroup(lua_State* L);
	int XLuaGetFMODStudio(lua_State* L);
	int XLuaGetFMSEntryInfo(lua_State* L);
	int XLuaGetFMSFlightPlanEntryInfo(lua_State* L);
	int XLuaGetFirstNavAid(lua_State* L);
	int XLuaGetFontDimensions(lua_State* L);
	int XLuaGetGPSDestination(lua_State* L);
	int XLuaGetGPSDestinationType(lua_State* L);
	int XLuaGetHotKeyInfo(lua_State* L);
	int XLuaGetLanguage(lua_State* L);
	int XLuaGetMETARForAirport(lua_State* L);
	int XLuaGetMagneticVariation(lua_State* L);
	int XLuaGetMyID(lua_State* L);
	int XLuaGetNavAidInfo(lua_State* L);
	int XLuaGetNextNavAid(lua_State* L);
	int XLuaGetNthAircraftModel(lua_State* L);
	int XLuaGetNthHotKey(lua_State* L);
	int XLuaGetNthPlugin(lua_State* L);
	int XLuaGetPluginInfo(lua_State* L);
	int XLuaGetPrefsPath(lua_State* L);
	int XLuaGetSystemPath(lua_State* L);
	int XLuaGetVersions(lua_State* L);
	int XLuaGetVirtualKeyDescription(lua_State* L);
	int XLuaGetWeatherAtLocation(lua_State* L);
	int XLuaHasAvionicsKeyboardFocus(lua_State* L);
	int XLuaHasFeature(lua_State* L);
	int XLuaInitFlight(lua_State* L);
	int XLuaInitialized(lua_State* L);
	int XLuaInstanceSetAutoShift(lua_State* L);
	int XLuaInstanceSetPosition(lua_State* L);
	int XLuaInstanceSetPositionDouble(lua_State* L);
	int XLuaIsAvionicsBound(lua_State* L);
	int XLuaIsAvionicsPoppedOut(lua_State* L);
	int XLuaIsAvionicsPopupVisible(lua_State* L);
	int XLuaIsCameraBeingControlled(lua_State* L);
	int XLuaIsCursorOverAvionics(lua_State* L);
	int XLuaIsDataRefGood(lua_State* L);
	int XLuaIsFeatureEnabled(lua_State* L);
	int XLuaIsPluginEnabled(lua_State* L);
	int XLuaLoadDataFile(lua_State* L);
	int XLuaLoadFMSFlightPlan(lua_State* L);
	int XLuaLoadObject(lua_State* L);
	int XLuaLoadObjectAsync(lua_State* L);
	int XLuaLocalToWorld(lua_State* L);
	int XLuaLookupObjects(lua_State* L);
	int XLuaMapExists(lua_State* L);
	int XLuaMapGetNorthHeading(lua_State* L);
	int XLuaMapProject(lua_State* L);
	int XLuaMapScaleMeter(lua_State* L);
	int XLuaMapUnproject(lua_State* L);
	int XLuaMeasureString(lua_State* L);
	int XLuaPlaceUserAtAirport(lua_State* L);
	int XLuaPlaceUserAtLocation(lua_State* L);
	int MakeXPLMPlaneDrawState_t(lua_State* L);
	int XLuaPlayPCMOnBus(lua_State* L);
	int XLuaPopOutAvionics(lua_State* L);
	int MakeXPLMProbeInfo_t(lua_State* L);
	int XLuaProbeTerrainXYZ(lua_State* L);
	int XLuaReadCameraPosition(lua_State* L);
	int XLuaRegisterAvionicsCallbacksEx(lua_State* L);
	int XLuaRegisterCommandHandler(lua_State* L);
	int XLuaRegisterDataAccessor(lua_State* L);
	int XLuaRegisterHotKey(lua_State* L);
	int XLuaRegisterMapCreationHook(lua_State* L);
	int XLuaReleasePlanes(lua_State* L);
	int XLuaReloadPlugins(lua_State* L);
	int XLuaReloadScenery(lua_State* L);
	int XLuaRemoveMenuItem(lua_State* L);
	int XLuaSaveDataFile(lua_State* L);
	int XLuaScheduleFlightLoop(lua_State* L);
	int XLuaSendMessageToPlugin(lua_State* L);
	int XLuaSetActiveAircraftCount(lua_State* L);
	int XLuaSetAircraftModel(lua_State* L);
	int XLuaSetAudioCone(lua_State* L);
	int XLuaSetAudioFadeDistance(lua_State* L);
	int XLuaSetAudioPitch(lua_State* L);
	int XLuaSetAudioPosition(lua_State* L);
	int XLuaSetAudioVolume(lua_State* L);
	int XLuaSetAvionicsBrightnessRheo(lua_State* L);
	int XLuaSetAvionicsGeometry(lua_State* L);
	int XLuaSetAvionicsGeometryOS(lua_State* L);
	int XLuaSetAvionicsPopupVisible(lua_State* L);
	int XLuaSetDatab(lua_State* L);
	int XLuaSetDatad(lua_State* L);
	int XLuaSetDataf(lua_State* L);
	int XLuaSetDatai(lua_State* L);
	int XLuaSetDatavf(lua_State* L);
	int XLuaSetDatavi(lua_State* L);
	int XLuaSetDestinationFMSEntry(lua_State* L);
	int XLuaSetDestinationFMSFlightPlanEntry(lua_State* L);
	int XLuaSetDirectToFMSFlightPlanEntry(lua_State* L);
	int XLuaSetDisplayedFMSEntry(lua_State* L);
	int XLuaSetDisplayedFMSFlightPlanEntry(lua_State* L);
	int XLuaSetFMSEntryInfo(lua_State* L);
	int XLuaSetFMSEntryLatLon(lua_State* L);
	int XLuaSetFMSFlightPlanEntryInfo(lua_State* L);
	int XLuaSetFMSFlightPlanEntryLatLon(lua_State* L);
	int XLuaSetFMSFlightPlanEntryLatLonWithId(lua_State* L);
	int XLuaSetHotKeyCombination(lua_State* L);
	int XLuaSetMenuItemName(lua_State* L);
	int XLuaSetUsersAircraft(lua_State* L);
	int XLuaSetWeatherAtAirport(lua_State* L);
	int XLuaSetWeatherAtLocation(lua_State* L);
	int XLuaSimulateKeyPress(lua_State* L);
	int XLuaSpeakString(lua_State* L);
	int XLuaStopAudio(lua_State* L);
	int XLuaTakeAvionicsKeyboardFocus(lua_State* L);
	int XLuaUnloadObject(lua_State* L);
	int XLuaUnregisterAvionicsCallbacks(lua_State* L);
	int XLuaUnregisterCommandHandler(lua_State* L);
	int XLuaUnregisterDataAccessor(lua_State* L);
	int XLuaUnregisterHotKey(lua_State* L);
	int XLuaUpdateFlight(lua_State* L);
	int MakeXPLMWeatherInfoClouds_t(lua_State* L);
	int MakeXPLMWeatherInfoWinds_t(lua_State* L);
	int MakeXPLMWeatherInfo_t(lua_State* L);
	int XLuaWorldToLocal(lua_State* L);

	// Typedefs
	void RegType_XPLMAvionicsID(lua_State* L);
	XPLMAvionicsID* Make_XPLMAvionicsID(lua_State* L, XPLMAvionicsID const& init);
	void RegType_XPLMCommandRef(lua_State* L);
	XPLMCommandRef* Make_XPLMCommandRef(lua_State* L, XPLMCommandRef const& init);
	void RegType_XPLMDataRef(lua_State* L);
	XPLMDataRef* Make_XPLMDataRef(lua_State* L, XPLMDataRef const& init);
	void RegType_XPLMFlightLoopID(lua_State* L);
	XPLMFlightLoopID* Make_XPLMFlightLoopID(lua_State* L, XPLMFlightLoopID const& init);
	void RegType_XPLMHotKeyID(lua_State* L);
	XPLMHotKeyID* Make_XPLMHotKeyID(lua_State* L, XPLMHotKeyID const& init);
	void RegType_XPLMInstanceRef(lua_State* L);
	XPLMInstanceRef* Make_XPLMInstanceRef(lua_State* L, XPLMInstanceRef const& init);
	void RegType_XPLMMapLayerID(lua_State* L);
	XPLMMapLayerID* Make_XPLMMapLayerID(lua_State* L, XPLMMapLayerID const& init);
	void RegType_XPLMMapProjectionID(lua_State* L);
	XPLMMapProjectionID* Make_XPLMMapProjectionID(lua_State* L, XPLMMapProjectionID const& init);
	void RegType_XPLMMenuID(lua_State* L);
	XPLMMenuID* Make_XPLMMenuID(lua_State* L, XPLMMenuID const& init);
	void RegType_XPLMNavRef(lua_State* L);
	XPLMNavRef* Make_XPLMNavRef(lua_State* L, XPLMNavRef const& init);
	void RegType_XPLMObjectRef(lua_State* L);
	XPLMObjectRef* Make_XPLMObjectRef(lua_State* L, XPLMObjectRef const& init);
	void RegType_XPLMPluginID(lua_State* L);
	XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);
	void RegType_XPLMProbeRef(lua_State* L);
	XPLMProbeRef* Make_XPLMProbeRef(lua_State* L, XPLMProbeRef const& init);
}		// extern "C"


void add_xplm_to_interp(lua_State* L)
{
	lua_register(L, "XPLMAcquirePlanes", XLuaAcquirePlanes);
	lua_register(L, "XPLMAppendMenuItem", XLuaAppendMenuItem);
	lua_register(L, "XPLMAppendMenuItemWithCommand", XLuaAppendMenuItemWithCommand);
	lua_register(L, "XPLMAppendMenuSeparator", XLuaAppendMenuSeparator);
	lua_register(L, "XPLMAvionicsNeedsDrawing", XLuaAvionicsNeedsDrawing);
	lua_register(L, "XPLMBeginWeatherUpdate", XLuaBeginWeatherUpdate);
	lua_register(L, "XPLMCameraPosition_t", MakeXPLMCameraPosition_t);
	lua_register(L, "XPLMCanWriteDataRef", XLuaCanWriteDataRef);
	lua_register(L, "XPLMCheckMenuItem", XLuaCheckMenuItem);
	lua_register(L, "XPLMCheckMenuItemState", XLuaCheckMenuItemState);
	lua_register(L, "XPLMClearAllMenuItems", XLuaClearAllMenuItems);
	lua_register(L, "XPLMClearFMSEntry", XLuaClearFMSEntry);
	lua_register(L, "XPLMClearFMSFlightPlanEntry", XLuaClearFMSFlightPlanEntry);
	lua_register(L, "XPLMCommandBegin", XLuaCommandBegin);
	lua_register(L, "XPLMCommandButtonPress", XLuaCommandButtonPress);
	lua_register(L, "XPLMCommandButtonRelease", XLuaCommandButtonRelease);
	lua_register(L, "XPLMCommandEnd", XLuaCommandEnd);
	lua_register(L, "XPLMCommandKeyStroke", XLuaCommandKeyStroke);
	lua_register(L, "XPLMCommandOnce", XLuaCommandOnce);
	lua_register(L, "XPLMControlCamera", XLuaControlCamera);
	lua_register(L, "XPLMCountAircraft", XLuaCountAircraft);
	lua_register(L, "XPLMCountDataRefs", XLuaCountDataRefs);
	lua_register(L, "XPLMCountFMSEntries", XLuaCountFMSEntries);
	lua_register(L, "XPLMCountFMSFlightPlanEntries", XLuaCountFMSFlightPlanEntries);
	lua_register(L, "XPLMCountHotKeys", XLuaCountHotKeys);
	lua_register(L, "XPLMCountPlugins", XLuaCountPlugins);
	lua_register(L, "XPLMCreateAvionicsEx", XLuaCreateAvionicsEx);
	lua_register(L, "XPLMCreateAvionics_t", MakeXPLMCreateAvionics_t);
	lua_register(L, "XPLMCreateCommand", XLuaCreateCommand);
	lua_register(L, "XPLMCreateFlightLoop", XLuaCreateFlightLoop);
	lua_register(L, "XPLMCreateFlightLoop_t", MakeXPLMCreateFlightLoop_t);
	lua_register(L, "XPLMCreateInstance", XLuaCreateInstance);
	lua_register(L, "XPLMCreateMapLayer", XLuaCreateMapLayer);
	lua_register(L, "XPLMCreateMapLayer_t", MakeXPLMCreateMapLayer_t);
	lua_register(L, "XPLMCreateMenu", XLuaCreateMenu);
	lua_register(L, "XPLMCreateProbe", XLuaCreateProbe);
	lua_register(L, "XPLMCustomizeAvionics_t", MakeXPLMCustomizeAvionics_t);
	lua_register(L, "XPLMDataRefInfo_t", MakeXPLMDataRefInfo_t);
	lua_register(L, "XPLMDebugString", XLuaDebugString);
	lua_register(L, "XPLMDegMagneticToDegTrue", XLuaDegMagneticToDegTrue);
	lua_register(L, "XPLMDegTrueToDegMagnetic", XLuaDegTrueToDegMagnetic);
	lua_register(L, "XPLMDestroyAvionics", XLuaDestroyAvionics);
	lua_register(L, "XPLMDestroyFlightLoop", XLuaDestroyFlightLoop);
	lua_register(L, "XPLMDestroyInstance", XLuaDestroyInstance);
	lua_register(L, "XPLMDestroyMapLayer", XLuaDestroyMapLayer);
	lua_register(L, "XPLMDestroyMenu", XLuaDestroyMenu);
	lua_register(L, "XPLMDestroyProbe", XLuaDestroyProbe);
	lua_register(L, "XPLMDisableAIForPlane", XLuaDisableAIForPlane);
	lua_register(L, "XPLMDisablePlugin", XLuaDisablePlugin);
	lua_register(L, "XPLMDontControlCamera", XLuaDontControlCamera);
	lua_register(L, "XPLMDrawInfoDouble_t", MakeXPLMDrawInfoDouble_t);
	lua_register(L, "XPLMDrawInfo_t", MakeXPLMDrawInfo_t);
	lua_register(L, "XPLMDrawMapIconFromSheet", XLuaDrawMapIconFromSheet);
	lua_register(L, "XPLMDrawMapLabel", XLuaDrawMapLabel);
	lua_register(L, "XPLMDrawNumber", XLuaDrawNumber);
	lua_register(L, "XPLMDrawString", XLuaDrawString);
	lua_register(L, "XPLMEnableFeature", XLuaEnableFeature);
	lua_register(L, "XPLMEnableMenuItem", XLuaEnableMenuItem);
	lua_register(L, "XPLMEnablePlugin", XLuaEnablePlugin);
	lua_register(L, "XPLMEndWeatherUpdate", XLuaEndWeatherUpdate);
	lua_register(L, "XPLMEnumerateFeatures", XLuaEnumerateFeatures);
	lua_register(L, "XPLMEraseWeatherAtAirport", XLuaEraseWeatherAtAirport);
	lua_register(L, "XPLMEraseWeatherAtLocation", XLuaEraseWeatherAtLocation);
	lua_register(L, "XPLMFindAircraftMenu", XLuaFindAircraftMenu);
	lua_register(L, "XPLMFindCommand", XLuaFindCommand);
	lua_register(L, "XPLMFindDataRef", XLuaFindDataRef);
	lua_register(L, "XPLMFindFirstNavAidOfType", XLuaFindFirstNavAidOfType);
	lua_register(L, "XPLMFindLastNavAidOfType", XLuaFindLastNavAidOfType);
	lua_register(L, "XPLMFindNavAid", XLuaFindNavAid);
	lua_register(L, "XPLMFindPluginByPath", XLuaFindPluginByPath);
	lua_register(L, "XPLMFindPluginBySignature", XLuaFindPluginBySignature);
	lua_register(L, "XPLMFindPluginsMenu", XLuaFindPluginsMenu);
	lua_register(L, "XPLMFixedString150_t", MakeXPLMFixedString150_t);
	lua_register(L, "XPLMGetAvionicsBrightnessRheo", XLuaGetAvionicsBrightnessRheo);
	lua_register(L, "XPLMGetAvionicsBusVoltsRatio", XLuaGetAvionicsBusVoltsRatio);
	lua_register(L, "XPLMGetAvionicsGeometry", XLuaGetAvionicsGeometry);
	lua_register(L, "XPLMGetAvionicsGeometryOS", XLuaGetAvionicsGeometryOS);
	lua_register(L, "XPLMGetAvionicsHandle", XLuaGetAvionicsHandle);
	lua_register(L, "XPLMGetCycleNumber", XLuaGetCycleNumber);
	lua_register(L, "XPLMGetDataRefInfo", XLuaGetDataRefInfo);
	lua_register(L, "XPLMGetDataRefTypes", XLuaGetDataRefTypes);
	lua_register(L, "XPLMGetDataRefsByIndex", XLuaGetDataRefsByIndex);
	lua_register(L, "XPLMGetDatab", XLuaGetDatab);
	lua_register(L, "XPLMGetDatad", XLuaGetDatad);
	lua_register(L, "XPLMGetDataf", XLuaGetDataf);
	lua_register(L, "XPLMGetDatai", XLuaGetDatai);
	lua_register(L, "XPLMGetDatavf", XLuaGetDatavf);
	lua_register(L, "XPLMGetDatavi", XLuaGetDatavi);
	lua_register(L, "XPLMGetDestinationFMSEntry", XLuaGetDestinationFMSEntry);
	lua_register(L, "XPLMGetDestinationFMSFlightPlanEntry", XLuaGetDestinationFMSFlightPlanEntry);
	lua_register(L, "XPLMGetDirectorySeparator", XLuaGetDirectorySeparator);
	lua_register(L, "XPLMGetDisplayedFMSEntry", XLuaGetDisplayedFMSEntry);
	lua_register(L, "XPLMGetDisplayedFMSFlightPlanEntry", XLuaGetDisplayedFMSFlightPlanEntry);
	lua_register(L, "XPLMGetElapsedTime", XLuaGetElapsedTime);
	lua_register(L, "XPLMGetFMODChannelGroup", XLuaGetFMODChannelGroup);
	lua_register(L, "XPLMGetFMODStudio", XLuaGetFMODStudio);
	lua_register(L, "XPLMGetFMSEntryInfo", XLuaGetFMSEntryInfo);
	lua_register(L, "XPLMGetFMSFlightPlanEntryInfo", XLuaGetFMSFlightPlanEntryInfo);
	lua_register(L, "XPLMGetFirstNavAid", XLuaGetFirstNavAid);
	lua_register(L, "XPLMGetFontDimensions", XLuaGetFontDimensions);
	lua_register(L, "XPLMGetGPSDestination", XLuaGetGPSDestination);
	lua_register(L, "XPLMGetGPSDestinationType", XLuaGetGPSDestinationType);
	lua_register(L, "XPLMGetHotKeyInfo", XLuaGetHotKeyInfo);
	lua_register(L, "XPLMGetLanguage", XLuaGetLanguage);
	lua_register(L, "XPLMGetMETARForAirport", XLuaGetMETARForAirport);
	lua_register(L, "XPLMGetMagneticVariation", XLuaGetMagneticVariation);
	lua_register(L, "XPLMGetMyID", XLuaGetMyID);
	lua_register(L, "XPLMGetNavAidInfo", XLuaGetNavAidInfo);
	lua_register(L, "XPLMGetNextNavAid", XLuaGetNextNavAid);
	lua_register(L, "XPLMGetNthAircraftModel", XLuaGetNthAircraftModel);
	lua_register(L, "XPLMGetNthHotKey", XLuaGetNthHotKey);
	lua_register(L, "XPLMGetNthPlugin", XLuaGetNthPlugin);
	lua_register(L, "XPLMGetPluginInfo", XLuaGetPluginInfo);
	lua_register(L, "XPLMGetPrefsPath", XLuaGetPrefsPath);
	lua_register(L, "XPLMGetSystemPath", XLuaGetSystemPath);
	lua_register(L, "XPLMGetVersions", XLuaGetVersions);
	lua_register(L, "XPLMGetVirtualKeyDescription", XLuaGetVirtualKeyDescription);
	lua_register(L, "XPLMGetWeatherAtLocation", XLuaGetWeatherAtLocation);
	lua_register(L, "XPLMHasAvionicsKeyboardFocus", XLuaHasAvionicsKeyboardFocus);
	lua_register(L, "XPLMHasFeature", XLuaHasFeature);
	lua_register(L, "XPLMInitFlight", XLuaInitFlight);
	lua_register(L, "XPLMInitialized", XLuaInitialized);
	lua_register(L, "XPLMInstanceSetAutoShift", XLuaInstanceSetAutoShift);
	lua_register(L, "XPLMInstanceSetPosition", XLuaInstanceSetPosition);
	lua_register(L, "XPLMInstanceSetPositionDouble", XLuaInstanceSetPositionDouble);
	lua_register(L, "XPLMIsAvionicsBound", XLuaIsAvionicsBound);
	lua_register(L, "XPLMIsAvionicsPoppedOut", XLuaIsAvionicsPoppedOut);
	lua_register(L, "XPLMIsAvionicsPopupVisible", XLuaIsAvionicsPopupVisible);
	lua_register(L, "XPLMIsCameraBeingControlled", XLuaIsCameraBeingControlled);
	lua_register(L, "XPLMIsCursorOverAvionics", XLuaIsCursorOverAvionics);
	lua_register(L, "XPLMIsDataRefGood", XLuaIsDataRefGood);
	lua_register(L, "XPLMIsFeatureEnabled", XLuaIsFeatureEnabled);
	lua_register(L, "XPLMIsPluginEnabled", XLuaIsPluginEnabled);
	lua_register(L, "XPLMLoadDataFile", XLuaLoadDataFile);
	lua_register(L, "XPLMLoadFMSFlightPlan", XLuaLoadFMSFlightPlan);
	lua_register(L, "XPLMLoadObject", XLuaLoadObject);
	lua_register(L, "XPLMLoadObjectAsync", XLuaLoadObjectAsync);
	lua_register(L, "XPLMLocalToWorld", XLuaLocalToWorld);
	lua_register(L, "XPLMLookupObjects", XLuaLookupObjects);
	lua_register(L, "XPLMMapExists", XLuaMapExists);
	lua_register(L, "XPLMMapGetNorthHeading", XLuaMapGetNorthHeading);
	lua_register(L, "XPLMMapProject", XLuaMapProject);
	lua_register(L, "XPLMMapScaleMeter", XLuaMapScaleMeter);
	lua_register(L, "XPLMMapUnproject", XLuaMapUnproject);
	lua_register(L, "XPLMMeasureString", XLuaMeasureString);
	lua_register(L, "XPLMPlaceUserAtAirport", XLuaPlaceUserAtAirport);
	lua_register(L, "XPLMPlaceUserAtLocation", XLuaPlaceUserAtLocation);
	lua_register(L, "XPLMPlaneDrawState_t", MakeXPLMPlaneDrawState_t);
	lua_register(L, "XPLMPlayPCMOnBus", XLuaPlayPCMOnBus);
	lua_register(L, "XPLMPopOutAvionics", XLuaPopOutAvionics);
	lua_register(L, "XPLMProbeInfo_t", MakeXPLMProbeInfo_t);
	lua_register(L, "XPLMProbeTerrainXYZ", XLuaProbeTerrainXYZ);
	lua_register(L, "XPLMReadCameraPosition", XLuaReadCameraPosition);
	lua_register(L, "XPLMRegisterAvionicsCallbacksEx", XLuaRegisterAvionicsCallbacksEx);
	lua_register(L, "XPLMRegisterCommandHandler", XLuaRegisterCommandHandler);
	lua_register(L, "XPLMRegisterDataAccessor", XLuaRegisterDataAccessor);
	lua_register(L, "XPLMRegisterHotKey", XLuaRegisterHotKey);
	lua_register(L, "XPLMRegisterMapCreationHook", XLuaRegisterMapCreationHook);
	lua_register(L, "XPLMReleasePlanes", XLuaReleasePlanes);
	lua_register(L, "XPLMReloadPlugins", XLuaReloadPlugins);
	lua_register(L, "XPLMReloadScenery", XLuaReloadScenery);
	lua_register(L, "XPLMRemoveMenuItem", XLuaRemoveMenuItem);
	lua_register(L, "XPLMSaveDataFile", XLuaSaveDataFile);
	lua_register(L, "XPLMScheduleFlightLoop", XLuaScheduleFlightLoop);
	lua_register(L, "XPLMSendMessageToPlugin", XLuaSendMessageToPlugin);
	lua_register(L, "XPLMSetActiveAircraftCount", XLuaSetActiveAircraftCount);
	lua_register(L, "XPLMSetAircraftModel", XLuaSetAircraftModel);
	lua_register(L, "XPLMSetAudioCone", XLuaSetAudioCone);
	lua_register(L, "XPLMSetAudioFadeDistance", XLuaSetAudioFadeDistance);
	lua_register(L, "XPLMSetAudioPitch", XLuaSetAudioPitch);
	lua_register(L, "XPLMSetAudioPosition", XLuaSetAudioPosition);
	lua_register(L, "XPLMSetAudioVolume", XLuaSetAudioVolume);
	lua_register(L, "XPLMSetAvionicsBrightnessRheo", XLuaSetAvionicsBrightnessRheo);
	lua_register(L, "XPLMSetAvionicsGeometry", XLuaSetAvionicsGeometry);
	lua_register(L, "XPLMSetAvionicsGeometryOS", XLuaSetAvionicsGeometryOS);
	lua_register(L, "XPLMSetAvionicsPopupVisible", XLuaSetAvionicsPopupVisible);
	lua_register(L, "XPLMSetDatab", XLuaSetDatab);
	lua_register(L, "XPLMSetDatad", XLuaSetDatad);
	lua_register(L, "XPLMSetDataf", XLuaSetDataf);
	lua_register(L, "XPLMSetDatai", XLuaSetDatai);
	lua_register(L, "XPLMSetDatavf", XLuaSetDatavf);
	lua_register(L, "XPLMSetDatavi", XLuaSetDatavi);
	lua_register(L, "XPLMSetDestinationFMSEntry", XLuaSetDestinationFMSEntry);
	lua_register(L, "XPLMSetDestinationFMSFlightPlanEntry", XLuaSetDestinationFMSFlightPlanEntry);
	lua_register(L, "XPLMSetDirectToFMSFlightPlanEntry", XLuaSetDirectToFMSFlightPlanEntry);
	lua_register(L, "XPLMSetDisplayedFMSEntry", XLuaSetDisplayedFMSEntry);
	lua_register(L, "XPLMSetDisplayedFMSFlightPlanEntry", XLuaSetDisplayedFMSFlightPlanEntry);
	lua_register(L, "XPLMSetFMSEntryInfo", XLuaSetFMSEntryInfo);
	lua_register(L, "XPLMSetFMSEntryLatLon", XLuaSetFMSEntryLatLon);
	lua_register(L, "XPLMSetFMSFlightPlanEntryInfo", XLuaSetFMSFlightPlanEntryInfo);
	lua_register(L, "XPLMSetFMSFlightPlanEntryLatLon", XLuaSetFMSFlightPlanEntryLatLon);
	lua_register(L, "XPLMSetFMSFlightPlanEntryLatLonWithId", XLuaSetFMSFlightPlanEntryLatLonWithId);
	lua_register(L, "XPLMSetHotKeyCombination", XLuaSetHotKeyCombination);
	lua_register(L, "XPLMSetMenuItemName", XLuaSetMenuItemName);
	lua_register(L, "XPLMSetUsersAircraft", XLuaSetUsersAircraft);
	lua_register(L, "XPLMSetWeatherAtAirport", XLuaSetWeatherAtAirport);
	lua_register(L, "XPLMSetWeatherAtLocation", XLuaSetWeatherAtLocation);
	lua_register(L, "XPLMSimulateKeyPress", XLuaSimulateKeyPress);
	lua_register(L, "XPLMSpeakString", XLuaSpeakString);
	lua_register(L, "XPLMStopAudio", XLuaStopAudio);
	lua_register(L, "XPLMTakeAvionicsKeyboardFocus", XLuaTakeAvionicsKeyboardFocus);
	lua_register(L, "XPLMUnloadObject", XLuaUnloadObject);
	lua_register(L, "XPLMUnregisterAvionicsCallbacks", XLuaUnregisterAvionicsCallbacks);
	lua_register(L, "XPLMUnregisterCommandHandler", XLuaUnregisterCommandHandler);
	lua_register(L, "XPLMUnregisterDataAccessor", XLuaUnregisterDataAccessor);
	lua_register(L, "XPLMUnregisterHotKey", XLuaUnregisterHotKey);
	lua_register(L, "XPLMUpdateFlight", XLuaUpdateFlight);
	lua_register(L, "XPLMWeatherInfoClouds_t", MakeXPLMWeatherInfoClouds_t);
	lua_register(L, "XPLMWeatherInfoWinds_t", MakeXPLMWeatherInfoWinds_t);
	lua_register(L, "XPLMWeatherInfo_t", MakeXPLMWeatherInfo_t);
	lua_register(L, "XPLMWorldToLocal", XLuaWorldToLocal);

	// Userdata types
	RegType_XPLMAvionicsID(L);
	RegType_XPLMCommandRef(L);
	RegType_XPLMDataRef(L);
	RegType_XPLMFlightLoopID(L);
	RegType_XPLMHotKeyID(L);
	RegType_XPLMInstanceRef(L);
	RegType_XPLMMapLayerID(L);
	RegType_XPLMMapProjectionID(L);
	RegType_XPLMMenuID(L);
	RegType_XPLMNavRef(L);
	RegType_XPLMObjectRef(L);
	RegType_XPLMPluginID(L);
	RegType_XPLMProbeRef(L);
}
