void xlua_register_event(int EventID, char const* EventParamtype);

extern "C"
{
	#include <lua.h>
	#include <lauxlib.h>


	// Headers with typedefs etc.
	#include "XPLMCamera.h"
	#include "XPLMDataAccess.h"
	#include "XPLMDefs.h"
	#include "XPLMDisplay.h"
	#include "XPLMGraphics.h"
	#include "XPLMInstance.h"
	#include "XPLMMap.h"
	#include "XPLMMenus.h"
	#include "XPLMNavigation.h"
	#include "XPLMPanelGraphics.h"
	#include "XPLMPlanes.h"
	#include "XPLMPlugin.h"
	#include "XPLMProcessing.h"
	#include "XPLMScenery.h"
	#include "XPLMUtilities.h"
	#include "XPLMWeather.h"

	int XLuaCreateBrowserWindow(lua_State* L);
	int XLuaCreateImguiWindow(lua_State* L);
	int XLuaDestroyBrowserWindow(lua_State* L);
	int XLuaDestroyImguiWindow(lua_State* L);
	int XLuaAccumulateTouchZone(lua_State* L);
	int XLuaAcquirePlanes(lua_State* L);
	int XLuaAppendMenuItem(lua_State* L);
	int XLuaAppendMenuItemWithCommand(lua_State* L);
	int XLuaAppendMenuSeparator(lua_State* L);
	int XLuaAvionicsNeedsDrawing(lua_State* L);
	int XLuaAvionicsSetTouchEventHandler(lua_State* L);
	int XLuaBeginRetainedDrawing(lua_State* L);
	int XLuaBeginSetupStencilMask(lua_State* L);
	int XLuaBeginWeatherUpdate(lua_State* L);
	int XLuaBringWindowToFront(lua_State* L);
	int MakeXPLMCameraPosition_t(lua_State* L);
	int XLuaCanWriteDataRef(lua_State* L);
	int XLuaCheckMenuItem(lua_State* L);
	int XLuaCheckMenuItemState(lua_State* L);
	int XLuaClearAllMenuItems(lua_State* L);
	int XLuaClearFMSEntry(lua_State* L);
	int XLuaClearFMSFlightPlanEntry(lua_State* L);
	int XLuaClearStencilMask(lua_State* L);
	int XLuaCommandBegin(lua_State* L);
	int XLuaCommandEnd(lua_State* L);
	int XLuaCommandOnce(lua_State* L);
	int XLuaControlCamera(lua_State* L);
	int XLuaCountAircraft(lua_State* L);
	int XLuaCountDataRefs(lua_State* L);
	int XLuaCountFMSEntries(lua_State* L);
	int XLuaCountFMSFlightPlanEntries(lua_State* L);
	int XLuaCountPlugins(lua_State* L);
	int XLuaCreateAvionicsEx(lua_State* L);
	int MakeXPLMCreateAvionics_t(lua_State* L);
	int XLuaCreateCommand(lua_State* L);
	int XLuaCreateFlightLoop(lua_State* L);
	int MakeXPLMCreateFlightLoop_t(lua_State* L);
	int XLuaCreateFont(lua_State* L);
	int XLuaCreateInstance(lua_State* L);
	int XLuaCreateMapDisplay(lua_State* L);
	int XLuaCreateMapLayer(lua_State* L);
	int MakeXPLMCreateMapLayer_t(lua_State* L);
	int MakeXPLMCreateMap_t(lua_State* L);
	int XLuaCreateMenu(lua_State* L);
	int XLuaCreateProbe(lua_State* L);
	int XLuaCreateSVTDisplay(lua_State* L);
	int MakeXPLMCreateSVT_t(lua_State* L);
	int XLuaCreateTextureAtlas(lua_State* L);
	int MakeXPLMCreateWindow_t(lua_State* L);
	int MakeXPLMCustomizeAvionics_t(lua_State* L);
	int MakeXPLMDataRefInfo_t(lua_State* L);
	int XLuaDebugString(lua_State* L);
	int XLuaDegMagneticToDegTrue(lua_State* L);
	int XLuaDegTrueToDegMagnetic(lua_State* L);
	int XLuaDestroyAvionics(lua_State* L);
	int XLuaDestroyFlightLoop(lua_State* L);
	int XLuaDestroyFont(lua_State* L);
	int XLuaDestroyInstance(lua_State* L);
	int XLuaDestroyMapDisplay(lua_State* L);
	int XLuaDestroyMapLayer(lua_State* L);
	int XLuaDestroyMenu(lua_State* L);
	int XLuaDestroyProbe(lua_State* L);
	int XLuaDestroyRetainedDrawing(lua_State* L);
	int XLuaDestroySVTDisplay(lua_State* L);
	int XLuaDestroyTextureAtlas(lua_State* L);
	int XLuaDisableAIForPlane(lua_State* L);
	int XLuaDisablePlugin(lua_State* L);
	int XLuaDontControlCamera(lua_State* L);
	int MakeXPLMDrawInfoDouble_t(lua_State* L);
	int MakeXPLMDrawInfo_t(lua_State* L);
	int XLuaDrawMapIconFromSheet(lua_State* L);
	int XLuaDrawMapLabel(lua_State* L);
	int XLuaDrawNumber(lua_State* L);
	int XLuaDrawRetained(lua_State* L);
	int XLuaDrawString(lua_State* L);
	int XLuaEnableFeature(lua_State* L);
	int XLuaEnableMenuItem(lua_State* L);
	int XLuaEnablePlugin(lua_State* L);
	int XLuaEndRetainedDrawing(lua_State* L);
	int XLuaEndSetupStencilMask(lua_State* L);
	int XLuaEndWeatherUpdate(lua_State* L);
	int XLuaEnumerateFeatures(lua_State* L);
	int XLuaEraseWeatherAtAirport(lua_State* L);
	int XLuaEraseWeatherAtLocation(lua_State* L);
	int XLuaFindAircraftMenu(lua_State* L);
	int XLuaFindCommand(lua_State* L);
	int XLuaFindDataRef(lua_State* L);
	int XLuaFindFirstNavAidOfType(lua_State* L);
	int XLuaFindLastNavAidOfType(lua_State* L);
	int XLuaFindNavAid(lua_State* L);
	int XLuaFindPluginByPath(lua_State* L);
	int XLuaFindPluginBySignature(lua_State* L);
	int XLuaFindPluginsMenu(lua_State* L);
	int MakeXPLMFixedString150_t(lua_State* L);
	int XLuaFontAddFace(lua_State* L);
	int XLuaFontDrawString(lua_State* L);
	int XLuaFontDrawStringFixedSpacing(lua_State* L);
	int XLuaFontDrawStringRotated(lua_State* L);
	int XLuaFontDrawStringWordWrapped(lua_State* L);
	int XLuaFontFitForward(lua_State* L);
	int XLuaFontFitReverse(lua_State* L);
	int XLuaFontGetLineCount(lua_State* L);
	int XLuaFontGetMetrics(lua_State* L);
	int XLuaFontMeasureString(lua_State* L);
	int MakeXPLMFontMetrics_t(lua_State* L);
	int XLuaGetAllMonitorBoundsGlobal(lua_State* L);
	int XLuaGetAllMonitorBoundsOS(lua_State* L);
	int XLuaGetAvionicsBrightnessRheo(lua_State* L);
	int XLuaGetAvionicsBusVoltsRatio(lua_State* L);
	int XLuaGetAvionicsGeometry(lua_State* L);
	int XLuaGetAvionicsGeometryOS(lua_State* L);
	int XLuaGetAvionicsHandle(lua_State* L);
	int XLuaGetCycleNumber(lua_State* L);
	int XLuaGetDataRefInfo(lua_State* L);
	int XLuaGetDataRefTypes(lua_State* L);
	int XLuaGetDataRefsByIndex(lua_State* L);
	int XLuaGetDatab(lua_State* L);
	int XLuaGetDatad(lua_State* L);
	int XLuaGetDataf(lua_State* L);
	int XLuaGetDatai(lua_State* L);
	int XLuaGetDatavf(lua_State* L);
	int XLuaGetDatavi(lua_State* L);
	int XLuaGetDestinationFMSEntry(lua_State* L);
	int XLuaGetDestinationFMSFlightPlanEntry(lua_State* L);
	int XLuaGetDirectorySeparator(lua_State* L);
	int XLuaGetDisplayedFMSEntry(lua_State* L);
	int XLuaGetDisplayedFMSFlightPlanEntry(lua_State* L);
	int XLuaGetElapsedTime(lua_State* L);
	int XLuaGetFMSEntryInfo(lua_State* L);
	int XLuaGetFMSFlightPlanEntryInfo(lua_State* L);
	int XLuaGetFirstNavAid(lua_State* L);
	int XLuaGetFontDimensions(lua_State* L);
	int XLuaGetGPSDestination(lua_State* L);
	int XLuaGetGPSDestinationType(lua_State* L);
	int XLuaGetLanguage(lua_State* L);
	int XLuaGetMETARForAirport(lua_State* L);
	int XLuaGetMagneticVariation(lua_State* L);
	int XLuaGetMouseLocationGlobal(lua_State* L);
	int XLuaGetMyID(lua_State* L);
	int XLuaGetNavAidInfo(lua_State* L);
	int XLuaGetNextNavAid(lua_State* L);
	int XLuaGetNthAircraftModel(lua_State* L);
	int XLuaGetNthPlugin(lua_State* L);
	int XLuaGetPluginInfo(lua_State* L);
	int XLuaGetPrefsPath(lua_State* L);
	int XLuaGetScreenBoundsGlobal(lua_State* L);
	int XLuaGetScreenSize(lua_State* L);
	int XLuaGetSystemPath(lua_State* L);
	int XLuaGetVersions(lua_State* L);
	int XLuaGetVirtualKeyDescription(lua_State* L);
	int XLuaGetWeatherAtLocation(lua_State* L);
	int XLuaGetWindowGeometry(lua_State* L);
	int XLuaGetWindowGeometryOS(lua_State* L);
	int XLuaGetWindowGeometryVR(lua_State* L);
	int XLuaGetWindowIsVisible(lua_State* L);
	int XLuaGetWindowRefCon(lua_State* L);
	int XLuaHasAvionicsKeyboardFocus(lua_State* L);
	int XLuaHasFeature(lua_State* L);
	int XLuaHasKeyboardFocus(lua_State* L);
	int XLuaInitFlight(lua_State* L);
	int XLuaInstanceSetAutoShift(lua_State* L);
	int XLuaInstanceSetPosition(lua_State* L);
	int XLuaInstanceSetPositionDouble(lua_State* L);
	int XLuaIsAvionicsBound(lua_State* L);
	int XLuaIsAvionicsMappedToVR(lua_State* L);
	int XLuaIsAvionicsPoppedOut(lua_State* L);
	int XLuaIsAvionicsPopupVisible(lua_State* L);
	int XLuaIsCameraBeingControlled(lua_State* L);
	int XLuaIsCursorOverAvionics(lua_State* L);
	int XLuaIsDataRefGood(lua_State* L);
	int XLuaIsFeatureEnabled(lua_State* L);
	int XLuaIsPluginEnabled(lua_State* L);
	int XLuaIsWindowInFront(lua_State* L);
	int XLuaLineLoop(lua_State* L);
	int XLuaLineLoopStipple(lua_State* L);
	int XLuaLineLoopWithWidth(lua_State* L);
	int XLuaLineLoopc(lua_State* L);
	int XLuaLineLoopcWithWidth(lua_State* L);
	int XLuaLineStrip(lua_State* L);
	int XLuaLineStripStipple(lua_State* L);
	int XLuaLineStripWithWidth(lua_State* L);
	int XLuaLineStripc(lua_State* L);
	int XLuaLineStripcWithWidth(lua_State* L);
	int XLuaLines(lua_State* L);
	int XLuaLinesStipple(lua_State* L);
	int XLuaLinesWithWidth(lua_State* L);
	int XLuaLinesc(lua_State* L);
	int XLuaLinescWithWidth(lua_State* L);
	int XLuaLoadDataFile(lua_State* L);
	int XLuaLoadFMSFlightPlan(lua_State* L);
	int XLuaLoadObject(lua_State* L);
	int XLuaLoadObjectAsync(lua_State* L);
	int XLuaLocalToWorld(lua_State* L);
	int XLuaLookupObjects(lua_State* L);
	int XLuaMakeColor(lua_State* L);
	int MakeXPLMMapCustomData_t(lua_State* L);
	int XLuaMapDisplayDrawIn(lua_State* L);
	int XLuaMapExists(lua_State* L);
	int XLuaMapGetNorthHeading(lua_State* L);
	int XLuaMapProject(lua_State* L);
	int XLuaMapScaleMeter(lua_State* L);
	int XLuaMapUnproject(lua_State* L);
	int XLuaMeasureString(lua_State* L);
	int XLuaPlaceUserAtAirport(lua_State* L);
	int XLuaPlaceUserAtLocation(lua_State* L);
	int XLuaPolygon(lua_State* L);
	int XLuaPolygonWithWidth(lua_State* L);
	int XLuaPolygonc(lua_State* L);
	int XLuaPolygoncWithWidth(lua_State* L);
	int XLuaPopOutAvionics(lua_State* L);
	int MakeXPLMProbeInfo_t(lua_State* L);
	int XLuaProbeTerrainXYZ(lua_State* L);
	int XLuaQuadstrip(lua_State* L);
	int XLuaQuadstripWithWidth(lua_State* L);
	int XLuaQuadstripc(lua_State* L);
	int XLuaQuadstripcWithWidth(lua_State* L);
	int XLuaReadCameraPosition(lua_State* L);
	int XLuaRegisterAvionicsCallbacksEx(lua_State* L);
	int XLuaRegisterCommandHandler(lua_State* L);
	int XLuaRegisterDataAccessor(lua_State* L);
	int XLuaRegisterMapCreationHook(lua_State* L);
	int XLuaReleasePlanes(lua_State* L);
	int XLuaReloadPlugins(lua_State* L);
	int XLuaReloadScenery(lua_State* L);
	int XLuaReloadThisPlugin(lua_State* L);
	int XLuaRemoveMenuItem(lua_State* L);
	int MakeXPLMSVTCustomData_t(lua_State* L);
	int XLuaSVTDisplayDrawIn(lua_State* L);
	int XLuaSaveDataFile(lua_State* L);
	int XLuaScheduleFlightLoop(lua_State* L);
	int XLuaScissorPop(lua_State* L);
	int XLuaScissorPush(lua_State* L);
	int XLuaScissorSet(lua_State* L);
	int XLuaScissorShrink(lua_State* L);
	int XLuaSendMessageToPlugin(lua_State* L);
	int XLuaSetActiveAircraftCount(lua_State* L);
	int XLuaSetAircraftModel(lua_State* L);
	int XLuaSetAvionicsBrightnessRheo(lua_State* L);
	int XLuaSetAvionicsGeometry(lua_State* L);
	int XLuaSetAvionicsGeometryOS(lua_State* L);
	int XLuaSetAvionicsMappedToVR(lua_State* L);
	int XLuaSetAvionicsPopupVisible(lua_State* L);
	int XLuaSetDatab(lua_State* L);
	int XLuaSetDatad(lua_State* L);
	int XLuaSetDataf(lua_State* L);
	int XLuaSetDatai(lua_State* L);
	int XLuaSetDatavf(lua_State* L);
	int XLuaSetDatavi(lua_State* L);
	int XLuaSetDestinationFMSEntry(lua_State* L);
	int XLuaSetDestinationFMSFlightPlanEntry(lua_State* L);
	int XLuaSetDirectToFMSFlightPlanEntry(lua_State* L);
	int XLuaSetDisplayedFMSEntry(lua_State* L);
	int XLuaSetDisplayedFMSFlightPlanEntry(lua_State* L);
	int XLuaSetFMSEntryInfo(lua_State* L);
	int XLuaSetFMSEntryLatLon(lua_State* L);
	int XLuaSetFMSFlightPlanEntryInfo(lua_State* L);
	int XLuaSetFMSFlightPlanEntryLatLon(lua_State* L);
	int XLuaSetFMSFlightPlanEntryLatLonWithId(lua_State* L);
	int XLuaSetMenuItemName(lua_State* L);
	int XLuaSetUsersAircraft(lua_State* L);
	int XLuaSetWeatherAtAirport(lua_State* L);
	int XLuaSetWeatherAtLocation(lua_State* L);
	int XLuaSetWindowGeometry(lua_State* L);
	int XLuaSetWindowGeometryOS(lua_State* L);
	int XLuaSetWindowGeometryVR(lua_State* L);
	int XLuaSetWindowGravity(lua_State* L);
	int XLuaSetWindowIsVisible(lua_State* L);
	int XLuaSetWindowPositioningMode(lua_State* L);
	int XLuaSetWindowRefCon(lua_State* L);
	int XLuaSetWindowResizingLimits(lua_State* L);
	int XLuaSetWindowTitle(lua_State* L);
	int XLuaSpeakString(lua_State* L);
	int XLuaTakeAvionicsKeyboardFocus(lua_State* L);
	int XLuaTakeKeyboardFocus(lua_State* L);
	int XLuaTextureAtlasAddImage(lua_State* L);
	int XLuaTextureAtlasAddImageFile(lua_State* L);
	int XLuaTextureAtlasAddImageFileSet(lua_State* L);
	int XLuaTextureAtlasBake(lua_State* L);
	int XLuaTextureAtlasDrawAt(lua_State* L);
	int XLuaTextureAtlasDrawIn(lua_State* L);
	int XLuaTextureAtlasDrawMesh(lua_State* L);
	int XLuaTextureAtlasDrawScaled(lua_State* L);
	int XLuaTextureAtlasDrawStretched(lua_State* L);
	int XLuaTextureAtlasGetImageHeight(lua_State* L);
	int XLuaTextureAtlasGetImageUVMap(lua_State* L);
	int XLuaTextureAtlasGetImageWidth(lua_State* L);
	int XLuaTextureSourceDrawIn(lua_State* L);
	int XLuaTextureSourceDrawMesh(lua_State* L);
	int MakeXPLMTextureVertex_t(lua_State* L);
	int MakeXPLMTouchZoneSpec_t(lua_State* L);
	int XLuaTransformPop(lua_State* L);
	int XLuaTransformPush(lua_State* L);
	int XLuaTransformRotate(lua_State* L);
	int XLuaTransformScale(lua_State* L);
	int XLuaTransformTranslate(lua_State* L);
	int XLuaUnloadObject(lua_State* L);
	int XLuaUnregisterAvionicsCallbacks(lua_State* L);
	int XLuaUnregisterCommandHandler(lua_State* L);
	int XLuaUnregisterDataAccessor(lua_State* L);
	int XLuaUpdateFlight(lua_State* L);
	int XLuaUseStencilMask(lua_State* L);
	int MakeXPLMVertexColor_t(lua_State* L);
	int MakeXPLMVertex_t(lua_State* L);
	int MakeXPLMWeatherInfoClouds_t(lua_State* L);
	int MakeXPLMWeatherInfoWinds_t(lua_State* L);
	int MakeXPLMWeatherInfo_t(lua_State* L);
	int XLuaWindowAddBrowserFunction(lua_State* L);
	int XLuaWindowInjectScript(lua_State* L);
	int XLuaWindowIsInVR(lua_State* L);
	int XLuaWindowIsPoppedOut(lua_State* L);
	int XLuaWindowRefresh(lua_State* L);
	int XLuaWindowSetTouchEventHandler(lua_State* L);
	int XLuaWindowSetURL(lua_State* L);
	int XLuaWorldToLocal(lua_State* L);

	// Typedefs
	void RegType_XPLMAvionicsID(lua_State* L);
	XPLMAvionicsID* Make_XPLMAvionicsID(lua_State* L, XPLMAvionicsID const& init);
	void RegType_XPLMCommandRef(lua_State* L);
	XPLMCommandRef* Make_XPLMCommandRef(lua_State* L, XPLMCommandRef const& init);
	void RegType_XPLMDataRef(lua_State* L);
	XPLMDataRef* Make_XPLMDataRef(lua_State* L, XPLMDataRef const& init);
	void RegType_XPLMFlightLoopID(lua_State* L);
	XPLMFlightLoopID* Make_XPLMFlightLoopID(lua_State* L, XPLMFlightLoopID const& init);
	void RegType_XPLMFontHandle(lua_State* L);
	XPLMFontHandle* Make_XPLMFontHandle(lua_State* L, XPLMFontHandle const& init);
	void RegType_XPLMInstanceRef(lua_State* L);
	XPLMInstanceRef* Make_XPLMInstanceRef(lua_State* L, XPLMInstanceRef const& init);
	void RegType_XPLMMapDisplayRef(lua_State* L);
	XPLMMapDisplayRef* Make_XPLMMapDisplayRef(lua_State* L, XPLMMapDisplayRef const& init);
	void RegType_XPLMMapLayerID(lua_State* L);
	XPLMMapLayerID* Make_XPLMMapLayerID(lua_State* L, XPLMMapLayerID const& init);
	void RegType_XPLMMapProjectionID(lua_State* L);
	XPLMMapProjectionID* Make_XPLMMapProjectionID(lua_State* L, XPLMMapProjectionID const& init);
	void RegType_XPLMMenuID(lua_State* L);
	XPLMMenuID* Make_XPLMMenuID(lua_State* L, XPLMMenuID const& init);
	void RegType_XPLMNavRef(lua_State* L);
	XPLMNavRef* Make_XPLMNavRef(lua_State* L, XPLMNavRef const& init);
	void RegType_XPLMObjectRef(lua_State* L);
	XPLMObjectRef* Make_XPLMObjectRef(lua_State* L, XPLMObjectRef const& init);
	void RegType_XPLMPluginID(lua_State* L);
	XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);
	void RegType_XPLMProbeRef(lua_State* L);
	XPLMProbeRef* Make_XPLMProbeRef(lua_State* L, XPLMProbeRef const& init);
	void RegType_XPLMRetainedDrawing_t(lua_State* L);
	XPLMRetainedDrawing_t* Make_XPLMRetainedDrawing_t(lua_State* L, XPLMRetainedDrawing_t const& init);
	void RegType_XPLMSVTDisplayRef(lua_State* L);
	XPLMSVTDisplayRef* Make_XPLMSVTDisplayRef(lua_State* L, XPLMSVTDisplayRef const& init);
	void RegType_XPLMTextureAtlasRef(lua_State* L);
	XPLMTextureAtlasRef* Make_XPLMTextureAtlasRef(lua_State* L, XPLMTextureAtlasRef const& init);
	void RegType_XPLMWindowID(lua_State* L);
	XPLMWindowID* Make_XPLMWindowID(lua_State* L, XPLMWindowID const& init);

	// Enums
	void RegEnum_XPLMCameraControlDuration(lua_State* L);
	void RegEnum_XPLMCharSet_t(lua_State* L);
	void RegEnum_XPLMCommandPhase(lua_State* L);
	void RegEnum_XPLMCursorStatus(lua_State* L);
	void RegEnum_XPLMDataFileType(lua_State* L);
	void RegEnum_XPLMDataTypeID(lua_State* L);
	void RegEnum_XPLMDeviceID(lua_State* L);
	void RegEnum_XPLMFlightLoopPhaseType(lua_State* L);
	void RegEnum_XPLMFontID(lua_State* L);
	void RegEnum_XPLMHostApplicationID(lua_State* L);
	void RegEnum_XPLMInitResult(lua_State* L);
	void RegEnum_XPLMJustification_t(lua_State* L);
	void RegEnum_XPLMKeyFlags(lua_State* L);
	void RegEnum_XPLMLanguageCode(lua_State* L);
	void RegEnum_XPLMMapLayerType(lua_State* L);
	void RegEnum_XPLMMapLayers(lua_State* L);
	void RegEnum_XPLMMapOrientation(lua_State* L);
	void RegEnum_XPLMMapStyle(lua_State* L);
	void RegEnum_XPLMMenuCheck(lua_State* L);
	void RegEnum_XPLMMouseStatus(lua_State* L);
	void RegEnum_XPLMNavFlightPlan(lua_State* L);
	void RegEnum_XPLMNavType(lua_State* L);
	void RegEnum_XPLMProbeResult(lua_State* L);
	void RegEnum_XPLMProbeType(lua_State* L);
	void RegEnum_XPLMSVTFeatures(lua_State* L);
	void RegEnum_XPLMTextureSource(lua_State* L);
	void RegEnum_XPLMTouchZone(lua_State* L);
	void RegEnum_XPLMWindowContentType(lua_State* L);
	void RegEnum_XPLMWindowDecoration(lua_State* L);
	void RegEnum_XPLMWindowLayer(lua_State* L);
	void RegEnum_XPLMWindowPositioningMode(lua_State* L);

	// Defines
	void RegDefines_XPLMDefs(lua_State* L);
	void RegDefines_XPLMMap(lua_State* L);
	void RegDefines_XPLMNavigation(lua_State* L);
	void RegDefines_XPLMPlanes(lua_State* L);
	void RegDefines_XPLMPlugin(lua_State* L);
	void RegDefines_XPLMWeather(lua_State* L);
}		// extern "C"


void add_xplm_to_interp(lua_State* L)
{
	lua_register(L, "XLuaCreateBrowserWindow", XLuaCreateBrowserWindow);
	lua_register(L, "XLuaCreateImguiWindow", XLuaCreateImguiWindow);
	lua_register(L, "XLuaDestroyBrowserWindow", XLuaDestroyBrowserWindow);
	lua_register(L, "XLuaDestroyImguiWindow", XLuaDestroyImguiWindow);
	lua_register(L, "XPLMAccumulateTouchZone", XLuaAccumulateTouchZone);
	lua_register(L, "XPLMAcquirePlanes", XLuaAcquirePlanes);
	lua_register(L, "XPLMAppendMenuItem", XLuaAppendMenuItem);
	lua_register(L, "XPLMAppendMenuItemWithCommand", XLuaAppendMenuItemWithCommand);
	lua_register(L, "XPLMAppendMenuSeparator", XLuaAppendMenuSeparator);
	lua_register(L, "XPLMAvionicsNeedsDrawing", XLuaAvionicsNeedsDrawing);
	lua_register(L, "XPLMAvionicsSetTouchEventHandler", XLuaAvionicsSetTouchEventHandler);
	lua_register(L, "XPLMBeginRetainedDrawing", XLuaBeginRetainedDrawing);
	lua_register(L, "XPLMBeginSetupStencilMask", XLuaBeginSetupStencilMask);
	lua_register(L, "XPLMBeginWeatherUpdate", XLuaBeginWeatherUpdate);
	lua_register(L, "XPLMBringWindowToFront", XLuaBringWindowToFront);
	lua_register(L, "XPLMCameraPosition_t", MakeXPLMCameraPosition_t);
	lua_register(L, "XPLMCanWriteDataRef", XLuaCanWriteDataRef);
	lua_register(L, "XPLMCheckMenuItem", XLuaCheckMenuItem);
	lua_register(L, "XPLMCheckMenuItemState", XLuaCheckMenuItemState);
	lua_register(L, "XPLMClearAllMenuItems", XLuaClearAllMenuItems);
	lua_register(L, "XPLMClearFMSEntry", XLuaClearFMSEntry);
	lua_register(L, "XPLMClearFMSFlightPlanEntry", XLuaClearFMSFlightPlanEntry);
	lua_register(L, "XPLMClearStencilMask", XLuaClearStencilMask);
	lua_register(L, "XPLMCommandBegin", XLuaCommandBegin);
	lua_register(L, "XPLMCommandEnd", XLuaCommandEnd);
	lua_register(L, "XPLMCommandOnce", XLuaCommandOnce);
	lua_register(L, "XPLMControlCamera", XLuaControlCamera);
	lua_register(L, "XPLMCountAircraft", XLuaCountAircraft);
	lua_register(L, "XPLMCountDataRefs", XLuaCountDataRefs);
	lua_register(L, "XPLMCountFMSEntries", XLuaCountFMSEntries);
	lua_register(L, "XPLMCountFMSFlightPlanEntries", XLuaCountFMSFlightPlanEntries);
	lua_register(L, "XPLMCountPlugins", XLuaCountPlugins);
	lua_register(L, "XPLMCreateAvionicsEx", XLuaCreateAvionicsEx);
	lua_register(L, "XPLMCreateAvionics_t", MakeXPLMCreateAvionics_t);
	lua_register(L, "XPLMCreateCommand", XLuaCreateCommand);
	lua_register(L, "XPLMCreateFlightLoop", XLuaCreateFlightLoop);
	lua_register(L, "XPLMCreateFlightLoop_t", MakeXPLMCreateFlightLoop_t);
	lua_register(L, "XPLMCreateFont", XLuaCreateFont);
	lua_register(L, "XPLMCreateInstance", XLuaCreateInstance);
	lua_register(L, "XPLMCreateMapDisplay", XLuaCreateMapDisplay);
	lua_register(L, "XPLMCreateMapLayer", XLuaCreateMapLayer);
	lua_register(L, "XPLMCreateMapLayer_t", MakeXPLMCreateMapLayer_t);
	lua_register(L, "XPLMCreateMap_t", MakeXPLMCreateMap_t);
	lua_register(L, "XPLMCreateMenu", XLuaCreateMenu);
	lua_register(L, "XPLMCreateProbe", XLuaCreateProbe);
	lua_register(L, "XPLMCreateSVTDisplay", XLuaCreateSVTDisplay);
	lua_register(L, "XPLMCreateSVT_t", MakeXPLMCreateSVT_t);
	lua_register(L, "XPLMCreateTextureAtlas", XLuaCreateTextureAtlas);
	lua_register(L, "XPLMCreateWindow_t", MakeXPLMCreateWindow_t);
	lua_register(L, "XPLMCustomizeAvionics_t", MakeXPLMCustomizeAvionics_t);
	lua_register(L, "XPLMDataRefInfo_t", MakeXPLMDataRefInfo_t);
	lua_register(L, "XPLMDebugString", XLuaDebugString);
	lua_register(L, "XPLMDegMagneticToDegTrue", XLuaDegMagneticToDegTrue);
	lua_register(L, "XPLMDegTrueToDegMagnetic", XLuaDegTrueToDegMagnetic);
	lua_register(L, "XPLMDestroyAvionics", XLuaDestroyAvionics);
	lua_register(L, "XPLMDestroyFlightLoop", XLuaDestroyFlightLoop);
	lua_register(L, "XPLMDestroyFont", XLuaDestroyFont);
	lua_register(L, "XPLMDestroyInstance", XLuaDestroyInstance);
	lua_register(L, "XPLMDestroyMapDisplay", XLuaDestroyMapDisplay);
	lua_register(L, "XPLMDestroyMapLayer", XLuaDestroyMapLayer);
	lua_register(L, "XPLMDestroyMenu", XLuaDestroyMenu);
	lua_register(L, "XPLMDestroyProbe", XLuaDestroyProbe);
	lua_register(L, "XPLMDestroyRetainedDrawing", XLuaDestroyRetainedDrawing);
	lua_register(L, "XPLMDestroySVTDisplay", XLuaDestroySVTDisplay);
	lua_register(L, "XPLMDestroyTextureAtlas", XLuaDestroyTextureAtlas);
	lua_register(L, "XPLMDisableAIForPlane", XLuaDisableAIForPlane);
	lua_register(L, "XPLMDisablePlugin", XLuaDisablePlugin);
	lua_register(L, "XPLMDontControlCamera", XLuaDontControlCamera);
	lua_register(L, "XPLMDrawInfoDouble_t", MakeXPLMDrawInfoDouble_t);
	lua_register(L, "XPLMDrawInfo_t", MakeXPLMDrawInfo_t);
	lua_register(L, "XPLMDrawMapIconFromSheet", XLuaDrawMapIconFromSheet);
	lua_register(L, "XPLMDrawMapLabel", XLuaDrawMapLabel);
	lua_register(L, "XPLMDrawNumber", XLuaDrawNumber);
	lua_register(L, "XPLMDrawRetained", XLuaDrawRetained);
	lua_register(L, "XPLMDrawString", XLuaDrawString);
	lua_register(L, "XPLMEnableFeature", XLuaEnableFeature);
	lua_register(L, "XPLMEnableMenuItem", XLuaEnableMenuItem);
	lua_register(L, "XPLMEnablePlugin", XLuaEnablePlugin);
	lua_register(L, "XPLMEndRetainedDrawing", XLuaEndRetainedDrawing);
	lua_register(L, "XPLMEndSetupStencilMask", XLuaEndSetupStencilMask);
	lua_register(L, "XPLMEndWeatherUpdate", XLuaEndWeatherUpdate);
	lua_register(L, "XPLMEnumerateFeatures", XLuaEnumerateFeatures);
	lua_register(L, "XPLMEraseWeatherAtAirport", XLuaEraseWeatherAtAirport);
	lua_register(L, "XPLMEraseWeatherAtLocation", XLuaEraseWeatherAtLocation);
	lua_register(L, "XPLMFindAircraftMenu", XLuaFindAircraftMenu);
	lua_register(L, "XPLMFindCommand", XLuaFindCommand);
	lua_register(L, "XPLMFindDataRef", XLuaFindDataRef);
	lua_register(L, "XPLMFindFirstNavAidOfType", XLuaFindFirstNavAidOfType);
	lua_register(L, "XPLMFindLastNavAidOfType", XLuaFindLastNavAidOfType);
	lua_register(L, "XPLMFindNavAid", XLuaFindNavAid);
	lua_register(L, "XPLMFindPluginByPath", XLuaFindPluginByPath);
	lua_register(L, "XPLMFindPluginBySignature", XLuaFindPluginBySignature);
	lua_register(L, "XPLMFindPluginsMenu", XLuaFindPluginsMenu);
	lua_register(L, "XPLMFixedString150_t", MakeXPLMFixedString150_t);
	lua_register(L, "XPLMFontAddFace", XLuaFontAddFace);
	lua_register(L, "XPLMFontDrawString", XLuaFontDrawString);
	lua_register(L, "XPLMFontDrawStringFixedSpacing", XLuaFontDrawStringFixedSpacing);
	lua_register(L, "XPLMFontDrawStringRotated", XLuaFontDrawStringRotated);
	lua_register(L, "XPLMFontDrawStringWordWrapped", XLuaFontDrawStringWordWrapped);
	lua_register(L, "XPLMFontFitForward", XLuaFontFitForward);
	lua_register(L, "XPLMFontFitReverse", XLuaFontFitReverse);
	lua_register(L, "XPLMFontGetLineCount", XLuaFontGetLineCount);
	lua_register(L, "XPLMFontGetMetrics", XLuaFontGetMetrics);
	lua_register(L, "XPLMFontMeasureString", XLuaFontMeasureString);
	lua_register(L, "XPLMFontMetrics_t", MakeXPLMFontMetrics_t);
	lua_register(L, "XPLMGetAllMonitorBoundsGlobal", XLuaGetAllMonitorBoundsGlobal);
	lua_register(L, "XPLMGetAllMonitorBoundsOS", XLuaGetAllMonitorBoundsOS);
	lua_register(L, "XPLMGetAvionicsBrightnessRheo", XLuaGetAvionicsBrightnessRheo);
	lua_register(L, "XPLMGetAvionicsBusVoltsRatio", XLuaGetAvionicsBusVoltsRatio);
	lua_register(L, "XPLMGetAvionicsGeometry", XLuaGetAvionicsGeometry);
	lua_register(L, "XPLMGetAvionicsGeometryOS", XLuaGetAvionicsGeometryOS);
	lua_register(L, "XPLMGetAvionicsHandle", XLuaGetAvionicsHandle);
	lua_register(L, "XPLMGetCycleNumber", XLuaGetCycleNumber);
	lua_register(L, "XPLMGetDataRefInfo", XLuaGetDataRefInfo);
	lua_register(L, "XPLMGetDataRefTypes", XLuaGetDataRefTypes);
	lua_register(L, "XPLMGetDataRefsByIndex", XLuaGetDataRefsByIndex);
	lua_register(L, "XPLMGetDatab", XLuaGetDatab);
	lua_register(L, "XPLMGetDatad", XLuaGetDatad);
	lua_register(L, "XPLMGetDataf", XLuaGetDataf);
	lua_register(L, "XPLMGetDatai", XLuaGetDatai);
	lua_register(L, "XPLMGetDatavf", XLuaGetDatavf);
	lua_register(L, "XPLMGetDatavi", XLuaGetDatavi);
	lua_register(L, "XPLMGetDestinationFMSEntry", XLuaGetDestinationFMSEntry);
	lua_register(L, "XPLMGetDestinationFMSFlightPlanEntry", XLuaGetDestinationFMSFlightPlanEntry);
	lua_register(L, "XPLMGetDirectorySeparator", XLuaGetDirectorySeparator);
	lua_register(L, "XPLMGetDisplayedFMSEntry", XLuaGetDisplayedFMSEntry);
	lua_register(L, "XPLMGetDisplayedFMSFlightPlanEntry", XLuaGetDisplayedFMSFlightPlanEntry);
	lua_register(L, "XPLMGetElapsedTime", XLuaGetElapsedTime);
	lua_register(L, "XPLMGetFMSEntryInfo", XLuaGetFMSEntryInfo);
	lua_register(L, "XPLMGetFMSFlightPlanEntryInfo", XLuaGetFMSFlightPlanEntryInfo);
	lua_register(L, "XPLMGetFirstNavAid", XLuaGetFirstNavAid);
	lua_register(L, "XPLMGetFontDimensions", XLuaGetFontDimensions);
	lua_register(L, "XPLMGetGPSDestination", XLuaGetGPSDestination);
	lua_register(L, "XPLMGetGPSDestinationType", XLuaGetGPSDestinationType);
	lua_register(L, "XPLMGetLanguage", XLuaGetLanguage);
	lua_register(L, "XPLMGetMETARForAirport", XLuaGetMETARForAirport);
	lua_register(L, "XPLMGetMagneticVariation", XLuaGetMagneticVariation);
	lua_register(L, "XPLMGetMouseLocationGlobal", XLuaGetMouseLocationGlobal);
	lua_register(L, "XPLMGetMyID", XLuaGetMyID);
	lua_register(L, "XPLMGetNavAidInfo", XLuaGetNavAidInfo);
	lua_register(L, "XPLMGetNextNavAid", XLuaGetNextNavAid);
	lua_register(L, "XPLMGetNthAircraftModel", XLuaGetNthAircraftModel);
	lua_register(L, "XPLMGetNthPlugin", XLuaGetNthPlugin);
	lua_register(L, "XPLMGetPluginInfo", XLuaGetPluginInfo);
	lua_register(L, "XPLMGetPrefsPath", XLuaGetPrefsPath);
	lua_register(L, "XPLMGetScreenBoundsGlobal", XLuaGetScreenBoundsGlobal);
	lua_register(L, "XPLMGetScreenSize", XLuaGetScreenSize);
	lua_register(L, "XPLMGetSystemPath", XLuaGetSystemPath);
	lua_register(L, "XPLMGetVersions", XLuaGetVersions);
	lua_register(L, "XPLMGetVirtualKeyDescription", XLuaGetVirtualKeyDescription);
	lua_register(L, "XPLMGetWeatherAtLocation", XLuaGetWeatherAtLocation);
	lua_register(L, "XPLMGetWindowGeometry", XLuaGetWindowGeometry);
	lua_register(L, "XPLMGetWindowGeometryOS", XLuaGetWindowGeometryOS);
	lua_register(L, "XPLMGetWindowGeometryVR", XLuaGetWindowGeometryVR);
	lua_register(L, "XPLMGetWindowIsVisible", XLuaGetWindowIsVisible);
	lua_register(L, "XPLMGetWindowRefCon", XLuaGetWindowRefCon);
	lua_register(L, "XPLMHasAvionicsKeyboardFocus", XLuaHasAvionicsKeyboardFocus);
	lua_register(L, "XPLMHasFeature", XLuaHasFeature);
	lua_register(L, "XPLMHasKeyboardFocus", XLuaHasKeyboardFocus);
	lua_register(L, "XPLMInitFlight", XLuaInitFlight);
	lua_register(L, "XPLMInstanceSetAutoShift", XLuaInstanceSetAutoShift);
	lua_register(L, "XPLMInstanceSetPosition", XLuaInstanceSetPosition);
	lua_register(L, "XPLMInstanceSetPositionDouble", XLuaInstanceSetPositionDouble);
	lua_register(L, "XPLMIsAvionicsBound", XLuaIsAvionicsBound);
	lua_register(L, "XPLMIsAvionicsMappedToVR", XLuaIsAvionicsMappedToVR);
	lua_register(L, "XPLMIsAvionicsPoppedOut", XLuaIsAvionicsPoppedOut);
	lua_register(L, "XPLMIsAvionicsPopupVisible", XLuaIsAvionicsPopupVisible);
	lua_register(L, "XPLMIsCameraBeingControlled", XLuaIsCameraBeingControlled);
	lua_register(L, "XPLMIsCursorOverAvionics", XLuaIsCursorOverAvionics);
	lua_register(L, "XPLMIsDataRefGood", XLuaIsDataRefGood);
	lua_register(L, "XPLMIsFeatureEnabled", XLuaIsFeatureEnabled);
	lua_register(L, "XPLMIsPluginEnabled", XLuaIsPluginEnabled);
	lua_register(L, "XPLMIsWindowInFront", XLuaIsWindowInFront);
	lua_register(L, "XPLMLineLoop", XLuaLineLoop);
	lua_register(L, "XPLMLineLoopStipple", XLuaLineLoopStipple);
	lua_register(L, "XPLMLineLoopWithWidth", XLuaLineLoopWithWidth);
	lua_register(L, "XPLMLineLoopc", XLuaLineLoopc);
	lua_register(L, "XPLMLineLoopcWithWidth", XLuaLineLoopcWithWidth);
	lua_register(L, "XPLMLineStrip", XLuaLineStrip);
	lua_register(L, "XPLMLineStripStipple", XLuaLineStripStipple);
	lua_register(L, "XPLMLineStripWithWidth", XLuaLineStripWithWidth);
	lua_register(L, "XPLMLineStripc", XLuaLineStripc);
	lua_register(L, "XPLMLineStripcWithWidth", XLuaLineStripcWithWidth);
	lua_register(L, "XPLMLines", XLuaLines);
	lua_register(L, "XPLMLinesStipple", XLuaLinesStipple);
	lua_register(L, "XPLMLinesWithWidth", XLuaLinesWithWidth);
	lua_register(L, "XPLMLinesc", XLuaLinesc);
	lua_register(L, "XPLMLinescWithWidth", XLuaLinescWithWidth);
	lua_register(L, "XPLMLoadDataFile", XLuaLoadDataFile);
	lua_register(L, "XPLMLoadFMSFlightPlan", XLuaLoadFMSFlightPlan);
	lua_register(L, "XPLMLoadObject", XLuaLoadObject);
	lua_register(L, "XPLMLoadObjectAsync", XLuaLoadObjectAsync);
	lua_register(L, "XPLMLocalToWorld", XLuaLocalToWorld);
	lua_register(L, "XPLMLookupObjects", XLuaLookupObjects);
	lua_register(L, "XPLMMakeColor", XLuaMakeColor);
	lua_register(L, "XPLMMapCustomData_t", MakeXPLMMapCustomData_t);
	lua_register(L, "XPLMMapDisplayDrawIn", XLuaMapDisplayDrawIn);
	lua_register(L, "XPLMMapExists", XLuaMapExists);
	lua_register(L, "XPLMMapGetNorthHeading", XLuaMapGetNorthHeading);
	lua_register(L, "XPLMMapProject", XLuaMapProject);
	lua_register(L, "XPLMMapScaleMeter", XLuaMapScaleMeter);
	lua_register(L, "XPLMMapUnproject", XLuaMapUnproject);
	lua_register(L, "XPLMMeasureString", XLuaMeasureString);
	lua_register(L, "XPLMPlaceUserAtAirport", XLuaPlaceUserAtAirport);
	lua_register(L, "XPLMPlaceUserAtLocation", XLuaPlaceUserAtLocation);
	lua_register(L, "XPLMPolygon", XLuaPolygon);
	lua_register(L, "XPLMPolygonWithWidth", XLuaPolygonWithWidth);
	lua_register(L, "XPLMPolygonc", XLuaPolygonc);
	lua_register(L, "XPLMPolygoncWithWidth", XLuaPolygoncWithWidth);
	lua_register(L, "XPLMPopOutAvionics", XLuaPopOutAvionics);
	lua_register(L, "XPLMProbeInfo_t", MakeXPLMProbeInfo_t);
	lua_register(L, "XPLMProbeTerrainXYZ", XLuaProbeTerrainXYZ);
	lua_register(L, "XPLMQuadstrip", XLuaQuadstrip);
	lua_register(L, "XPLMQuadstripWithWidth", XLuaQuadstripWithWidth);
	lua_register(L, "XPLMQuadstripc", XLuaQuadstripc);
	lua_register(L, "XPLMQuadstripcWithWidth", XLuaQuadstripcWithWidth);
	lua_register(L, "XPLMReadCameraPosition", XLuaReadCameraPosition);
	lua_register(L, "XPLMRegisterAvionicsCallbacksEx", XLuaRegisterAvionicsCallbacksEx);
	lua_register(L, "XPLMRegisterCommandHandler", XLuaRegisterCommandHandler);
	lua_register(L, "XPLMRegisterDataAccessor", XLuaRegisterDataAccessor);
	lua_register(L, "XPLMRegisterMapCreationHook", XLuaRegisterMapCreationHook);
	lua_register(L, "XPLMReleasePlanes", XLuaReleasePlanes);
	lua_register(L, "XPLMReloadPlugins", XLuaReloadPlugins);
	lua_register(L, "XPLMReloadScenery", XLuaReloadScenery);
	lua_register(L, "XPLMReloadThisPlugin", XLuaReloadThisPlugin);
	lua_register(L, "XPLMRemoveMenuItem", XLuaRemoveMenuItem);
	lua_register(L, "XPLMSVTCustomData_t", MakeXPLMSVTCustomData_t);
	lua_register(L, "XPLMSVTDisplayDrawIn", XLuaSVTDisplayDrawIn);
	lua_register(L, "XPLMSaveDataFile", XLuaSaveDataFile);
	lua_register(L, "XPLMScheduleFlightLoop", XLuaScheduleFlightLoop);
	lua_register(L, "XPLMScissorPop", XLuaScissorPop);
	lua_register(L, "XPLMScissorPush", XLuaScissorPush);
	lua_register(L, "XPLMScissorSet", XLuaScissorSet);
	lua_register(L, "XPLMScissorShrink", XLuaScissorShrink);
	lua_register(L, "XPLMSendMessageToPlugin", XLuaSendMessageToPlugin);
	lua_register(L, "XPLMSetActiveAircraftCount", XLuaSetActiveAircraftCount);
	lua_register(L, "XPLMSetAircraftModel", XLuaSetAircraftModel);
	lua_register(L, "XPLMSetAvionicsBrightnessRheo", XLuaSetAvionicsBrightnessRheo);
	lua_register(L, "XPLMSetAvionicsGeometry", XLuaSetAvionicsGeometry);
	lua_register(L, "XPLMSetAvionicsGeometryOS", XLuaSetAvionicsGeometryOS);
	lua_register(L, "XPLMSetAvionicsMappedToVR", XLuaSetAvionicsMappedToVR);
	lua_register(L, "XPLMSetAvionicsPopupVisible", XLuaSetAvionicsPopupVisible);
	lua_register(L, "XPLMSetDatab", XLuaSetDatab);
	lua_register(L, "XPLMSetDatad", XLuaSetDatad);
	lua_register(L, "XPLMSetDataf", XLuaSetDataf);
	lua_register(L, "XPLMSetDatai", XLuaSetDatai);
	lua_register(L, "XPLMSetDatavf", XLuaSetDatavf);
	lua_register(L, "XPLMSetDatavi", XLuaSetDatavi);
	lua_register(L, "XPLMSetDestinationFMSEntry", XLuaSetDestinationFMSEntry);
	lua_register(L, "XPLMSetDestinationFMSFlightPlanEntry", XLuaSetDestinationFMSFlightPlanEntry);
	lua_register(L, "XPLMSetDirectToFMSFlightPlanEntry", XLuaSetDirectToFMSFlightPlanEntry);
	lua_register(L, "XPLMSetDisplayedFMSEntry", XLuaSetDisplayedFMSEntry);
	lua_register(L, "XPLMSetDisplayedFMSFlightPlanEntry", XLuaSetDisplayedFMSFlightPlanEntry);
	lua_register(L, "XPLMSetFMSEntryInfo", XLuaSetFMSEntryInfo);
	lua_register(L, "XPLMSetFMSEntryLatLon", XLuaSetFMSEntryLatLon);
	lua_register(L, "XPLMSetFMSFlightPlanEntryInfo", XLuaSetFMSFlightPlanEntryInfo);
	lua_register(L, "XPLMSetFMSFlightPlanEntryLatLon", XLuaSetFMSFlightPlanEntryLatLon);
	lua_register(L, "XPLMSetFMSFlightPlanEntryLatLonWithId", XLuaSetFMSFlightPlanEntryLatLonWithId);
	lua_register(L, "XPLMSetMenuItemName", XLuaSetMenuItemName);
	lua_register(L, "XPLMSetUsersAircraft", XLuaSetUsersAircraft);
	lua_register(L, "XPLMSetWeatherAtAirport", XLuaSetWeatherAtAirport);
	lua_register(L, "XPLMSetWeatherAtLocation", XLuaSetWeatherAtLocation);
	lua_register(L, "XPLMSetWindowGeometry", XLuaSetWindowGeometry);
	lua_register(L, "XPLMSetWindowGeometryOS", XLuaSetWindowGeometryOS);
	lua_register(L, "XPLMSetWindowGeometryVR", XLuaSetWindowGeometryVR);
	lua_register(L, "XPLMSetWindowGravity", XLuaSetWindowGravity);
	lua_register(L, "XPLMSetWindowIsVisible", XLuaSetWindowIsVisible);
	lua_register(L, "XPLMSetWindowPositioningMode", XLuaSetWindowPositioningMode);
	lua_register(L, "XPLMSetWindowRefCon", XLuaSetWindowRefCon);
	lua_register(L, "XPLMSetWindowResizingLimits", XLuaSetWindowResizingLimits);
	lua_register(L, "XPLMSetWindowTitle", XLuaSetWindowTitle);
	lua_register(L, "XPLMSpeakString", XLuaSpeakString);
	lua_register(L, "XPLMTakeAvionicsKeyboardFocus", XLuaTakeAvionicsKeyboardFocus);
	lua_register(L, "XPLMTakeKeyboardFocus", XLuaTakeKeyboardFocus);
	lua_register(L, "XPLMTextureAtlasAddImage", XLuaTextureAtlasAddImage);
	lua_register(L, "XPLMTextureAtlasAddImageFile", XLuaTextureAtlasAddImageFile);
	lua_register(L, "XPLMTextureAtlasAddImageFileSet", XLuaTextureAtlasAddImageFileSet);
	lua_register(L, "XPLMTextureAtlasBake", XLuaTextureAtlasBake);
	lua_register(L, "XPLMTextureAtlasDrawAt", XLuaTextureAtlasDrawAt);
	lua_register(L, "XPLMTextureAtlasDrawIn", XLuaTextureAtlasDrawIn);
	lua_register(L, "XPLMTextureAtlasDrawMesh", XLuaTextureAtlasDrawMesh);
	lua_register(L, "XPLMTextureAtlasDrawScaled", XLuaTextureAtlasDrawScaled);
	lua_register(L, "XPLMTextureAtlasDrawStretched", XLuaTextureAtlasDrawStretched);
	lua_register(L, "XPLMTextureAtlasGetImageHeight", XLuaTextureAtlasGetImageHeight);
	lua_register(L, "XPLMTextureAtlasGetImageUVMap", XLuaTextureAtlasGetImageUVMap);
	lua_register(L, "XPLMTextureAtlasGetImageWidth", XLuaTextureAtlasGetImageWidth);
	lua_register(L, "XPLMTextureSourceDrawIn", XLuaTextureSourceDrawIn);
	lua_register(L, "XPLMTextureSourceDrawMesh", XLuaTextureSourceDrawMesh);
	lua_register(L, "XPLMTextureVertex_t", MakeXPLMTextureVertex_t);
	lua_register(L, "XPLMTouchZoneSpec_t", MakeXPLMTouchZoneSpec_t);
	lua_register(L, "XPLMTransformPop", XLuaTransformPop);
	lua_register(L, "XPLMTransformPush", XLuaTransformPush);
	lua_register(L, "XPLMTransformRotate", XLuaTransformRotate);
	lua_register(L, "XPLMTransformScale", XLuaTransformScale);
	lua_register(L, "XPLMTransformTranslate", XLuaTransformTranslate);
	lua_register(L, "XPLMUnloadObject", XLuaUnloadObject);
	lua_register(L, "XPLMUnregisterAvionicsCallbacks", XLuaUnregisterAvionicsCallbacks);
	lua_register(L, "XPLMUnregisterCommandHandler", XLuaUnregisterCommandHandler);
	lua_register(L, "XPLMUnregisterDataAccessor", XLuaUnregisterDataAccessor);
	lua_register(L, "XPLMUpdateFlight", XLuaUpdateFlight);
	lua_register(L, "XPLMUseStencilMask", XLuaUseStencilMask);
	lua_register(L, "XPLMVertexColor_t", MakeXPLMVertexColor_t);
	lua_register(L, "XPLMVertex_t", MakeXPLMVertex_t);
	lua_register(L, "XPLMWeatherInfoClouds_t", MakeXPLMWeatherInfoClouds_t);
	lua_register(L, "XPLMWeatherInfoWinds_t", MakeXPLMWeatherInfoWinds_t);
	lua_register(L, "XPLMWeatherInfo_t", MakeXPLMWeatherInfo_t);
	lua_register(L, "XPLMWindowAddBrowserFunction", XLuaWindowAddBrowserFunction);
	lua_register(L, "XPLMWindowInjectScript", XLuaWindowInjectScript);
	lua_register(L, "XPLMWindowIsInVR", XLuaWindowIsInVR);
	lua_register(L, "XPLMWindowIsPoppedOut", XLuaWindowIsPoppedOut);
	lua_register(L, "XPLMWindowRefresh", XLuaWindowRefresh);
	lua_register(L, "XPLMWindowSetTouchEventHandler", XLuaWindowSetTouchEventHandler);
	lua_register(L, "XPLMWindowSetURL", XLuaWindowSetURL);
	lua_register(L, "XPLMWorldToLocal", XLuaWorldToLocal);

	// Userdata types
	RegType_XPLMAvionicsID(L);
	RegType_XPLMCommandRef(L);
	RegType_XPLMDataRef(L);
	RegType_XPLMFlightLoopID(L);
	RegType_XPLMFontHandle(L);
	RegType_XPLMInstanceRef(L);
	RegType_XPLMMapDisplayRef(L);
	RegType_XPLMMapLayerID(L);
	RegType_XPLMMapProjectionID(L);
	RegType_XPLMMenuID(L);
	RegType_XPLMNavRef(L);
	RegType_XPLMObjectRef(L);
	RegType_XPLMPluginID(L);
	RegType_XPLMProbeRef(L);
	RegType_XPLMRetainedDrawing_t(L);
	RegType_XPLMSVTDisplayRef(L);
	RegType_XPLMTextureAtlasRef(L);
	RegType_XPLMWindowID(L);

	// Enums
	RegEnum_XPLMCameraControlDuration(L);
	RegEnum_XPLMCharSet_t(L);
	RegEnum_XPLMCommandPhase(L);
	RegEnum_XPLMCursorStatus(L);
	RegEnum_XPLMDataFileType(L);
	RegEnum_XPLMDataTypeID(L);
	RegEnum_XPLMDeviceID(L);
	RegEnum_XPLMFlightLoopPhaseType(L);
	RegEnum_XPLMFontID(L);
	RegEnum_XPLMHostApplicationID(L);
	RegEnum_XPLMInitResult(L);
	RegEnum_XPLMJustification_t(L);
	RegEnum_XPLMKeyFlags(L);
	RegEnum_XPLMLanguageCode(L);
	RegEnum_XPLMMapLayerType(L);
	RegEnum_XPLMMapLayers(L);
	RegEnum_XPLMMapOrientation(L);
	RegEnum_XPLMMapStyle(L);
	RegEnum_XPLMMenuCheck(L);
	RegEnum_XPLMMouseStatus(L);
	RegEnum_XPLMNavFlightPlan(L);
	RegEnum_XPLMNavType(L);
	RegEnum_XPLMProbeResult(L);
	RegEnum_XPLMProbeType(L);
	RegEnum_XPLMSVTFeatures(L);
	RegEnum_XPLMTextureSource(L);
	RegEnum_XPLMTouchZone(L);
	RegEnum_XPLMWindowContentType(L);
	RegEnum_XPLMWindowDecoration(L);
	RegEnum_XPLMWindowLayer(L);
	RegEnum_XPLMWindowPositioningMode(L);

	// Defines
	RegDefines_XPLMDefs(L);
	RegDefines_XPLMMap(L);
	RegDefines_XPLMNavigation(L);
	RegDefines_XPLMPlanes(L);
	RegDefines_XPLMPlugin(L);
	RegDefines_XPLMWeather(L);

	// Event types
	xlua_register_event(XPLM_MSG_DATAREFS_ADDED, "*u");
	xlua_register_event(XPLM_MSG_FMOD_BANK_LOADED, "extdata<XPLMBankID>");
	xlua_register_event(XPLM_MSG_FMOD_BANK_UNLOADING, "extdata<XPLMBankID>");
	xlua_register_event(XPLM_MSG_LIVERY_LOADED, "i");
	xlua_register_event(XPLM_MSG_PLANE_LOADED, "i");
	xlua_register_event(XPLM_MSG_PLANE_UNLOADED, "i");
}
