#ifndef _Glua_XPLMPlanes_h_
#define _Glua_XPLMPlanes_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMPlanes
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMPlanes.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


int XLuaInitFlight(lua_State* L)
{
	char const* inJsonData = xlua_checkstring(L, 1);

	XPLMInitResult res = XPLMInitFlight(inJsonData);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaUpdateFlight(lua_State* L)
{
	char const* inJsonData = xlua_checkstring(L, 1);

	XPLMInitResult res = XPLMUpdateFlight(inJsonData);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetUsersAircraft(lua_State* L)
{
	const char * inAircraftPath = xlua_checkstring(L, 1);

	XPLMSetUsersAircraft(inAircraftPath);

	return 0;
}

int XLuaPlaceUserAtAirport(lua_State* L)
{
	const char * inAirportCode = xlua_checkstring(L, 1);

	XPLMPlaceUserAtAirport(inAirportCode);

	return 0;
}

int XLuaPlaceUserAtLocation(lua_State* L)
{
	double latitudeDegrees = xlua_checknumber(L, 1);
	double longitudeDegrees = xlua_checknumber(L, 2);
	float elevationMetersMSL = xlua_checknumber(L, 3);
	float headingDegreesTrue = xlua_checknumber(L, 4);
	float speedMetersPerSecond = xlua_checknumber(L, 5);

	XPLMPlaceUserAtLocation(latitudeDegrees, longitudeDegrees, elevationMetersMSL, headingDegreesTrue, speedMetersPerSecond);

	return 0;
}

int XLuaCountAircraft(lua_State* L)
{
	int outTotalAircraft = {};
	int outActiveAircraft = {};
	XPLMPluginID outController = {};
	XPLMCountAircraft(&outTotalAircraft, &outActiveAircraft, &outController);

	lua_createtable(L, 0, 3);

	lua_pushstring(L, "outTotalAircraft");
	lua_pushinteger(L, outTotalAircraft);
	lua_settable(L, -3);

	lua_pushstring(L, "outActiveAircraft");
	lua_pushinteger(L, outActiveAircraft);
	lua_settable(L, -3);

	lua_pushstring(L, "outController");
	xlua_pushuserdata<XPLMPluginID>(L, outController);
	lua_settable(L, -3);

	return 1;
}

int XLuaGetNthAircraftModel(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	char outFileName[256] = {};
	char outPath[512] = {};

	XPLMGetNthAircraftModel(inIndex, outFileName, outPath);

	lua_createtable(L, 0, 2);

	lua_pushstring(L, "outFileName");
	lua_pushstring(L, outFileName);
	lua_settable(L, -3);

	lua_pushstring(L, "outPath");
	lua_pushstring(L, outPath);
	lua_settable(L, -3);

	return 1;
}

static void cb_XPLMPlanesAvailable_f(void* inRefcon)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMPlanesAvailable_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r", inRefcon_cb->get_capture()))
		{
		}
	}
}

int XLuaAcquirePlanes(lua_State* L)
{
	if (!lua_isnil(L, 1))
	{
		luaL_checktype(L, 1, LUA_TTABLE);
	}


	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 3);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 2, true, "XPLMPlanesAvailable_f");

	int inAircraft_len = lua_objlen(L, 1);
	char const** inAircraft = new char const*[inAircraft_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < inAircraft_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		inAircraft[i] = xlua_checkstring(L, -1);
		lua_pop(L, 1);
	}
	
	int res = XPLMAcquirePlanes((inAircraft ? &*inAircraft : nullptr), (cb_capture_0 ? cb_XPLMPlanesAvailable_f : nullptr), cb_capture_0.get());
	lua_pushboolean(L, res);

	if (inAircraft != nullptr)
	{
		delete[] inAircraft;
	}

	return 1;
}

int XLuaReleasePlanes(lua_State* L)
{
	XPLMReleasePlanes();

	return 0;
}

int XLuaSetActiveAircraftCount(lua_State* L)
{
	int inCount = xlua_checkinteger(L, 1);

	XPLMSetActiveAircraftCount(inCount);

	return 0;
}

int XLuaSetAircraftModel(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	const char * inAircraftPath = xlua_checkstring(L, 2);

	XPLMSetAircraftModel(inIndex, inAircraftPath);

	return 0;
}

int XLuaDisableAIForPlane(lua_State* L)
{
	int inPlaneIndex = xlua_checkinteger(L, 1);

	XPLMDisableAIForPlane(inPlaneIndex);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
