#ifndef _Glua_XPLMPlugin_h_
#define _Glua_XPLMPlugin_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMPlugin
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"
#include "XPLMSound.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMPlugin.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


int XLuaGetMyID(lua_State* L)
{
	XPLMPluginID res = XPLMGetMyID();
	Make_XPLMPluginID(L, res);

	return 1;
}

int XLuaCountPlugins(lua_State* L)
{
	int res = XPLMCountPlugins();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetNthPlugin(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);

	XPLMPluginID res = XPLMGetNthPlugin(inIndex);
	Make_XPLMPluginID(L, res);

	return 1;
}

int XLuaFindPluginByPath(lua_State* L)
{
	const char * inPath = xlua_checkstring(L, 1);

	XPLMPluginID res = XPLMFindPluginByPath(inPath);
	Make_XPLMPluginID(L, res);

	return 1;
}

int XLuaFindPluginBySignature(lua_State* L)
{
	const char * inSignature = xlua_checkstring(L, 1);

	XPLMPluginID res = XPLMFindPluginBySignature(inSignature);
	Make_XPLMPluginID(L, res);

	return 1;
}

int XLuaGetPluginInfo(lua_State* L)
{
	XPLMPluginID inPlugin = {};
	if (lua_isuserdata(L, 1))
	{
		inPlugin = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	}
	char outName[256] = {};
	char outFilePath[256] = {};
	char outSignature[256] = {};
	char outDescription[256] = {};

	XPLMGetPluginInfo(inPlugin, outName, outFilePath, outSignature, outDescription);

	lua_createtable(L, 0, 4);

	lua_pushstring(L, "outName");
	lua_pushstring(L, outName);
	lua_settable(L, -3);

	lua_pushstring(L, "outFilePath");
	lua_pushstring(L, outFilePath);
	lua_settable(L, -3);

	lua_pushstring(L, "outSignature");
	lua_pushstring(L, outSignature);
	lua_settable(L, -3);

	lua_pushstring(L, "outDescription");
	lua_pushstring(L, outDescription);
	lua_settable(L, -3);

	return 1;
}

int XLuaIsPluginEnabled(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	}

	int res = XPLMIsPluginEnabled(inPluginID);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaEnablePlugin(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	}

	int res = XPLMEnablePlugin(inPluginID);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaDisablePlugin(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	}

	XPLMDisablePlugin(inPluginID);

	return 0;
}

int XLuaReloadPlugins(lua_State* L)
{
	XPLMReloadPlugins();

	return 0;
}

int XLuaReloadThisPlugin(lua_State* L)
{
	bool forReplacement = xlua_checkboolean(L, 1);

	XPLMReloadThisPlugin(forReplacement);

	return 0;
}

int XLuaSendMessageToPlugin(lua_State* L)
{
	XPLMPluginID inPlugin = {};
	if (lua_isuserdata(L, 1))
	{
		inPlugin = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	}
	int inMessage = xlua_checkinteger(L, 2);
	void * inParam = {};
	if (lua_isuserdata(L, 3))
	{
		inParam = xlua_checkuserdata<void*>(L, 3, "Expected void*");
	}

	XPLMSendMessageToPlugin(inPlugin, inMessage, inParam);

	return 0;
}

static void cb_XPLMFeatureEnumerator_f(const char * inFeature, void* inRef)
{
	notify_cb_t const* inRef_cb = static_cast<notify_cb_t*>(inRef);

	lua_State* L = setup_lua_callback(inRef_cb, "XPLMFeatureEnumerator_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "sr", inFeature, inRef_cb->get_capture()))
		{
		}
	}
}

int XLuaHasFeature(lua_State* L)
{
	const char * inFeature = xlua_checkstring(L, 1);

	int res = XPLMHasFeature(inFeature);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaIsFeatureEnabled(lua_State* L)
{
	const char * inFeature = xlua_checkstring(L, 1);

	int res = XPLMIsFeatureEnabled(inFeature);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaEnableFeature(lua_State* L)
{
	const char * inFeature = xlua_checkstring(L, 1);
	bool inEnable = xlua_checkboolean(L, 2);

	XPLMEnableFeature(inFeature, inEnable);

	return 0;
}

int XLuaEnumerateFeatures(lua_State* L)
{

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 2);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 1, true, "XPLMFeatureEnumerator_f");

	XPLMEnumerateFeatures((cb_capture_0 ? cb_XPLMFeatureEnumerator_f : nullptr), cb_capture_0.get());

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
