#ifndef _Glua_XPLMNavigation_h_
#define _Glua_XPLMNavigation_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMNavigation
 ***************************************************************************/

#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMNavigation.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>


int XLuaGetFirstNavAid(lua_State* L)
{
	XPLMNavRef res = XPLMGetFirstNavAid();
	xlua_pushuserdata<XPLMNavRef>(L, res);

	return 1;
}

int XLuaGetNextNavAid(lua_State* L)
{
	XPLMNavRef inNavAidRef = {};
	if (lua_isuserdata(L, 1))
	{
		inNavAidRef = xlua_checkuserdata<XPLMNavRef>(L, 1, "Expected userdata<XPLMNavRef>");
	}

	XPLMNavRef res = XPLMGetNextNavAid(inNavAidRef);
	xlua_pushuserdata<XPLMNavRef>(L, res);

	return 1;
}

int XLuaFindFirstNavAidOfType(lua_State* L)
{
	XPLMNavType inType = luaL_checkinteger(L, 1);

	XPLMNavRef res = XPLMFindFirstNavAidOfType(inType);
	xlua_pushuserdata<XPLMNavRef>(L, res);

	return 1;
}

int XLuaFindLastNavAidOfType(lua_State* L)
{
	XPLMNavType inType = luaL_checkinteger(L, 1);

	XPLMNavRef res = XPLMFindLastNavAidOfType(inType);
	xlua_pushuserdata<XPLMNavRef>(L, res);

	return 1;
}

int XLuaGetNavAidInfo(lua_State* L)
{
	XPLMNavRef inRef = {};
	if (lua_isuserdata(L, 1))
	{
		inRef = xlua_checkuserdata<XPLMNavRef>(L, 1, "Expected userdata<XPLMNavRef>");
	}
	XPLMNavType outType;
	float outLatitude;
	float outLongitude;
	float outHeight;
	int outFrequency;
	float outHeading;
	char outID[32];
	char outName[256];
	char outReg[1];

	XPLMGetNavAidInfo(inRef, &outType, &outLatitude, &outLongitude, &outHeight, &outFrequency, &outHeading, outID, outName, outReg);

	lua_createtable(L, 0, 9); // 0 array slots and 9 key-value pairs

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outLatitude");
	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");
	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outHeight");
	lua_pushnumber(L, outHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "outFrequency");
	lua_pushinteger(L, outFrequency);
	lua_settable(L, -3);

	lua_pushstring(L, "outHeading");
	lua_pushnumber(L, outHeading);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outName");
	lua_pushstring(L, outName);
	lua_settable(L, -3);

	lua_pushstring(L, "outReg");
	lua_pushstring(L, outReg);
	lua_settable(L, -3);

	return 1;
}

int XLuaCountFMSEntries(lua_State* L)
{
	int res = XPLMCountFMSEntries();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDisplayedFMSEntry(lua_State* L)
{
	int res = XPLMGetDisplayedFMSEntry();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDestinationFMSEntry(lua_State* L)
{
	int res = XPLMGetDestinationFMSEntry();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDisplayedFMSEntry(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);

	XPLMSetDisplayedFMSEntry(inIndex);

	return 0;
}

int XLuaSetDestinationFMSEntry(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);

	XPLMSetDestinationFMSEntry(inIndex);

	return 0;
}

int XLuaGetFMSEntryInfo(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);
	XPLMNavType outType;
	char outID[256];
	XPLMNavRef outRef;
	int outAltitude;
	float outLat;
	float outLon;

	XPLMGetFMSEntryInfo(inIndex, &outType, outID, &outRef, &outAltitude, &outLat, &outLon);

	lua_createtable(L, 0, 6); // 0 array slots and 6 key-value pairs

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outRef");
	xlua_pushuserdata<XPLMNavRef>(L, outRef);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushinteger(L, outAltitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLat");
	lua_pushnumber(L, outLat);
	lua_settable(L, -3);

	lua_pushstring(L, "outLon");
	lua_pushnumber(L, outLon);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetFMSEntryInfo(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);
	XPLMNavRef inRef = {};
	if (lua_isuserdata(L, 2))
	{
		inRef = xlua_checkuserdata<XPLMNavRef>(L, 2, "Expected userdata<XPLMNavRef>");
	}
	int inAltitude = luaL_checkinteger(L, 3);

	XPLMSetFMSEntryInfo(inIndex, inRef, inAltitude);

	return 0;
}

int XLuaSetFMSEntryLatLon(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);
	float inLat = luaL_checknumber(L, 2);
	float inLon = luaL_checknumber(L, 3);
	int inAltitude = luaL_checkinteger(L, 4);

	XPLMSetFMSEntryLatLon(inIndex, inLat, inLon, inAltitude);

	return 0;
}

int XLuaClearFMSEntry(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);

	XPLMClearFMSEntry(inIndex);

	return 0;
}

int XLuaCountFMSFlightPlanEntries(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);

	int res = XPLMCountFMSFlightPlanEntries(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDisplayedFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);

	int res = XPLMGetDisplayedFMSFlightPlanEntry(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDestinationFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);

	int res = XPLMGetDestinationFMSFlightPlanEntry(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDisplayedFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);

	XPLMSetDisplayedFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaSetDestinationFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);

	XPLMSetDestinationFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaSetDirectToFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);

	XPLMSetDirectToFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaGetFMSFlightPlanEntryInfo(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);
	XPLMNavType outType;
	char outID[256];
	XPLMNavRef outRef;
	int outAltitude;
	float outLat;
	float outLon;

	XPLMGetFMSFlightPlanEntryInfo(inFlightPlan, inIndex, &outType, outID, &outRef, &outAltitude, &outLat, &outLon);

	lua_createtable(L, 0, 6); // 0 array slots and 6 key-value pairs

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outRef");
	xlua_pushuserdata<XPLMNavRef>(L, outRef);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushinteger(L, outAltitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLat");
	lua_pushnumber(L, outLat);
	lua_settable(L, -3);

	lua_pushstring(L, "outLon");
	lua_pushnumber(L, outLon);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetFMSFlightPlanEntryInfo(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);
	XPLMNavRef inRef = {};
	if (lua_isuserdata(L, 3))
	{
		inRef = xlua_checkuserdata<XPLMNavRef>(L, 3, "Expected userdata<XPLMNavRef>");
	}
	int inAltitude = luaL_checkinteger(L, 4);

	XPLMSetFMSFlightPlanEntryInfo(inFlightPlan, inIndex, inRef, inAltitude);

	return 0;
}

int XLuaSetFMSFlightPlanEntryLatLon(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);
	float inLat = luaL_checknumber(L, 3);
	float inLon = luaL_checknumber(L, 4);
	int inAltitude = luaL_checkinteger(L, 5);

	XPLMSetFMSFlightPlanEntryLatLon(inFlightPlan, inIndex, inLat, inLon, inAltitude);

	return 0;
}

int XLuaSetFMSFlightPlanEntryLatLonWithId(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);
	float inLat = luaL_checknumber(L, 3);
	float inLon = luaL_checknumber(L, 4);
	int inAltitude = luaL_checkinteger(L, 5);
	const char* inId = luaL_checkstring(L, 6);
	unsigned int inIdLength = luaL_checkinteger(L, 7);

	XPLMSetFMSFlightPlanEntryLatLonWithId(inFlightPlan, inIndex, inLat, inLon, inAltitude, inId, inIdLength);

	return 0;
}

int XLuaClearFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = luaL_checkinteger(L, 1);
	int inIndex = luaL_checkinteger(L, 2);

	XPLMClearFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaLoadFMSFlightPlan(lua_State* L)
{
	int inDevice = luaL_checkinteger(L, 1);
	const char * inBuffer = luaL_checkstring(L, 2);
	unsigned int inBufferLen = luaL_checkinteger(L, 3);

	XPLMLoadFMSFlightPlan(inDevice, inBuffer, inBufferLen);

	return 0;
}

int XLuaGetGPSDestinationType(lua_State* L)
{
	XPLMNavType res = XPLMGetGPSDestinationType();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetGPSDestination(lua_State* L)
{
	XPLMNavRef res = XPLMGetGPSDestination();
	xlua_pushuserdata<XPLMNavRef>(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
