#ifndef _Glua_XPLMPanelGraphics_h_
#define _Glua_XPLMPanelGraphics_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMPanelGraphics
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"
#include "XPLMUtilities.h"
#include "XPLMDisplay.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMPanelGraphics.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMCreateAvionics_t XPLMCreateAvionics_t_from_table(lua_State* L, int stackpos);
void XPLMCreateAvionics_t_to_table(lua_State* L, XPLMCreateAvionics_t const& src);
XPLMCreateMap_t XPLMCreateMap_t_from_table(lua_State* L, int stackpos);
void XPLMCreateMap_t_to_table(lua_State* L, XPLMCreateMap_t const& src);
XPLMCreateSVT_t XPLMCreateSVT_t_from_table(lua_State* L, int stackpos);
void XPLMCreateSVT_t_to_table(lua_State* L, XPLMCreateSVT_t const& src);
XPLMCreateWindow_t XPLMCreateWindow_t_from_table(lua_State* L, int stackpos);
void XPLMCreateWindow_t_to_table(lua_State* L, XPLMCreateWindow_t const& src);
XPLMCustomizeAvionics_t XPLMCustomizeAvionics_t_from_table(lua_State* L, int stackpos);
void XPLMCustomizeAvionics_t_to_table(lua_State* L, XPLMCustomizeAvionics_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);
XPLMFontMetrics_t XPLMFontMetrics_t_from_table(lua_State* L, int stackpos);
void XPLMFontMetrics_t_to_table(lua_State* L, XPLMFontMetrics_t const& src);
XPLMMapCustomData_t XPLMMapCustomData_t_from_table(lua_State* L, int stackpos);
void XPLMMapCustomData_t_to_table(lua_State* L, XPLMMapCustomData_t const& src);
XPLMMapDrawInfo_t XPLMMapDrawInfo_t_from_table(lua_State* L, int stackpos);
void XPLMMapDrawInfo_t_to_table(lua_State* L, XPLMMapDrawInfo_t const& src);
XPLMSVTCustomData_t XPLMSVTCustomData_t_from_table(lua_State* L, int stackpos);
void XPLMSVTCustomData_t_to_table(lua_State* L, XPLMSVTCustomData_t const& src);
XPLMTextureVertex_t XPLMTextureVertex_t_from_table(lua_State* L, int stackpos);
void XPLMTextureVertex_t_to_table(lua_State* L, XPLMTextureVertex_t const& src);
XPLMTouchZoneSpec_t XPLMTouchZoneSpec_t_from_table(lua_State* L, int stackpos);
void XPLMTouchZoneSpec_t_to_table(lua_State* L, XPLMTouchZoneSpec_t const& src);
XPLMVertexColor_t XPLMVertexColor_t_from_table(lua_State* L, int stackpos);
void XPLMVertexColor_t_to_table(lua_State* L, XPLMVertexColor_t const& src);
XPLMVertex_t XPLMVertex_t_from_table(lua_State* L, int stackpos);
void XPLMVertex_t_to_table(lua_State* L, XPLMVertex_t const& src);

//
// Typedefs
//
XPLMAvionicsID* Make_XPLMAvionicsID(lua_State* L, XPLMAvionicsID const& init);
XPLMCommandRef* Make_XPLMCommandRef(lua_State* L, XPLMCommandRef const& init);
XPLMFontHandle* Make_XPLMFontHandle(lua_State* L, XPLMFontHandle const& init);
XPLMMapDisplayRef* Make_XPLMMapDisplayRef(lua_State* L, XPLMMapDisplayRef const& init);
XPLMRetainedDrawing_t* Make_XPLMRetainedDrawing_t(lua_State* L, XPLMRetainedDrawing_t const& init);
XPLMSVTDisplayRef* Make_XPLMSVTDisplayRef(lua_State* L, XPLMSVTDisplayRef const& init);
XPLMTextureAtlasRef* Make_XPLMTextureAtlasRef(lua_State* L, XPLMTextureAtlasRef const& init);
XPLMWindowID* Make_XPLMWindowID(lua_State* L, XPLMWindowID const& init);

/*
 * XPLMVertex_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMVertex_t XPLMVertex_t_from_table(lua_State* L, int stackpos)
{
	XPLMVertex_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMVertex_t_to_table(lua_State* L, XPLMVertex_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);
}

int MakeXPLMVertex_t(lua_State* L)
{
	XPLMVertex_t out = {};
	XPLMVertex_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */
/*
 * XPLMVertexColor_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMVertexColor_t XPLMVertexColor_t_from_table(lua_State* L, int stackpos)
{
	XPLMVertexColor_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "color");
	if (!lua_isnil(L, -1))
	{
		out.color = static_cast<uint32_t>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMVertexColor_t_to_table(lua_State* L, XPLMVertexColor_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "color");
	lua_pushinteger(L, src.color);
	lua_settable(L, -3);
}

int MakeXPLMVertexColor_t(lua_State* L)
{
	XPLMVertexColor_t out = {};
	XPLMVertexColor_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaMakeColor(lua_State* L)
{
	float red = xlua_checknumber(L, 1);
	float green = xlua_checknumber(L, 2);
	float blue = xlua_checknumber(L, 3);
	float alpha = xlua_checknumber(L, 4);

	uint32_t res = XPLMMakeColor(red, green, blue, alpha);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaLines(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int vertices_len = lua_objlen(L, 2);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertex_t* vertices = new XPLMVertex_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		vertices[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLines(color, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaLinesWithWidth(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	float lineWidth = xlua_checknumber(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);

	int count = xlua_checkinteger(L, 4);

	int vertices_len = lua_objlen(L, 3);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertex_t* vertices = new XPLMVertex_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		vertices[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLinesWithWidth(color, lineWidth, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaLinesc(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);

	int count = xlua_checkinteger(L, 2);

	int vertices_len = lua_objlen(L, 1);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertexColor_t* vertices = new XPLMVertexColor_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		vertices[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLinesc(vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaLinescWithWidth(lua_State* L)
{
	float lineWidth = xlua_checknumber(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int vertices_len = lua_objlen(L, 2);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertexColor_t* vertices = new XPLMVertexColor_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		vertices[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLinescWithWidth(lineWidth, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaLinesStipple(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);
	float dashLength = xlua_checknumber(L, 4);
	float lineWidth = xlua_checknumber(L, 5);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLinesStipple(color, pts, count, dashLength, lineWidth);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineStrip(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineStrip(color, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineStripWithWidth(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	float lineWidth = xlua_checknumber(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);

	int count = xlua_checkinteger(L, 4);

	int pts_len = lua_objlen(L, 3);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineStripWithWidth(color, lineWidth, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineStripc(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);

	int count = xlua_checkinteger(L, 2);

	int pts_len = lua_objlen(L, 1);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertexColor_t* pts = new XPLMVertexColor_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		pts[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineStripc(pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineStripcWithWidth(lua_State* L)
{
	float lineWidth = xlua_checknumber(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertexColor_t* pts = new XPLMVertexColor_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineStripcWithWidth(lineWidth, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineStripStipple(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);
	float dashLength = xlua_checknumber(L, 4);
	float lineWidth = xlua_checknumber(L, 5);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineStripStipple(color, pts, count, dashLength, lineWidth);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineLoop(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineLoop(color, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineLoopWithWidth(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	float lineWidth = xlua_checknumber(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);

	int count = xlua_checkinteger(L, 4);

	int pts_len = lua_objlen(L, 3);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineLoopWithWidth(color, lineWidth, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineLoopc(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);

	int count = xlua_checkinteger(L, 2);

	int pts_len = lua_objlen(L, 1);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertexColor_t* pts = new XPLMVertexColor_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		pts[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineLoopc(pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineLoopcWithWidth(lua_State* L)
{
	float lineWidth = xlua_checknumber(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertexColor_t* pts = new XPLMVertexColor_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineLoopcWithWidth(lineWidth, pts, count);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaLineLoopStipple(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);
	float dashLength = xlua_checknumber(L, 4);
	float lineWidth = xlua_checknumber(L, 5);

	int pts_len = lua_objlen(L, 2);
	pts_len = std::min(pts_len, static_cast<int>(count));
	XPLMVertex_t* pts = new XPLMVertex_t[pts_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < pts_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		pts[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMLineLoopStipple(color, pts, count, dashLength, lineWidth);

	if (pts != nullptr)
	{
		delete[] pts;
	}

	return 0;
}

int XLuaPolygon(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int vertices_len = lua_objlen(L, 2);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertex_t* vertices = new XPLMVertex_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		vertices[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMPolygon(color, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaPolygonc(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);

	int count = xlua_checkinteger(L, 2);

	int vertices_len = lua_objlen(L, 1);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertexColor_t* vertices = new XPLMVertexColor_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		vertices[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMPolygonc(vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaQuadstrip(lua_State* L)
{
	uint32_t color = xlua_checkinteger(L, 1);
	luaL_checktype(L, 2, LUA_TTABLE);

	int count = xlua_checkinteger(L, 3);

	int vertices_len = lua_objlen(L, 2);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertex_t* vertices = new XPLMVertex_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		vertices[i] = XPLMVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMQuadstrip(color, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

int XLuaQuadstripc(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);

	int count = xlua_checkinteger(L, 2);

	int vertices_len = lua_objlen(L, 1);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMVertexColor_t* vertices = new XPLMVertexColor_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		vertices[i] = XPLMVertexColor_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMQuadstripc(vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

void RegEnum_XPLMCharSet_t(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_CharSetDigits");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_CharSetASCII");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_CharSetUnicode");
	lua_setglobal(L, "XPLMCharSet_t");
}

void RegEnum_XPLMJustification_t(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_JustLeft");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_JustCenter");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_JustRight");
	lua_setglobal(L, "XPLMJustification_t");
}
/*
 * XPLMFontMetrics_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMFontMetrics_t XPLMFontMetrics_t_from_table(lua_State* L, int stackpos)
{
	XPLMFontMetrics_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "lineHeight");
	if (!lua_isnil(L, -1))
	{
		out.lineHeight = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "lineAscent");
	if (!lua_isnil(L, -1))
	{
		out.lineAscent = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "lineDescent");
	if (!lua_isnil(L, -1))
	{
		out.lineDescent = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMFontMetrics_t_to_table(lua_State* L, XPLMFontMetrics_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "lineHeight");
	lua_pushnumber(L, src.lineHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "lineAscent");
	lua_pushnumber(L, src.lineAscent);
	lua_settable(L, -3);

	lua_pushstring(L, "lineDescent");
	lua_pushnumber(L, src.lineDescent);
	lua_settable(L, -3);
}

int MakeXPLMFontMetrics_t(lua_State* L)
{
	XPLMFontMetrics_t out = {};
	out.structSize = sizeof(XPLMFontMetrics_t);
	XPLMFontMetrics_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

XPLMFontHandle* Make_XPLMFontHandle(lua_State* L, XPLMFontHandle const& init)
{
	XPLMFontHandle* ud = static_cast<XPLMFontHandle*>(lua_newuserdata(L, sizeof(XPLMFontHandle)));
	memcpy(ud, &init, sizeof(XPLMFontHandle));

	luaL_getmetatable(L, "_mt_XPLMFontHandle");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMFontHandle_Constructor(lua_State* L)
{
	Make_XPLMFontHandle(L, nullptr);
	return 1;
}

static int _XPLMFontHandle_compare(lua_State* L)
{
	XPLMFontHandle const test1 = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	XPLMFontHandle const test2 = xlua_checkuserdata<XPLMFontHandle>(L, 2, "Expected XPLMFontHandle");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMFontHandle(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMFontHandle");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMFontHandle");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMFontHandle_tostring
	lua_pushcfunction(L, _XPLMFontHandle_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMFontHandle_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMFontHandle", _XPLMFontHandle_Constructor);

	lua_pop(L, 1);
}

int XLuaCreateFont(lua_State* L)
{
	XPLMCharSet_t charset = xlua_checkinteger(L, 1);

	XPLMFontHandle res = XPLMCreateFont(charset);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMFontHandle(L, res);
	}

	return 1;
}

int XLuaDestroyFont(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}

	XPLMDestroyFont(font);

	return 0;
}

int XLuaFontAddFace(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	char const* ttf_path = xlua_checkstring(L, 2);

	int res = XPLMFontAddFace(font, ttf_path);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaFontGetMetrics(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	float fontSize = xlua_checknumber(L, 2);
	XPLMFontMetrics_t outMetrics = {};
	outMetrics.structSize = sizeof(XPLMFontMetrics_t);

	XPLMFontGetMetrics(font, fontSize, &outMetrics);
	XPLMFontMetrics_t_to_table(L, outMetrics);

	return 1;
}

int XLuaFontMeasureString(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	float fontSize = xlua_checknumber(L, 2);
	char const* string = xlua_checkstring(L, 3);

	float res = XPLMFontMeasureString(font, fontSize, string);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaFontGetLineCount(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	float fontSize = xlua_checknumber(L, 2);
	char const* string = xlua_checkstring(L, 3);
	float width = xlua_checknumber(L, 4);

	int res = XPLMFontGetLineCount(font, fontSize, string, width);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFontFitForward(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	float fontSize = xlua_checknumber(L, 2);
	char const* string = xlua_checkstring(L, 3);
	float width = xlua_checknumber(L, 4);

	int res = XPLMFontFitForward(font, fontSize, string, width);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFontFitReverse(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	float fontSize = xlua_checknumber(L, 2);
	char const* string = xlua_checkstring(L, 3);
	float width = xlua_checknumber(L, 4);

	int res = XPLMFontFitReverse(font, fontSize, string, width);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFontDrawString(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	uint32_t color = xlua_checkinteger(L, 2);
	float fontSize = xlua_checknumber(L, 3);
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);
	char const* string = xlua_checkstring(L, 6);
	XPLMJustification_t justification = xlua_checkinteger(L, 7);

	XPLMFontDrawString(font, color, fontSize, x, y, string, justification);

	return 0;
}

int XLuaFontDrawStringFixedSpacing(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	uint32_t color = xlua_checkinteger(L, 2);
	float fontSize = xlua_checknumber(L, 3);
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);
	char const* string = xlua_checkstring(L, 6);
	int fixedSpacing = xlua_checkinteger(L, 7);
	XPLMJustification_t justification = xlua_checkinteger(L, 8);

	XPLMFontDrawStringFixedSpacing(font, color, fontSize, x, y, string, fixedSpacing, justification);

	return 0;
}

int XLuaFontDrawStringWordWrapped(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	uint32_t color = xlua_checkinteger(L, 2);
	float fontSize = xlua_checknumber(L, 3);
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);
	char const* string = xlua_checkstring(L, 6);
	int wrapWidth = xlua_checkinteger(L, 7);
	XPLMJustification_t justification = xlua_checkinteger(L, 8);

	XPLMFontDrawStringWordWrapped(font, color, fontSize, x, y, string, wrapWidth, justification);

	return 0;
}

int XLuaFontDrawStringRotated(lua_State* L)
{
	XPLMFontHandle font = {};
	if (lua_isuserdata(L, 1))
	{
		font = xlua_checkuserdata<XPLMFontHandle>(L, 1, "Expected XPLMFontHandle");
	}
	uint32_t color = xlua_checkinteger(L, 2);
	float fontSize = xlua_checknumber(L, 3);
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);
	char const* string = xlua_checkstring(L, 6);
	float angle = xlua_checknumber(L, 7);
	XPLMJustification_t justification = xlua_checkinteger(L, 8);

	XPLMFontDrawStringRotated(font, color, fontSize, x, y, string, angle, justification);

	return 0;
}

XPLMTextureAtlasRef* Make_XPLMTextureAtlasRef(lua_State* L, XPLMTextureAtlasRef const& init)
{
	XPLMTextureAtlasRef* ud = static_cast<XPLMTextureAtlasRef*>(lua_newuserdata(L, sizeof(XPLMTextureAtlasRef)));
	memcpy(ud, &init, sizeof(XPLMTextureAtlasRef));

	luaL_getmetatable(L, "_mt_XPLMTextureAtlasRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMTextureAtlasRef_Constructor(lua_State* L)
{
	Make_XPLMTextureAtlasRef(L, nullptr);
	return 1;
}

static int _XPLMTextureAtlasRef_compare(lua_State* L)
{
	XPLMTextureAtlasRef const test1 = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	XPLMTextureAtlasRef const test2 = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 2, "Expected XPLMTextureAtlasRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMTextureAtlasRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMTextureAtlasRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMTextureAtlasRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMTextureAtlasRef_tostring
	lua_pushcfunction(L, _XPLMTextureAtlasRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMTextureAtlasRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMTextureAtlasRef", _XPLMTextureAtlasRef_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMTextureVertex_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMTextureVertex_t XPLMTextureVertex_t_from_table(lua_State* L, int stackpos)
{
	XPLMTextureVertex_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "s");
	if (!lua_isnil(L, -1))
	{
		out.s = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "t");
	if (!lua_isnil(L, -1))
	{
		out.t = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMTextureVertex_t_to_table(lua_State* L, XPLMTextureVertex_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "s");
	lua_pushnumber(L, src.s);
	lua_settable(L, -3);

	lua_pushstring(L, "t");
	lua_pushnumber(L, src.t);
	lua_settable(L, -3);
}

int MakeXPLMTextureVertex_t(lua_State* L)
{
	XPLMTextureVertex_t out = {};
	XPLMTextureVertex_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCreateTextureAtlas(lua_State* L)
{
	XPLMTextureAtlasRef res = XPLMCreateTextureAtlas();
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMTextureAtlasRef(L, res);
	}

	return 1;
}

int XLuaDestroyTextureAtlas(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}

	XPLMDestroyTextureAtlas(inTextureAtlas);

	return 0;
}

int XLuaTextureAtlasAddImageFile(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	const char * inImageFilePath = xlua_checkstring(L, 2);

	int res = XPLMTextureAtlasAddImageFile(inTextureAtlas, inImageFilePath);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaTextureAtlasAddImageFileSet(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	const char * inImageFilePath = xlua_checkstring(L, 2);
	int inCellsX = xlua_checkinteger(L, 3);
	int inCellsY = xlua_checkinteger(L, 4);

	int res = XPLMTextureAtlasAddImageFileSet(inTextureAtlas, inImageFilePath, inCellsX, inCellsY);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaTextureAtlasAddImage(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	const unsigned char * inImage = {};
	if (lua_isuserdata(L, 2))
	{
		inImage = xlua_checkuserdata<const unsigned char *>(L, 2, "Expected const unsigned char *");
	}
	int inWidth = xlua_checkinteger(L, 3);
	int inHeight = xlua_checkinteger(L, 4);

	int res = XPLMTextureAtlasAddImage(inTextureAtlas, inImage, inWidth, inHeight);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaTextureAtlasBake(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}

	XPLMTextureAtlasBake(inTextureAtlas);

	return 0;
}

int XLuaTextureAtlasGetImageWidth(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);

	int res = XPLMTextureAtlasGetImageWidth(inTextureAtlas, inImageIndex);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaTextureAtlasGetImageHeight(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);

	int res = XPLMTextureAtlasGetImageHeight(inTextureAtlas, inImageIndex);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaTextureAtlasDrawAt(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);
	uint32_t inTintColor = xlua_checkinteger(L, 3);
	float inX = xlua_checknumber(L, 4);
	float inY = xlua_checknumber(L, 5);

	XPLMTextureAtlasDrawAt(inTextureAtlas, inImageIndex, inTintColor, inX, inY);

	return 0;
}

int XLuaTextureAtlasDrawIn(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);
	uint32_t inTintColor = xlua_checkinteger(L, 3);
	float inLeft = xlua_checknumber(L, 4);
	float inTop = xlua_checknumber(L, 5);
	float inRight = xlua_checknumber(L, 6);
	float inBottom = xlua_checknumber(L, 7);

	XPLMTextureAtlasDrawIn(inTextureAtlas, inImageIndex, inTintColor, inLeft, inTop, inRight, inBottom);

	return 0;
}

int XLuaTextureAtlasDrawStretched(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);
	uint32_t inTintColor = xlua_checkinteger(L, 3);
	float inLeft = xlua_checknumber(L, 4);
	float inTop = xlua_checknumber(L, 5);
	float inRight = xlua_checknumber(L, 6);
	float inBottom = xlua_checknumber(L, 7);

	XPLMTextureAtlasDrawStretched(inTextureAtlas, inImageIndex, inTintColor, inLeft, inTop, inRight, inBottom);

	return 0;
}

int XLuaTextureAtlasDrawScaled(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);
	uint32_t inTintColor = xlua_checkinteger(L, 3);
	float inXPanel = xlua_checknumber(L, 4);
	float inYPanel = xlua_checknumber(L, 5);
	float inXAtlas = xlua_checknumber(L, 6);
	float inYAtlas = xlua_checknumber(L, 7);
	float inXScale = xlua_checknumber(L, 8);
	float inYScale = xlua_checknumber(L, 9);
	float inRotateCW = xlua_checknumber(L, 10);

	XPLMTextureAtlasDrawScaled(inTextureAtlas, inImageIndex, inTintColor, inXPanel, inYPanel, inXAtlas, inYAtlas, inXScale, inYScale, inRotateCW);

	return 0;
}

int XLuaTextureAtlasDrawMesh(lua_State* L)
{
	XPLMTextureAtlasRef inTextureAtlas = {};
	if (lua_isuserdata(L, 1))
	{
		inTextureAtlas = xlua_checkuserdata<XPLMTextureAtlasRef>(L, 1, "Expected XPLMTextureAtlasRef");
	}
	int inImageIndex = xlua_checkinteger(L, 2);
	uint32_t inTintColor = xlua_checkinteger(L, 3);
	luaL_checktype(L, 4, LUA_TTABLE);

	int count = xlua_checkinteger(L, 5);

	int vertices_len = lua_objlen(L, 4);
	vertices_len = std::min(vertices_len, static_cast<int>(count));
	XPLMTextureVertex_t* vertices = new XPLMTextureVertex_t[vertices_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < vertices_len; ++i)
	{
		lua_rawgeti(L, 4, i + 1);
		vertices[i] = XPLMTextureVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMTextureAtlasDrawMesh(inTextureAtlas, inImageIndex, inTintColor, vertices, count);

	if (vertices != nullptr)
	{
		delete[] vertices;
	}

	return 0;
}

void RegEnum_XPLMTextureSource(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_Texture_WeatherRadar1");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_Texture_WeatherRadar2");
	lua_setglobal(L, "XPLMTextureSource");
}

int XLuaTextureSourceDrawIn(lua_State* L)
{
	XPLMTextureSource tex = xlua_checkinteger(L, 1);
	uint32_t tint = xlua_checkinteger(L, 2);
	int left = xlua_checkinteger(L, 3);
	int top = xlua_checkinteger(L, 4);
	int right = xlua_checkinteger(L, 5);
	int bottom = xlua_checkinteger(L, 6);

	XPLMTextureSourceDrawIn(tex, tint, left, top, right, bottom);

	return 0;
}

int XLuaTextureSourceDrawMesh(lua_State* L)
{
	XPLMTextureSource tex = xlua_checkinteger(L, 1);
	uint32_t tint = xlua_checkinteger(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);

	int count = xlua_checkinteger(L, 4);

	int mesh_len = lua_objlen(L, 3);
	mesh_len = std::min(mesh_len, static_cast<int>(count));
	XPLMTextureVertex_t* mesh = new XPLMTextureVertex_t[mesh_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < mesh_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		mesh[i] = XPLMTextureVertex_t_from_table(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMTextureSourceDrawMesh(tex, tint, mesh, count);

	if (mesh != nullptr)
	{
		delete[] mesh;
	}

	return 0;
}

int XLuaTransformPush(lua_State* L)
{
	XPLMTransformPush();

	return 0;
}

int XLuaTransformPop(lua_State* L)
{
	XPLMTransformPop();

	return 0;
}

int XLuaTransformTranslate(lua_State* L)
{
	float dx = xlua_checknumber(L, 1);
	float dy = xlua_checknumber(L, 2);

	XPLMTransformTranslate(dx, dy);

	return 0;
}

int XLuaTransformRotate(lua_State* L)
{
	float centerX = xlua_checknumber(L, 1);
	float centerY = xlua_checknumber(L, 2);
	float angle = xlua_checknumber(L, 3);

	XPLMTransformRotate(centerX, centerY, angle);

	return 0;
}

int XLuaTransformScale(lua_State* L)
{
	float scaleX = xlua_checknumber(L, 1);
	float scaleY = xlua_checknumber(L, 2);

	XPLMTransformScale(scaleX, scaleY);

	return 0;
}

int XLuaScissorPush(lua_State* L)
{
	XPLMScissorPush();

	return 0;
}

int XLuaScissorPop(lua_State* L)
{
	XPLMScissorPop();

	return 0;
}

int XLuaScissorSet(lua_State* L)
{
	int left = xlua_checkinteger(L, 1);
	int top = xlua_checkinteger(L, 2);
	int right = xlua_checkinteger(L, 3);
	int bottom = xlua_checkinteger(L, 4);

	XPLMScissorSet(left, top, right, bottom);

	return 0;
}

int XLuaScissorIntersect(lua_State* L)
{
	int left = xlua_checkinteger(L, 1);
	int top = xlua_checkinteger(L, 2);
	int right = xlua_checkinteger(L, 3);
	int bottom = xlua_checkinteger(L, 4);

	XPLMScissorIntersect(left, top, right, bottom);

	return 0;
}

int XLuaBeginSetupStencilMask(lua_State* L)
{
	unsigned int bits = xlua_checkinteger(L, 1);
	unsigned int mask = xlua_checkinteger(L, 2);

	XPLMBeginSetupStencilMask(bits, mask);

	return 0;
}

int XLuaEndSetupStencilMask(lua_State* L)
{
	XPLMEndSetupStencilMask();

	return 0;
}

int XLuaUseStencilMask(lua_State* L)
{
	unsigned int bits = xlua_checkinteger(L, 1);
	unsigned int mask = xlua_checkinteger(L, 2);

	XPLMUseStencilMask(bits, mask);

	return 0;
}

int XLuaClearStencilMask(lua_State* L)
{
	XPLMClearStencilMask();

	return 0;
}

void RegEnum_XPLMTouchZone(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_TouchZone_Nothing");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_TouchZone_Command");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_TouchZone_Identifier");
	lua_setglobal(L, "XPLMTouchZone");
}

static void cb_XPLMTouchEvent_f(int identifier, XPLMMouseStatus status, int x, int y, int dx, int dy, int button, void* ref)
{
	notify_cb_t const* ref_cb = static_cast<notify_cb_t*>(ref);

	lua_State* L = setup_lua_callback(ref_cb, "XPLMTouchEvent_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "iiiiiiir", identifier, status, x, y, dx, dy, button, ref_cb->get_capture()))
		{
		}
	}
}
/*
 * XPLMTouchZoneSpec_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMTouchZoneSpec_t XPLMTouchZoneSpec_t_from_table(lua_State* L, int stackpos)
{
	XPLMTouchZoneSpec_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "type");
	if (!lua_isnil(L, -1))
	{
		out.type = static_cast<XPLMTouchZone>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "command");
	if (!lua_isnil(L, -1))
	{
		out.command = static_cast<XPLMCommandRef>(xlua_checkuserdata<XPLMCommandRef>(L, -1, "Expected XPLMCommandRef"));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "identifier");
	if (!lua_isnil(L, -1))
	{
		out.identifier = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "left");
	if (!lua_isnil(L, -1))
	{
		out.left = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "top");
	if (!lua_isnil(L, -1))
	{
		out.top = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "right");
	if (!lua_isnil(L, -1))
	{
		out.right = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bottom");
	if (!lua_isnil(L, -1))
	{
		out.bottom = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMTouchZoneSpec_t_to_table(lua_State* L, XPLMTouchZoneSpec_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "type");
	lua_pushinteger(L, src.type);
	lua_settable(L, -3);

	lua_pushstring(L, "command");
	xlua_pushuserdata<XPLMCommandRef>(L, src.command);
	lua_settable(L, -3);

	lua_pushstring(L, "identifier");
	lua_pushinteger(L, src.identifier);
	lua_settable(L, -3);

	lua_pushstring(L, "left");
	lua_pushinteger(L, src.left);
	lua_settable(L, -3);

	lua_pushstring(L, "top");
	lua_pushinteger(L, src.top);
	lua_settable(L, -3);

	lua_pushstring(L, "right");
	lua_pushinteger(L, src.right);
	lua_settable(L, -3);

	lua_pushstring(L, "bottom");
	lua_pushinteger(L, src.bottom);
	lua_settable(L, -3);
}

int MakeXPLMTouchZoneSpec_t(lua_State* L)
{
	XPLMTouchZoneSpec_t out = {};
	out.structSize = sizeof(XPLMTouchZoneSpec_t);
	XPLMTouchZoneSpec_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaAccumulateTouchZone(lua_State* L)
{
	XPLMTouchZoneSpec_t inSpec = XPLMTouchZoneSpec_t_from_table(L, 1);

	int res = XPLMAccumulateTouchZone(&inSpec);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaAvionicsSetTouchEventHandler(lua_State* L)
{
	XPLMAvionicsID avionic = {};
	if (lua_isuserdata(L, 1))
	{
		avionic = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 3);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 2, true, "XPLMTouchEvent_f");

	XPLMAvionicsSetTouchEventHandler(avionic, (cb_capture_0 ? cb_XPLMTouchEvent_f : nullptr), cb_capture_0.get());

	return 0;
}

int XLuaWindowSetTouchEventHandler(lua_State* L)
{
	XPLMWindowID window = {};
	if (lua_isuserdata(L, 1))
	{
		window = xlua_checkuserdata<XPLMWindowID>(L, 1, "Expected XPLMWindowID");
	}

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 3);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 2, true, "XPLMTouchEvent_f");

	XPLMWindowSetTouchEventHandler(window, (cb_capture_0 ? cb_XPLMTouchEvent_f : nullptr), cb_capture_0.get());

	return 0;
}

XPLMRetainedDrawing_t* Make_XPLMRetainedDrawing_t(lua_State* L, XPLMRetainedDrawing_t const& init)
{
	XPLMRetainedDrawing_t* ud = static_cast<XPLMRetainedDrawing_t*>(lua_newuserdata(L, sizeof(XPLMRetainedDrawing_t)));
	memcpy(ud, &init, sizeof(XPLMRetainedDrawing_t));

	luaL_getmetatable(L, "_mt_XPLMRetainedDrawing_t");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMRetainedDrawing_t_Constructor(lua_State* L)
{
	Make_XPLMRetainedDrawing_t(L, nullptr);
	return 1;
}

static int _XPLMRetainedDrawing_t_compare(lua_State* L)
{
	XPLMRetainedDrawing_t const test1 = xlua_checkuserdata<XPLMRetainedDrawing_t>(L, 1, "Expected XPLMRetainedDrawing_t");
	XPLMRetainedDrawing_t const test2 = xlua_checkuserdata<XPLMRetainedDrawing_t>(L, 2, "Expected XPLMRetainedDrawing_t");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMRetainedDrawing_t(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMRetainedDrawing_t");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMRetainedDrawing_t");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMRetainedDrawing_t_tostring
	lua_pushcfunction(L, _XPLMRetainedDrawing_t_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMRetainedDrawing_t_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMRetainedDrawing_t", _XPLMRetainedDrawing_t_Constructor);

	lua_pop(L, 1);
}

int XLuaBeginRetainedDrawing(lua_State* L)
{
	XPLMBeginRetainedDrawing();

	return 0;
}

int XLuaEndRetainedDrawing(lua_State* L)
{
	XPLMRetainedDrawing_t res = XPLMEndRetainedDrawing();
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMRetainedDrawing_t(L, res);
	}

	return 1;
}

int XLuaDrawRetained(lua_State* L)
{
	XPLMRetainedDrawing_t drawing = {};
	if (lua_isuserdata(L, 1))
	{
		drawing = xlua_checkuserdata<XPLMRetainedDrawing_t>(L, 1, "Expected XPLMRetainedDrawing_t");
	}

	XPLMDrawRetained(drawing);

	return 0;
}

int XLuaDestroyRetainedDrawing(lua_State* L)
{
	XPLMRetainedDrawing_t drawing = {};
	if (lua_isuserdata(L, 1))
	{
		drawing = xlua_checkuserdata<XPLMRetainedDrawing_t>(L, 1, "Expected XPLMRetainedDrawing_t");
	}

	XPLMDestroyRetainedDrawing(drawing);

	return 0;
}

void RegEnum_XPLMSVTFeatures(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_SVT_Terrain");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_SVT_Runways");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "xplm_SVT_Obstacles");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "xplm_SVT_FlightPath");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "xplm_SVT_Traffic");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "xplm_SVT_AirportSigns");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "xplm_SVT_ILSHoops");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "xplm_SVT_HorizonHeading");
	lua_pushinteger(L, 255);
	lua_setfield(L, -2, "xplm_SVT_All");
	lua_setglobal(L, "XPLMSVTFeatures");
}
/*
 * XPLMCreateSVT_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCreateSVT_t XPLMCreateSVT_t_from_table(lua_State* L, int stackpos)
{
	XPLMCreateSVT_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "pilotIndex");
	if (!lua_isnil(L, -1))
	{
		out.pilotIndex = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pixelsPerDegree");
	if (!lua_isnil(L, -1))
	{
		out.pixelsPerDegree = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCreateSVT_t_to_table(lua_State* L, XPLMCreateSVT_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "pilotIndex");
	lua_pushinteger(L, src.pilotIndex);
	lua_settable(L, -3);

	lua_pushstring(L, "pixelsPerDegree");
	lua_pushnumber(L, src.pixelsPerDegree);
	lua_settable(L, -3);
}

int MakeXPLMCreateSVT_t(lua_State* L)
{
	XPLMCreateSVT_t out = {};
	out.structSize = sizeof(XPLMCreateSVT_t);
	XPLMCreateSVT_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

XPLMSVTDisplayRef* Make_XPLMSVTDisplayRef(lua_State* L, XPLMSVTDisplayRef const& init)
{
	XPLMSVTDisplayRef* ud = static_cast<XPLMSVTDisplayRef*>(lua_newuserdata(L, sizeof(XPLMSVTDisplayRef)));
	memcpy(ud, &init, sizeof(XPLMSVTDisplayRef));

	luaL_getmetatable(L, "_mt_XPLMSVTDisplayRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMSVTDisplayRef_Constructor(lua_State* L)
{
	Make_XPLMSVTDisplayRef(L, nullptr);
	return 1;
}

static int _XPLMSVTDisplayRef_compare(lua_State* L)
{
	XPLMSVTDisplayRef const test1 = xlua_checkuserdata<XPLMSVTDisplayRef>(L, 1, "Expected XPLMSVTDisplayRef");
	XPLMSVTDisplayRef const test2 = xlua_checkuserdata<XPLMSVTDisplayRef>(L, 2, "Expected XPLMSVTDisplayRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMSVTDisplayRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMSVTDisplayRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMSVTDisplayRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMSVTDisplayRef_tostring
	lua_pushcfunction(L, _XPLMSVTDisplayRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMSVTDisplayRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMSVTDisplayRef", _XPLMSVTDisplayRef_Constructor);

	lua_pop(L, 1);
}

int XLuaCreateSVTDisplay(lua_State* L)
{
	XPLMCreateSVT_t params = XPLMCreateSVT_t_from_table(L, 1);

	XPLMSVTDisplayRef res = XPLMCreateSVTDisplay(&params);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMSVTDisplayRef(L, res);
	}

	return 1;
}

int XLuaDestroySVTDisplay(lua_State* L)
{
	XPLMSVTDisplayRef svt = {};
	if (lua_isuserdata(L, 1))
	{
		svt = xlua_checkuserdata<XPLMSVTDisplayRef>(L, 1, "Expected XPLMSVTDisplayRef");
	}

	XPLMDestroySVTDisplay(svt);

	return 0;
}
/*
 * XPLMSVTCustomData_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMSVTCustomData_t XPLMSVTCustomData_t_from_table(lua_State* L, int stackpos)
{
	XPLMSVTCustomData_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "pitchDeg");
	if (!lua_isnil(L, -1))
	{
		out.pitchDeg = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "rollDeg");
	if (!lua_isnil(L, -1))
	{
		out.rollDeg = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "headingMagDeg");
	if (!lua_isnil(L, -1))
	{
		out.headingMagDeg = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "magVarDeg");
	if (!lua_isnil(L, -1))
	{
		out.magVarDeg = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "indicatedAltFt");
	if (!lua_isnil(L, -1))
	{
		out.indicatedAltFt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "baroSettingInHg");
	if (!lua_isnil(L, -1))
	{
		out.baroSettingInHg = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "hsiSource");
	if (!lua_isnil(L, -1))
	{
		out.hsiSource = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "hdefDots");
	if (!lua_isnil(L, -1))
	{
		out.hdefDots = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "vdefDots");
	if (!lua_isnil(L, -1))
	{
		out.vdefDots = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMSVTCustomData_t_to_table(lua_State* L, XPLMSVTCustomData_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "pitchDeg");
	lua_pushnumber(L, src.pitchDeg);
	lua_settable(L, -3);

	lua_pushstring(L, "rollDeg");
	lua_pushnumber(L, src.rollDeg);
	lua_settable(L, -3);

	lua_pushstring(L, "headingMagDeg");
	lua_pushnumber(L, src.headingMagDeg);
	lua_settable(L, -3);

	lua_pushstring(L, "magVarDeg");
	lua_pushnumber(L, src.magVarDeg);
	lua_settable(L, -3);

	lua_pushstring(L, "indicatedAltFt");
	lua_pushnumber(L, src.indicatedAltFt);
	lua_settable(L, -3);

	lua_pushstring(L, "baroSettingInHg");
	lua_pushnumber(L, src.baroSettingInHg);
	lua_settable(L, -3);

	lua_pushstring(L, "hsiSource");
	lua_pushinteger(L, src.hsiSource);
	lua_settable(L, -3);

	lua_pushstring(L, "hdefDots");
	lua_pushnumber(L, src.hdefDots);
	lua_settable(L, -3);

	lua_pushstring(L, "vdefDots");
	lua_pushnumber(L, src.vdefDots);
	lua_settable(L, -3);
}

int MakeXPLMSVTCustomData_t(lua_State* L)
{
	XPLMSVTCustomData_t out = {};
	XPLMSVTCustomData_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaSVTDisplayDrawIn(lua_State* L)
{
	XPLMSVTDisplayRef svt = {};
	if (lua_isuserdata(L, 1))
	{
		svt = xlua_checkuserdata<XPLMSVTDisplayRef>(L, 1, "Expected XPLMSVTDisplayRef");
	}
	XPLMSVTFeatures features = xlua_checkinteger(L, 2);
	int left = xlua_checkinteger(L, 3);
	int top = xlua_checkinteger(L, 4);
	int right = xlua_checkinteger(L, 5);
	int bottom = xlua_checkinteger(L, 6);
	std::optional<XPLMSVTCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 7))
	{
		dataOverrides = XPLMSVTCustomData_t_from_table(L, 7);
	}

	XPLMSVTDisplayDrawIn(svt, features, left, top, right, bottom, (dataOverrides ? &*dataOverrides : nullptr));

	return 0;
}

void RegEnum_XPLMMapLayers(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_Map_Nexrad");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_Map_IR");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "xplm_Map_Topo");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "xplm_Map_Terrain");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "xplm_Map_Water");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "xplm_Map_EGPWS");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "xplm_Map_raw_elev");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "xplm_Map_safe_taxi");
	lua_setglobal(L, "XPLMMapLayers");
}

void RegEnum_XPLMEGPWSStyle(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_EGPWS_Style_Blocky");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_EGPWS_Style_Smooth");
	lua_setglobal(L, "XPLMEGPWSStyle");
}
/*
 * XPLMMapCustomData_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMMapCustomData_t XPLMMapCustomData_t_from_table(lua_State* L, int stackpos)
{
	XPLMMapCustomData_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "datLat");
	if (!lua_isnil(L, -1))
	{
		out.datLat = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "datLon");
	if (!lua_isnil(L, -1))
	{
		out.datLon = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "centerX");
	if (!lua_isnil(L, -1))
	{
		out.centerX = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "centerY");
	if (!lua_isnil(L, -1))
	{
		out.centerY = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "roseRadius");
	if (!lua_isnil(L, -1))
	{
		out.roseRadius = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "mapRange");
	if (!lua_isnil(L, -1))
	{
		out.mapRange = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "orientation");
	if (!lua_isnil(L, -1))
	{
		out.orientation = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "terrainWarn");
	if (!lua_isnil(L, -1))
	{
		out.terrainWarn = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "terrainCaution");
	if (!lua_isnil(L, -1))
	{
		out.terrainCaution = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "acfAlt");
	if (!lua_isnil(L, -1))
	{
		out.acfAlt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "gearDown");
	if (!lua_isnil(L, -1))
	{
		out.gearDown = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "trueRotation");
	if (!lua_isnil(L, -1))
	{
		out.trueRotation = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "nearestRwyElev");
	if (!lua_isnil(L, -1))
	{
		out.nearestRwyElev = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "egpwsBrightness");
	if (!lua_isnil(L, -1))
	{
		out.egpwsBrightness = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "egpwsStyle");
	if (!lua_isnil(L, -1))
	{
		out.egpwsStyle = static_cast<XPLMEGPWSStyle>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMMapCustomData_t_to_table(lua_State* L, XPLMMapCustomData_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "datLat");
	lua_pushnumber(L, src.datLat);
	lua_settable(L, -3);

	lua_pushstring(L, "datLon");
	lua_pushnumber(L, src.datLon);
	lua_settable(L, -3);

	lua_pushstring(L, "centerX");
	lua_pushinteger(L, src.centerX);
	lua_settable(L, -3);

	lua_pushstring(L, "centerY");
	lua_pushinteger(L, src.centerY);
	lua_settable(L, -3);

	lua_pushstring(L, "roseRadius");
	lua_pushinteger(L, src.roseRadius);
	lua_settable(L, -3);

	lua_pushstring(L, "mapRange");
	lua_pushnumber(L, src.mapRange);
	lua_settable(L, -3);

	lua_pushstring(L, "orientation");
	lua_pushinteger(L, src.orientation);
	lua_settable(L, -3);

	lua_pushstring(L, "terrainWarn");
	lua_pushnumber(L, src.terrainWarn);
	lua_settable(L, -3);

	lua_pushstring(L, "terrainCaution");
	lua_pushnumber(L, src.terrainCaution);
	lua_settable(L, -3);

	lua_pushstring(L, "acfAlt");
	lua_pushnumber(L, src.acfAlt);
	lua_settable(L, -3);

	lua_pushstring(L, "gearDown");
	lua_pushinteger(L, src.gearDown);
	lua_settable(L, -3);

	lua_pushstring(L, "trueRotation");
	lua_pushnumber(L, src.trueRotation);
	lua_settable(L, -3);

	lua_pushstring(L, "nearestRwyElev");
	lua_pushnumber(L, src.nearestRwyElev);
	lua_settable(L, -3);

	lua_pushstring(L, "egpwsBrightness");
	lua_pushnumber(L, src.egpwsBrightness);
	lua_settable(L, -3);

	lua_pushstring(L, "egpwsStyle");
	lua_pushinteger(L, src.egpwsStyle);
	lua_settable(L, -3);
}

int MakeXPLMMapCustomData_t(lua_State* L)
{
	XPLMMapCustomData_t out = {};
	out.structSize = sizeof(XPLMMapCustomData_t);
	XPLMMapCustomData_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */
/*
 * XPLMCreateMap_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCreateMap_t XPLMCreateMap_t_from_table(lua_State* L, int stackpos)
{
	XPLMCreateMap_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "pilotIndex");
	if (!lua_isnil(L, -1))
	{
		out.pilotIndex = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCreateMap_t_to_table(lua_State* L, XPLMCreateMap_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "pilotIndex");
	lua_pushinteger(L, src.pilotIndex);
	lua_settable(L, -3);
}

int MakeXPLMCreateMap_t(lua_State* L)
{
	XPLMCreateMap_t out = {};
	out.structSize = sizeof(XPLMCreateMap_t);
	XPLMCreateMap_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

XPLMMapDisplayRef* Make_XPLMMapDisplayRef(lua_State* L, XPLMMapDisplayRef const& init)
{
	XPLMMapDisplayRef* ud = static_cast<XPLMMapDisplayRef*>(lua_newuserdata(L, sizeof(XPLMMapDisplayRef)));
	memcpy(ud, &init, sizeof(XPLMMapDisplayRef));

	luaL_getmetatable(L, "_mt_XPLMMapDisplayRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMMapDisplayRef_Constructor(lua_State* L)
{
	Make_XPLMMapDisplayRef(L, nullptr);
	return 1;
}

static int _XPLMMapDisplayRef_compare(lua_State* L)
{
	XPLMMapDisplayRef const test1 = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	XPLMMapDisplayRef const test2 = xlua_checkuserdata<XPLMMapDisplayRef>(L, 2, "Expected XPLMMapDisplayRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMMapDisplayRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMMapDisplayRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMMapDisplayRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMMapDisplayRef_tostring
	lua_pushcfunction(L, _XPLMMapDisplayRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMMapDisplayRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMMapDisplayRef", _XPLMMapDisplayRef_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMMapDrawInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMMapDrawInfo_t XPLMMapDrawInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMMapDrawInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "layers");
	if (!lua_isnil(L, -1))
	{
		out.layers = static_cast<XPLMMapLayers>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "left");
	if (!lua_isnil(L, -1))
	{
		out.left = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "top");
	if (!lua_isnil(L, -1))
	{
		out.top = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "right");
	if (!lua_isnil(L, -1))
	{
		out.right = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bottom");
	if (!lua_isnil(L, -1))
	{
		out.bottom = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMMapDrawInfo_t_to_table(lua_State* L, XPLMMapDrawInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "layers");
	lua_pushinteger(L, src.layers);
	lua_settable(L, -3);

	lua_pushstring(L, "left");
	lua_pushinteger(L, src.left);
	lua_settable(L, -3);

	lua_pushstring(L, "top");
	lua_pushinteger(L, src.top);
	lua_settable(L, -3);

	lua_pushstring(L, "right");
	lua_pushinteger(L, src.right);
	lua_settable(L, -3);

	lua_pushstring(L, "bottom");
	lua_pushinteger(L, src.bottom);
	lua_settable(L, -3);
}

int MakeXPLMMapDrawInfo_t(lua_State* L)
{
	XPLMMapDrawInfo_t out = {};
	out.structSize = sizeof(XPLMMapDrawInfo_t);
	XPLMMapDrawInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCreateMapDisplay(lua_State* L)
{
	XPLMCreateMap_t params = XPLMCreateMap_t_from_table(L, 1);

	XPLMMapDisplayRef res = XPLMCreateMapDisplay(&params);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMMapDisplayRef(L, res);
	}

	return 1;
}

int XLuaDestroyMapDisplay(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}

	XPLMDestroyMapDisplay(map);

	return 0;
}

int XLuaMapDisplayDrawIn(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	XPLMMapDrawInfo_t info = XPLMMapDrawInfo_t_from_table(L, 2);
	std::optional<XPLMMapCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 3))
	{
		dataOverrides = XPLMMapCustomData_t_from_table(L, 3);
	}

	XPLMMapDisplayDrawIn(map, &info, (dataOverrides ? &*dataOverrides : nullptr));

	return 0;
}

int XLuaMapDisplayProject(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	XPLMMapDrawInfo_t info = XPLMMapDrawInfo_t_from_table(L, 2);
	std::optional<XPLMMapCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 3))
	{
		dataOverrides = XPLMMapCustomData_t_from_table(L, 3);
	}
	double latitude = xlua_checknumber(L, 4);
	double longitude = xlua_checknumber(L, 5);
	float outX = {};
	float outY = {};

	int res = XPLMMapDisplayProject(map, &info, (dataOverrides ? &*dataOverrides : nullptr), latitude, longitude, &outX, &outY);
	lua_pushinteger(L, res);

	lua_createtable(L, 0, 2);

	lua_pushstring(L, "outX");
	lua_pushnumber(L, outX);
	lua_settable(L, -3);

	lua_pushstring(L, "outY");
	lua_pushnumber(L, outY);
	lua_settable(L, -3);

	return 2;
}

int XLuaMapDisplayUnproject(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	XPLMMapDrawInfo_t info = XPLMMapDrawInfo_t_from_table(L, 2);
	std::optional<XPLMMapCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 3))
	{
		dataOverrides = XPLMMapCustomData_t_from_table(L, 3);
	}
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);
	double outLatitude = {};
	double outLongitude = {};

	int res = XPLMMapDisplayUnproject(map, &info, (dataOverrides ? &*dataOverrides : nullptr), x, y, &outLatitude, &outLongitude);
	lua_pushinteger(L, res);

	lua_createtable(L, 0, 2);

	lua_pushstring(L, "outLatitude");
	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");
	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	return 2;
}

int XLuaMapDisplayScaleMeter(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	XPLMMapDrawInfo_t info = XPLMMapDrawInfo_t_from_table(L, 2);
	std::optional<XPLMMapCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 3))
	{
		dataOverrides = XPLMMapCustomData_t_from_table(L, 3);
	}
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);

	float res = XPLMMapDisplayScaleMeter(map, &info, (dataOverrides ? &*dataOverrides : nullptr), x, y);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaMapDisplayGetNorthHeading(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	XPLMMapDrawInfo_t info = XPLMMapDrawInfo_t_from_table(L, 2);
	std::optional<XPLMMapCustomData_t> dataOverrides;
	if (!lua_isnoneornil(L, 3))
	{
		dataOverrides = XPLMMapCustomData_t_from_table(L, 3);
	}
	float x = xlua_checknumber(L, 4);
	float y = xlua_checknumber(L, 5);

	float res = XPLMMapDisplayGetNorthHeading(map, &info, (dataOverrides ? &*dataOverrides : nullptr), x, y);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaMapDisplayGetTerrainAltitudes(lua_State* L)
{
	XPLMMapDisplayRef map = {};
	if (lua_isuserdata(L, 1))
	{
		map = xlua_checkuserdata<XPLMMapDisplayRef>(L, 1, "Expected XPLMMapDisplayRef");
	}
	float min = {};
	float max = {};

	int res = XPLMMapDisplayGetTerrainAltitudes(map, &min, &max);
	lua_pushinteger(L, res);

	lua_createtable(L, 0, 2);

	lua_pushstring(L, "min");
	lua_pushnumber(L, min);
	lua_settable(L, -3);

	lua_pushstring(L, "max");
	lua_pushnumber(L, max);
	lua_settable(L, -3);

	return 2;
}

#ifdef __cplusplus
}
#endif

#endif
