#ifndef _Glua_XPLMMenus_h_
#define _Glua_XPLMMenus_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMMenus
 ***************************************************************************/

#include "XPLMDefs.h"
#include "XPLMUtilities.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMMenus.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>


static void cb_XPLMMenuHandler_f(void * inMenuRef, void * inItemRef)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inMenuRef);
	lua_State* L = setup_lua_callback(cb, "XPLMMenuHandler_f");
	if (L)
	{
		fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r?", cb->origRefconRegIndex, inItemRef);
	}
}

int XLuaFindPluginsMenu(lua_State* L)
{
	XPLMMenuID res = XPLMFindPluginsMenu();
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMMenuID>(L, res);
	}

	return 1;
}

int XLuaFindAircraftMenu(lua_State* L)
{
	XPLMMenuID res = XPLMFindAircraftMenu();
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMMenuID>(L, res);
	}

	return 1;
}

int XLuaCreateMenu(lua_State* L)
{
	const char * inName = luaL_checkstring(L, 1);
	XPLMMenuID inParentMenu = {};
	if (lua_isuserdata(L, 2))
	{
		inParentMenu = xlua_checkuserdata<XPLMMenuID>(L, 2, "Expected userdata<XPLMMenuID>");
	}
	int inParentItem = luaL_checkinteger(L, 3);
	int refcon_regindex = capture_lua_value(L, 5);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 4, "XPLMMenuHandler_f", refcon_regindex);

	XPLMMenuID res = XPLMCreateMenu(inName, inParentMenu, inParentItem, cb_XPLMMenuHandler_f, cb_capture_0);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMMenuID>(L, res);
	}

	return 1;
}

int XLuaDestroyMenu(lua_State* L)
{
	XPLMMenuID inMenuID = {};
	if (lua_isuserdata(L, 1))
	{
		inMenuID = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}

	XPLMDestroyMenu(inMenuID);

	return 0;
}

int XLuaClearAllMenuItems(lua_State* L)
{
	XPLMMenuID inMenuID = {};
	if (lua_isuserdata(L, 1))
	{
		inMenuID = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}

	XPLMClearAllMenuItems(inMenuID);

	return 0;
}

int XLuaAppendMenuItem(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	const char * inItemName = luaL_checkstring(L, 2);
	int inItemRef_regindex = capture_lua_value(L, 3);
	int inDeprecatedAndIgnored = luaL_checkinteger(L, 4);

	int res = XPLMAppendMenuItem(inMenu, inItemName, reinterpret_cast<void*>(static_cast<intptr_t>(inItemRef_regindex)), inDeprecatedAndIgnored);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaAppendMenuItemWithCommand(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	const char * inItemName = luaL_checkstring(L, 2);
	XPLMCommandRef inCommandToExecute = {};
	if (lua_isuserdata(L, 3))
	{
		inCommandToExecute = xlua_checkuserdata<XPLMCommandRef>(L, 3, "Expected userdata<XPLMCommandRef>");
	}

	int res = XPLMAppendMenuItemWithCommand(inMenu, inItemName, inCommandToExecute);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaAppendMenuSeparator(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}

	XPLMAppendMenuSeparator(inMenu);

	return 0;
}

int XLuaSetMenuItemName(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	int inIndex = luaL_checkinteger(L, 2);
	const char * inItemName = luaL_checkstring(L, 3);
	int inDeprecatedAndIgnored = luaL_checkinteger(L, 4);

	XPLMSetMenuItemName(inMenu, inIndex, inItemName, inDeprecatedAndIgnored);

	return 0;
}

int XLuaCheckMenuItem(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	int index = luaL_checkinteger(L, 2);
	XPLMMenuCheck inCheck = luaL_checkinteger(L, 3);

	XPLMCheckMenuItem(inMenu, index, inCheck);

	return 0;
}

int XLuaCheckMenuItemState(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	int index = luaL_checkinteger(L, 2);
	XPLMMenuCheck outCheck;

	XPLMCheckMenuItemState(inMenu, index, &outCheck);

	lua_createtable(L, 0, 1); // 0 array slots and 1 key-value pairs

	lua_pushstring(L, "outCheck");
	lua_pushinteger(L, outCheck);
	lua_settable(L, -3);

	return 1;
}

int XLuaEnableMenuItem(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	int index = luaL_checkinteger(L, 2);
	bool enabled = xlua_checkboolean(L, 3);

	XPLMEnableMenuItem(inMenu, index, enabled);

	return 0;
}

int XLuaRemoveMenuItem(lua_State* L)
{
	XPLMMenuID inMenu = {};
	if (lua_isuserdata(L, 1))
	{
		inMenu = xlua_checkuserdata<XPLMMenuID>(L, 1, "Expected userdata<XPLMMenuID>");
	}
	int inIndex = luaL_checkinteger(L, 2);

	XPLMRemoveMenuItem(inMenu, inIndex);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
