#ifndef _Glua_XPLMCamera_h_
#define _Glua_XPLMCamera_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMCamera
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMCamera.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMCameraPosition_t XPLMCameraPosition_t_from_table(lua_State* L, int stackpos);
void XPLMCameraPosition_t_to_table(lua_State* L, XPLMCameraPosition_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);

/*
 * XPLMCameraPosition_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCameraPosition_t XPLMCameraPosition_t_from_table(lua_State* L, int stackpos)
{
	XPLMCameraPosition_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, -1, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "z");
	if (!lua_isnil(L, -1))
	{
		out.z = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "pitch");
	if (!lua_isnil(L, -1))
	{
		out.pitch = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "heading");
	if (!lua_isnil(L, -1))
	{
		out.heading = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "roll");
	if (!lua_isnil(L, -1))
	{
		out.roll = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "zoom");
	if (!lua_isnil(L, -1))
	{
		out.zoom = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCameraPosition_t_to_table(lua_State* L, XPLMCameraPosition_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "z");
	lua_pushnumber(L, src.z);
	lua_settable(L, -3);

	lua_pushstring(L, "pitch");
	lua_pushnumber(L, src.pitch);
	lua_settable(L, -3);

	lua_pushstring(L, "heading");
	lua_pushnumber(L, src.heading);
	lua_settable(L, -3);

	lua_pushstring(L, "roll");
	lua_pushnumber(L, src.roll);
	lua_settable(L, -3);

	lua_pushstring(L, "zoom");
	lua_pushnumber(L, src.zoom);
	lua_settable(L, -3);
}

int MakeXPLMCameraPosition_t(lua_State* L)
{
	XPLMCameraPosition_t out = {};
	XPLMCameraPosition_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

static int cb_XPLMCameraControl_f(XPLMCameraPosition_t * outCameraPosition, int inIsLosingControl, void* inRefcon)
{
	int res = {};
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMCameraControl_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "?br", outCameraPosition, static_cast<bool>(inIsLosingControl), cb->get_capture()))
		{
			res = xlua_checkboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}
	}

	return res;
}

int XLuaControlCamera(lua_State* L)
{
	XPLMCameraControlDuration inHowLong = xlua_checkinteger(L, 1);
	int refcon_regindex = capture_lua_value(L, 3);
	CleanupStoredCallbacks(L, refcon_regindex);

	std::shared_ptr<notify_cb_t> cb_capture_0 = wrap_first_lua_func(L, 2, "XPLMCameraControl_f", refcon_regindex);

	XPLMControlCamera(inHowLong, cb_XPLMCameraControl_f, cb_capture_0.get());

	return 0;
}

int XLuaDontControlCamera(lua_State* L)
{
	XPLMDontControlCamera();

	return 0;
}

int XLuaIsCameraBeingControlled(lua_State* L)
{
	XPLMCameraControlDuration outCameraControlDuration;
	int res = XPLMIsCameraBeingControlled(&outCameraControlDuration);
	lua_pushboolean(L, res);

	lua_pushinteger(L, outCameraControlDuration);

	return 2;
}

int XLuaReadCameraPosition(lua_State* L)
{
	XPLMCameraPosition_t outCameraPosition;
	XPLMReadCameraPosition(&outCameraPosition);
	XPLMCameraPosition_t_to_table(L, outCameraPosition);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
