#ifndef _Glua_XPLMPlanes_h_
#define _Glua_XPLMPlanes_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMPlanes
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMPlanes.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);
XPLMPlaneDrawState_t XPLMPlaneDrawState_t_from_table(lua_State* L, int stackpos);
void XPLMPlaneDrawState_t_to_table(lua_State* L, XPLMPlaneDrawState_t const& src);

int XLuaInitFlight(lua_State* L)
{
	char const* inJsonData = xlua_checkstring(L, 1);

	XPLMInitResult res = XPLMInitFlight(inJsonData);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaUpdateFlight(lua_State* L)
{
	char const* inJsonData = xlua_checkstring(L, 1);

	XPLMInitResult res = XPLMUpdateFlight(inJsonData);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetUsersAircraft(lua_State* L)
{
	const char * inAircraftPath = xlua_checkstring(L, 1);

	XPLMSetUsersAircraft(inAircraftPath);

	return 0;
}

int XLuaPlaceUserAtAirport(lua_State* L)
{
	const char * inAirportCode = xlua_checkstring(L, 1);

	XPLMPlaceUserAtAirport(inAirportCode);

	return 0;
}

int XLuaPlaceUserAtLocation(lua_State* L)
{
	double latitudeDegrees = xlua_checknumber(L, 1);
	double longitudeDegrees = xlua_checknumber(L, 2);
	float elevationMetersMSL = xlua_checknumber(L, 3);
	float headingDegreesTrue = xlua_checknumber(L, 4);
	float speedMetersPerSecond = xlua_checknumber(L, 5);

	XPLMPlaceUserAtLocation(latitudeDegrees, longitudeDegrees, elevationMetersMSL, headingDegreesTrue, speedMetersPerSecond);

	return 0;
}
/*
 * XPLMPlaneDrawState_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMPlaneDrawState_t XPLMPlaneDrawState_t_from_table(lua_State* L, int stackpos)
{
	XPLMPlaneDrawState_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);
	lua_pop(L, 1);

	lua_getfield(L, -1, "gearPosition");
	if (!lua_isnil(L, -1))
	{
		out.gearPosition = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "flapRatio");
	if (!lua_isnil(L, -1))
	{
		out.flapRatio = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "spoilerRatio");
	if (!lua_isnil(L, -1))
	{
		out.spoilerRatio = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "speedBrakeRatio");
	if (!lua_isnil(L, -1))
	{
		out.speedBrakeRatio = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "slatRatio");
	if (!lua_isnil(L, -1))
	{
		out.slatRatio = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "wingSweep");
	if (!lua_isnil(L, -1))
	{
		out.wingSweep = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "thrust");
	if (!lua_isnil(L, -1))
	{
		out.thrust = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "yokePitch");
	if (!lua_isnil(L, -1))
	{
		out.yokePitch = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "yokeHeading");
	if (!lua_isnil(L, -1))
	{
		out.yokeHeading = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "yokeRoll");
	if (!lua_isnil(L, -1))
	{
		out.yokeRoll = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMPlaneDrawState_t_to_table(lua_State* L, XPLMPlaneDrawState_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "gearPosition");
	lua_pushnumber(L, src.gearPosition);
	lua_settable(L, -3);

	lua_pushstring(L, "flapRatio");
	lua_pushnumber(L, src.flapRatio);
	lua_settable(L, -3);

	lua_pushstring(L, "spoilerRatio");
	lua_pushnumber(L, src.spoilerRatio);
	lua_settable(L, -3);

	lua_pushstring(L, "speedBrakeRatio");
	lua_pushnumber(L, src.speedBrakeRatio);
	lua_settable(L, -3);

	lua_pushstring(L, "slatRatio");
	lua_pushnumber(L, src.slatRatio);
	lua_settable(L, -3);

	lua_pushstring(L, "wingSweep");
	lua_pushnumber(L, src.wingSweep);
	lua_settable(L, -3);

	lua_pushstring(L, "thrust");
	lua_pushnumber(L, src.thrust);
	lua_settable(L, -3);

	lua_pushstring(L, "yokePitch");
	lua_pushnumber(L, src.yokePitch);
	lua_settable(L, -3);

	lua_pushstring(L, "yokeHeading");
	lua_pushnumber(L, src.yokeHeading);
	lua_settable(L, -3);

	lua_pushstring(L, "yokeRoll");
	lua_pushnumber(L, src.yokeRoll);
	lua_settable(L, -3);
}

int MakeXPLMPlaneDrawState_t(lua_State* L)
{
	XPLMPlaneDrawState_t out = {};
	out.structSize = sizeof(XPLMPlaneDrawState_t);
	XPLMPlaneDrawState_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCountAircraft(lua_State* L)
{
	int outTotalAircraft;
	int outActiveAircraft;
	XPLMPluginID outController;
	XPLMCountAircraft(&outTotalAircraft, &outActiveAircraft, &outController);

	lua_createtable(L, 0, 3); // 0 array slots and 3 key-value pairs

	lua_pushstring(L, "outTotalAircraft");

	lua_pushinteger(L, outTotalAircraft);
	lua_settable(L, -3);

	lua_pushstring(L, "outActiveAircraft");

	lua_pushinteger(L, outActiveAircraft);
	lua_settable(L, -3);

	lua_pushstring(L, "outController");

	xlua_pushuserdata<XPLMPluginID>(L, outController);
	lua_settable(L, -3);

	return 1;
}

int XLuaGetNthAircraftModel(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	char outFileName[256];
	char outPath[512];

	XPLMGetNthAircraftModel(inIndex, outFileName, outPath);

	lua_createtable(L, 0, 2); // 0 array slots and 2 key-value pairs

	lua_pushstring(L, "outFileName");

	lua_pushstring(L, outFileName);
	lua_settable(L, -3);

	lua_pushstring(L, "outPath");

	lua_pushstring(L, outPath);
	lua_settable(L, -3);

	return 1;
}

static void cb_XPLMPlanesAvailable_f(void* inRefcon)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMPlanesAvailable_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r", cb->origRefconRegIndex))
		{
		}
	}
}

int XLuaReleasePlanes(lua_State* L)
{
	XPLMReleasePlanes();

	return 0;
}

int XLuaSetActiveAircraftCount(lua_State* L)
{
	int inCount = xlua_checkinteger(L, 1);

	XPLMSetActiveAircraftCount(inCount);

	return 0;
}

int XLuaSetAircraftModel(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	const char * inAircraftPath = xlua_checkstring(L, 2);

	XPLMSetAircraftModel(inIndex, inAircraftPath);

	return 0;
}

int XLuaDisableAIForPlane(lua_State* L)
{
	int inPlaneIndex = xlua_checkinteger(L, 1);

	XPLMDisableAIForPlane(inPlaneIndex);

	return 0;
}

int XLuaDrawAircraft(lua_State* L)
{
	int inPlaneIndex = xlua_checkinteger(L, 1);
	float inX = xlua_checknumber(L, 2);
	float inY = xlua_checknumber(L, 3);
	float inZ = xlua_checknumber(L, 4);
	float inPitch = xlua_checknumber(L, 5);
	float inRoll = xlua_checknumber(L, 6);
	float inYaw = xlua_checknumber(L, 7);
	bool inFullDraw = xlua_checkboolean(L, 8);
	XPLMPlaneDrawState_t inDrawStateInfo = XPLMPlaneDrawState_t_from_table(L, 9);

	XPLMDrawAircraft(inPlaneIndex, inX, inY, inZ, inPitch, inRoll, inYaw, inFullDraw, &inDrawStateInfo);

	return 0;
}

int XLuaReinitUsersPlane(lua_State* L)
{
	XPLMReinitUsersPlane();

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
