#ifndef _Glua_XPLMStore_h_
#define _Glua_XPLMStore_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMStore
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMStore.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//


int XLuaIsStoreManagedPlugin(lua_State* L)
{
	int res = XPLMIsStoreManagedPlugin();
	lua_pushboolean(L, res);

	return 1;
}

void RegEnum_XPLMDecryptResult(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplmDecrypt_Ok");
	lua_pushinteger(L, -1);
	lua_setfield(L, -2, "xplmDecrypt_NotAllowed");
	lua_pushinteger(L, -2);
	lua_setfield(L, -2, "xplmDecrypt_FileError");
	lua_setglobal(L, "XPLMDecryptResult");
}

int XLuaStoreIsEncrypted(lua_State* L)
{
	const char * inFilePath = xlua_checkstring(L, 1);

	int res = XPLMStoreIsEncrypted(inFilePath);
	lua_pushinteger(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
