#ifndef _Glua_XPLMGraphics_h_
#define _Glua_XPLMGraphics_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMGraphics
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMGraphics.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//


int XLuaWorldToLocal(lua_State* L)
{
	double inLatitude = xlua_checknumber(L, 1);
	double inLongitude = xlua_checknumber(L, 2);
	double inAltitude = xlua_checknumber(L, 3);
	double outX = {};
	double outY = {};
	double outZ = {};

	XPLMWorldToLocal(inLatitude, inLongitude, inAltitude, &outX, &outY, &outZ);

	lua_createtable(L, 0, 3);

	lua_pushstring(L, "outX");
	lua_pushnumber(L, outX);
	lua_settable(L, -3);

	lua_pushstring(L, "outY");
	lua_pushnumber(L, outY);
	lua_settable(L, -3);

	lua_pushstring(L, "outZ");
	lua_pushnumber(L, outZ);
	lua_settable(L, -3);

	return 1;
}

int XLuaLocalToWorld(lua_State* L)
{
	double inX = xlua_checknumber(L, 1);
	double inY = xlua_checknumber(L, 2);
	double inZ = xlua_checknumber(L, 3);
	double outLatitude = {};
	double outLongitude = {};
	double outAltitude = {};

	XPLMLocalToWorld(inX, inY, inZ, &outLatitude, &outLongitude, &outAltitude);

	lua_createtable(L, 0, 3);

	lua_pushstring(L, "outLatitude");
	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");
	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushnumber(L, outAltitude);
	lua_settable(L, -3);

	return 1;
}

void RegEnum_XPLMFontID(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplmFont_Basic");
	lua_pushinteger(L, 18);
	lua_setfield(L, -2, "xplmFont_Proportional");
	lua_setglobal(L, "XPLMFontID");
}

int XLuaDrawString(lua_State* L)
{
	float inColorRGB[3] = {};
	int inXOffset = xlua_checkinteger(L, 2);
	int inYOffset = xlua_checkinteger(L, 3);
	const char * inChar = xlua_checkstring(L, 4);
	std::optional<int> inWordWrapWidth = xlua_checkoptint(L, 5);
	XPLMFontID inFontID = xlua_checkinteger(L, 6);

	int inColorRGB_len = lua_objlen(L, 1);
	if (inColorRGB_len != 3)
	{
		luaL_argerror(L, 1, "Array 'inColorRGB' must have 3 elements.\\n");				// Never returns.
		return{};
	}

	for (int i = 0; i < inColorRGB_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		inColorRGB[i] = xlua_checknumber(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMDrawString(inColorRGB, inXOffset, inYOffset, inChar, (inWordWrapWidth ? &*inWordWrapWidth : nullptr), inFontID);

	return 0;
}

int XLuaDrawNumber(lua_State* L)
{
	float inColorRGB[3] = {};
	int inXOffset = xlua_checkinteger(L, 2);
	int inYOffset = xlua_checkinteger(L, 3);
	double inValue = xlua_checknumber(L, 4);
	int inDigits = xlua_checkinteger(L, 5);
	int inDecimals = xlua_checkinteger(L, 6);
	bool inShowSign = xlua_checkboolean(L, 7);
	XPLMFontID inFontID = xlua_checkinteger(L, 8);

	int inColorRGB_len = lua_objlen(L, 1);
	if (inColorRGB_len != 3)
	{
		luaL_argerror(L, 1, "Array 'inColorRGB' must have 3 elements.\\n");				// Never returns.
		return{};
	}

	for (int i = 0; i < inColorRGB_len; ++i)
	{
		lua_rawgeti(L, 1, i + 1);
		inColorRGB[i] = xlua_checknumber(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMDrawNumber(inColorRGB, inXOffset, inYOffset, inValue, inDigits, inDecimals, inShowSign, inFontID);

	return 0;
}

int XLuaGetFontDimensions(lua_State* L)
{
	XPLMFontID inFontID = xlua_checkinteger(L, 1);
	int outCharWidth = {};
	int outCharHeight = {};
	int outDigitsOnly = {};

	XPLMGetFontDimensions(inFontID, &outCharWidth, &outCharHeight, &outDigitsOnly);

	lua_createtable(L, 0, 3);

	lua_pushstring(L, "outCharWidth");
	lua_pushinteger(L, outCharWidth);
	lua_settable(L, -3);

	lua_pushstring(L, "outCharHeight");
	lua_pushinteger(L, outCharHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "outDigitsOnly");
	lua_pushboolean(L, static_cast<bool>(outDigitsOnly));
	lua_settable(L, -3);

	return 1;
}

int XLuaMeasureString(lua_State* L)
{
	XPLMFontID inFontID = xlua_checkinteger(L, 1);
	const char * inChar = xlua_checkstring(L, 2);
	int inNumChars = xlua_checkinteger(L, 3);

	float res = XPLMMeasureString(inFontID, inChar, inNumChars);
	lua_pushnumber(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
