#ifndef _Glua_XPLMWeather_h_
#define _Glua_XPLMWeather_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMWeather
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMWeather.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);
XPLMWeatherInfoClouds_t XPLMWeatherInfoClouds_t_from_table(lua_State* L, int stackpos);
void XPLMWeatherInfoClouds_t_to_table(lua_State* L, XPLMWeatherInfoClouds_t const& src);
XPLMWeatherInfoWinds_t XPLMWeatherInfoWinds_t_from_table(lua_State* L, int stackpos);
void XPLMWeatherInfoWinds_t_to_table(lua_State* L, XPLMWeatherInfoWinds_t const& src);
XPLMWeatherInfo_t XPLMWeatherInfo_t_from_table(lua_State* L, int stackpos);
void XPLMWeatherInfo_t_to_table(lua_State* L, XPLMWeatherInfo_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);

/*
 * XPLMWeatherInfoWinds_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMWeatherInfoWinds_t XPLMWeatherInfoWinds_t_from_table(lua_State* L, int stackpos)
{
	XPLMWeatherInfoWinds_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "alt_msl");
	if (!lua_isnil(L, -1))
	{
		out.alt_msl = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "speed");
	if (!lua_isnil(L, -1))
	{
		out.speed = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "direction");
	if (!lua_isnil(L, -1))
	{
		out.direction = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "gust_speed");
	if (!lua_isnil(L, -1))
	{
		out.gust_speed = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "shear");
	if (!lua_isnil(L, -1))
	{
		out.shear = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "turbulence");
	if (!lua_isnil(L, -1))
	{
		out.turbulence = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMWeatherInfoWinds_t_to_table(lua_State* L, XPLMWeatherInfoWinds_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "alt_msl");
	lua_pushnumber(L, src.alt_msl);
	lua_settable(L, -3);

	lua_pushstring(L, "speed");
	lua_pushnumber(L, src.speed);
	lua_settable(L, -3);

	lua_pushstring(L, "direction");
	lua_pushnumber(L, src.direction);
	lua_settable(L, -3);

	lua_pushstring(L, "gust_speed");
	lua_pushnumber(L, src.gust_speed);
	lua_settable(L, -3);

	lua_pushstring(L, "shear");
	lua_pushnumber(L, src.shear);
	lua_settable(L, -3);

	lua_pushstring(L, "turbulence");
	lua_pushnumber(L, src.turbulence);
	lua_settable(L, -3);
}

int MakeXPLMWeatherInfoWinds_t(lua_State* L)
{
	XPLMWeatherInfoWinds_t out = {};
	XPLMWeatherInfoWinds_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */
/*
 * XPLMWeatherInfoClouds_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMWeatherInfoClouds_t XPLMWeatherInfoClouds_t_from_table(lua_State* L, int stackpos)
{
	XPLMWeatherInfoClouds_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "cloud_type");
	if (!lua_isnil(L, -1))
	{
		out.cloud_type = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "coverage");
	if (!lua_isnil(L, -1))
	{
		out.coverage = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "alt_top");
	if (!lua_isnil(L, -1))
	{
		out.alt_top = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "alt_base");
	if (!lua_isnil(L, -1))
	{
		out.alt_base = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMWeatherInfoClouds_t_to_table(lua_State* L, XPLMWeatherInfoClouds_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "cloud_type");
	lua_pushnumber(L, src.cloud_type);
	lua_settable(L, -3);

	lua_pushstring(L, "coverage");
	lua_pushnumber(L, src.coverage);
	lua_settable(L, -3);

	lua_pushstring(L, "alt_top");
	lua_pushnumber(L, src.alt_top);
	lua_settable(L, -3);

	lua_pushstring(L, "alt_base");
	lua_pushnumber(L, src.alt_base);
	lua_settable(L, -3);
}

int MakeXPLMWeatherInfoClouds_t(lua_State* L)
{
	XPLMWeatherInfoClouds_t out = {};
	XPLMWeatherInfoClouds_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */
/*
 * XPLMWeatherInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMWeatherInfo_t XPLMWeatherInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMWeatherInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "temperature_alt");
	if (!lua_isnil(L, -1))
	{
		out.temperature_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "dewpoint_alt");
	if (!lua_isnil(L, -1))
	{
		out.dewpoint_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pressure_alt");
	if (!lua_isnil(L, -1))
	{
		out.pressure_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "precip_rate_alt");
	if (!lua_isnil(L, -1))
	{
		out.precip_rate_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wind_dir_alt");
	if (!lua_isnil(L, -1))
	{
		out.wind_dir_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wind_spd_alt");
	if (!lua_isnil(L, -1))
	{
		out.wind_spd_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "turbulence_alt");
	if (!lua_isnil(L, -1))
	{
		out.turbulence_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wave_height");
	if (!lua_isnil(L, -1))
	{
		out.wave_height = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wave_length");
	if (!lua_isnil(L, -1))
	{
		out.wave_length = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wave_dir");
	if (!lua_isnil(L, -1))
	{
		out.wave_dir = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wave_speed");
	if (!lua_isnil(L, -1))
	{
		out.wave_speed = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "visibility");
	if (!lua_isnil(L, -1))
	{
		out.visibility = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "precip_rate");
	if (!lua_isnil(L, -1))
	{
		out.precip_rate = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "thermal_climb");
	if (!lua_isnil(L, -1))
	{
		out.thermal_climb = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pressure_sl");
	if (!lua_isnil(L, -1))
	{
		out.pressure_sl = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "wind_layers");
	for (size_t i = 0; i < 13; ++i)
	{
		lua_rawgeti(L, -1, i + 1);
		if (!lua_isnil(L, -1))
		{
			out.wind_layers[i] = XPLMWeatherInfoWinds_t_from_table(L, -1);
		}
		else
		{
			out.wind_layers[i] = XPLMWeatherInfoWinds_t{};
		}
		lua_pop(L, 1);
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "cloud_layers");
	for (size_t i = 0; i < 3; ++i)
	{
		lua_rawgeti(L, -1, i + 1);
		if (!lua_isnil(L, -1))
		{
			out.cloud_layers[i] = XPLMWeatherInfoClouds_t_from_table(L, -1);
		}
		else
		{
			out.cloud_layers[i] = XPLMWeatherInfoClouds_t{};
		}
		lua_pop(L, 1);
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "temp_layers");
	for (size_t i = 0; i < 13; ++i)
	{
		lua_rawgeti(L, -1, i + 1);
		if (!lua_isnil(L, -1))
		{
			out.temp_layers[i] = static_cast<float>(luaL_checknumber(L, -1));
		}
		else
		{
			out.temp_layers[i] = float{};
		}
		lua_pop(L, 1);
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "dewp_layers");
	for (size_t i = 0; i < 13; ++i)
	{
		lua_rawgeti(L, -1, i + 1);
		if (!lua_isnil(L, -1))
		{
			out.dewp_layers[i] = static_cast<float>(luaL_checknumber(L, -1));
		}
		else
		{
			out.dewp_layers[i] = float{};
		}
		lua_pop(L, 1);
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "troposphere_alt");
	if (!lua_isnil(L, -1))
	{
		out.troposphere_alt = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "troposphere_temp");
	if (!lua_isnil(L, -1))
	{
		out.troposphere_temp = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "age");
	if (!lua_isnil(L, -1))
	{
		out.age = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "radius_nm");
	if (!lua_isnil(L, -1))
	{
		out.radius_nm = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "max_altitude_msl_ft");
	if (!lua_isnil(L, -1))
	{
		out.max_altitude_msl_ft = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMWeatherInfo_t_to_table(lua_State* L, XPLMWeatherInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "temperature_alt");
	lua_pushnumber(L, src.temperature_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "dewpoint_alt");
	lua_pushnumber(L, src.dewpoint_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "pressure_alt");
	lua_pushnumber(L, src.pressure_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "precip_rate_alt");
	lua_pushnumber(L, src.precip_rate_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "wind_dir_alt");
	lua_pushnumber(L, src.wind_dir_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "wind_spd_alt");
	lua_pushnumber(L, src.wind_spd_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "turbulence_alt");
	lua_pushnumber(L, src.turbulence_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "wave_height");
	lua_pushnumber(L, src.wave_height);
	lua_settable(L, -3);

	lua_pushstring(L, "wave_length");
	lua_pushnumber(L, src.wave_length);
	lua_settable(L, -3);

	lua_pushstring(L, "wave_dir");
	lua_pushinteger(L, src.wave_dir);
	lua_settable(L, -3);

	lua_pushstring(L, "wave_speed");
	lua_pushnumber(L, src.wave_speed);
	lua_settable(L, -3);

	lua_pushstring(L, "visibility");
	lua_pushnumber(L, src.visibility);
	lua_settable(L, -3);

	lua_pushstring(L, "precip_rate");
	lua_pushnumber(L, src.precip_rate);
	lua_settable(L, -3);

	lua_pushstring(L, "thermal_climb");
	lua_pushnumber(L, src.thermal_climb);
	lua_settable(L, -3);

	lua_pushstring(L, "pressure_sl");
	lua_pushnumber(L, src.pressure_sl);
	lua_settable(L, -3);

	lua_pushstring(L, "wind_layers");
	lua_newtable(L);
	for (size_t i = 0; i < 13; ++i)
	{
		lua_pushinteger(L, i+1);
		XPLMWeatherInfoWinds_t_to_table(L, src.wind_layers[i]);
		lua_settable(L, -3);
	}
	lua_settable(L, -3);

	lua_pushstring(L, "cloud_layers");
	lua_newtable(L);
	for (size_t i = 0; i < 3; ++i)
	{
		lua_pushinteger(L, i+1);
		XPLMWeatherInfoClouds_t_to_table(L, src.cloud_layers[i]);
		lua_settable(L, -3);
	}
	lua_settable(L, -3);

	lua_pushstring(L, "temp_layers");
	lua_newtable(L);
	for (size_t i = 0; i < 13; ++i)
	{
		lua_pushinteger(L, i+1);
		lua_pushnumber(L, src.temp_layers[i]);
		lua_settable(L, -3);
	}
	lua_settable(L, -3);

	lua_pushstring(L, "dewp_layers");
	lua_newtable(L);
	for (size_t i = 0; i < 13; ++i)
	{
		lua_pushinteger(L, i+1);
		lua_pushnumber(L, src.dewp_layers[i]);
		lua_settable(L, -3);
	}
	lua_settable(L, -3);

	lua_pushstring(L, "troposphere_alt");
	lua_pushnumber(L, src.troposphere_alt);
	lua_settable(L, -3);

	lua_pushstring(L, "troposphere_temp");
	lua_pushnumber(L, src.troposphere_temp);
	lua_settable(L, -3);

	lua_pushstring(L, "age");
	lua_pushnumber(L, src.age);
	lua_settable(L, -3);

	lua_pushstring(L, "radius_nm");
	lua_pushnumber(L, src.radius_nm);
	lua_settable(L, -3);

	lua_pushstring(L, "max_altitude_msl_ft");
	lua_pushnumber(L, src.max_altitude_msl_ft);
	lua_settable(L, -3);
}

int MakeXPLMWeatherInfo_t(lua_State* L)
{
	XPLMWeatherInfo_t out = {};
	out.structSize = sizeof(XPLMWeatherInfo_t);
	XPLMWeatherInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaGetMETARForAirport(lua_State* L)
{
	const char * airport_id = xlua_checkstring(L, 1);
	XPLMFixedString150_t outMETAR = {};

	XPLMGetMETARForAirport(airport_id, &outMETAR);
	XPLMFixedString150_t_to_table(L, outMETAR);

	return 1;
}

int XLuaGetWeatherAtLocation(lua_State* L)
{
	double latitude = xlua_checknumber(L, 1);
	double longitude = xlua_checknumber(L, 2);
	double altitude_m = xlua_checknumber(L, 3);
	XPLMWeatherInfo_t out_info = {};
	out_info.structSize = sizeof(XPLMWeatherInfo_t);

	int res = XPLMGetWeatherAtLocation(latitude, longitude, altitude_m, &out_info);
	lua_pushboolean(L, res);
	XPLMWeatherInfo_t_to_table(L, out_info);

	return 2;
}

int XLuaBeginWeatherUpdate(lua_State* L)
{
	XPLMBeginWeatherUpdate();

	return 0;
}

int XLuaEndWeatherUpdate(lua_State* L)
{
	bool isIncremental = xlua_checkboolean(L, 1);
	bool updateImmediately = xlua_checkboolean(L, 2);

	XPLMEndWeatherUpdate(isIncremental, updateImmediately);

	return 0;
}

int XLuaSetWeatherAtLocation(lua_State* L)
{
	double latitude = xlua_checknumber(L, 1);
	double longitude = xlua_checknumber(L, 2);
	double ground_altitude_msl = xlua_checknumber(L, 3);
	XPLMWeatherInfo_t in_info = XPLMWeatherInfo_t_from_table(L, 4);

	XPLMSetWeatherAtLocation(latitude, longitude, ground_altitude_msl, &in_info);

	return 0;
}

int XLuaEraseWeatherAtLocation(lua_State* L)
{
	double latitude = xlua_checknumber(L, 1);
	double longitude = xlua_checknumber(L, 2);

	XPLMEraseWeatherAtLocation(latitude, longitude);

	return 0;
}

int XLuaSetWeatherAtAirport(lua_State* L)
{
	const char * airport_id = xlua_checkstring(L, 1);
	XPLMWeatherInfo_t in_info = XPLMWeatherInfo_t_from_table(L, 2);

	XPLMSetWeatherAtAirport(airport_id, &in_info);

	return 0;
}

int XLuaEraseWeatherAtAirport(lua_State* L)
{
	const char * airport_id = xlua_checkstring(L, 1);

	XPLMEraseWeatherAtAirport(airport_id);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
