#ifndef _Glua_XPLMCamera_h_
#define _Glua_XPLMCamera_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMCamera
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMCamera.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMCameraPosition_t XPLMCameraPosition_t_from_table(lua_State* L, int stackpos);
void XPLMCameraPosition_t_to_table(lua_State* L, XPLMCameraPosition_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//


void RegEnum_XPLMCameraControlDuration(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_ControlCameraUntilViewChanges");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_ControlCameraForever");
	lua_setglobal(L, "XPLMCameraControlDuration");
}
/*
 * XPLMCameraPosition_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCameraPosition_t XPLMCameraPosition_t_from_table(lua_State* L, int stackpos)
{
	XPLMCameraPosition_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "z");
	if (!lua_isnil(L, -1))
	{
		out.z = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pitch");
	if (!lua_isnil(L, -1))
	{
		out.pitch = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "heading");
	if (!lua_isnil(L, -1))
	{
		out.heading = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "roll");
	if (!lua_isnil(L, -1))
	{
		out.roll = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "zoom");
	if (!lua_isnil(L, -1))
	{
		out.zoom = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCameraPosition_t_to_table(lua_State* L, XPLMCameraPosition_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "z");
	lua_pushnumber(L, src.z);
	lua_settable(L, -3);

	lua_pushstring(L, "pitch");
	lua_pushnumber(L, src.pitch);
	lua_settable(L, -3);

	lua_pushstring(L, "heading");
	lua_pushnumber(L, src.heading);
	lua_settable(L, -3);

	lua_pushstring(L, "roll");
	lua_pushnumber(L, src.roll);
	lua_settable(L, -3);

	lua_pushstring(L, "zoom");
	lua_pushnumber(L, src.zoom);
	lua_settable(L, -3);
}

int MakeXPLMCameraPosition_t(lua_State* L)
{
	XPLMCameraPosition_t out = {};
	XPLMCameraPosition_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

static int cb_XPLMCameraControl_f(XPLMCameraPosition_t * outCameraPosition, int inIsLosingControl, void* inRefcon)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMCameraControl_f");
	if (L)
	{
		XPLMCameraPosition_t_to_table(L, outCameraPosition != nullptr ? *outCameraPosition : XPLMCameraPosition_t{});
		int outCameraPosition_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "rbr", outCameraPosition_ref, static_cast<bool>(inIsLosingControl), inRefcon_cb->get_capture()))
		{
			res = lua_toboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}

		if (outCameraPosition != nullptr)
		{
			lua_rawgeti(L, LUA_REGISTRYINDEX, outCameraPosition_ref);
			*outCameraPosition = XPLMCameraPosition_t_from_table(L, -1);
			lua_pop(L, 1);
		}
		luaL_unref(L, LUA_REGISTRYINDEX, outCameraPosition_ref);
	}

	return res;
}

int XLuaControlCamera(lua_State* L)
{
	XPLMCameraControlDuration inHowLong = xlua_checkinteger(L, 1);

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 3);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 2, false, "XPLMCameraControl_f");

	XPLMControlCamera(inHowLong, cb_XPLMCameraControl_f, cb_capture_0.get());

	return 0;
}

int XLuaDontControlCamera(lua_State* L)
{
	XPLMDontControlCamera();

	return 0;
}

int XLuaIsCameraBeingControlled(lua_State* L)
{
	XPLMCameraControlDuration outCameraControlDuration = {};
	int res = XPLMIsCameraBeingControlled(&outCameraControlDuration);
	lua_pushboolean(L, res);
	lua_pushinteger(L, outCameraControlDuration);

	return 2;
}

int XLuaReadCameraPosition(lua_State* L)
{
	XPLMCameraPosition_t outCameraPosition = {};
	XPLMReadCameraPosition(&outCameraPosition);
	XPLMCameraPosition_t_to_table(L, outCameraPosition);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
