#ifndef _Glua_XPLMMap_h_
#define _Glua_XPLMMap_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMMap
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMMap.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMCreateMapLayer_t XPLMCreateMapLayer_t_from_table(lua_State* L, int stackpos);
void XPLMCreateMapLayer_t_to_table(lua_State* L, XPLMCreateMapLayer_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMMapLayerID* Make_XPLMMapLayerID(lua_State* L, XPLMMapLayerID const& init);
XPLMMapProjectionID* Make_XPLMMapProjectionID(lua_State* L, XPLMMapProjectionID const& init);
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


XPLMMapLayerID* Make_XPLMMapLayerID(lua_State* L, XPLMMapLayerID const& init)
{
	XPLMMapLayerID* ud = static_cast<XPLMMapLayerID*>(lua_newuserdata(L, sizeof(XPLMMapLayerID)));
	memcpy(ud, &init, sizeof(XPLMMapLayerID));

	luaL_getmetatable(L, "_mt_XPLMMapLayerID");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMMapLayerID_Constructor(lua_State* L)
{
	Make_XPLMMapLayerID(L, nullptr);
	return 1;
}

static int _XPLMMapLayerID_compare(lua_State* L)
{
	XPLMMapLayerID const test1 = xlua_checkuserdata<XPLMMapLayerID>(L, 1, "Expected XPLMMapLayerID");
	XPLMMapLayerID const test2 = xlua_checkuserdata<XPLMMapLayerID>(L, 2, "Expected XPLMMapLayerID");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMMapLayerID(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMMapLayerID");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMMapLayerID");
	lua_setfield(L, -2, "__name");

/*	lua_pushcfunction(L, _XPLMMapLayerID_to_string);
	lua_setfield(L, -2, "__tostring");

	lua_pushcfunction(L, _XPLMMapLayerID_compare);
	lua_setfield(L, -2, "__eq");
*/

	lua_register(L, "XPLMMapLayerID", _XPLMMapLayerID_Constructor);

	lua_pop(L, 1);
}

XPLMMapProjectionID* Make_XPLMMapProjectionID(lua_State* L, XPLMMapProjectionID const& init)
{
	XPLMMapProjectionID* ud = static_cast<XPLMMapProjectionID*>(lua_newuserdata(L, sizeof(XPLMMapProjectionID)));
	memcpy(ud, &init, sizeof(XPLMMapProjectionID));

	luaL_getmetatable(L, "_mt_XPLMMapProjectionID");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMMapProjectionID_Constructor(lua_State* L)
{
	Make_XPLMMapProjectionID(L, nullptr);
	return 1;
}

static int _XPLMMapProjectionID_compare(lua_State* L)
{
	XPLMMapProjectionID const test1 = xlua_checkuserdata<XPLMMapProjectionID>(L, 1, "Expected XPLMMapProjectionID");
	XPLMMapProjectionID const test2 = xlua_checkuserdata<XPLMMapProjectionID>(L, 2, "Expected XPLMMapProjectionID");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMMapProjectionID(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMMapProjectionID");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMMapProjectionID");
	lua_setfield(L, -2, "__name");

/*	lua_pushcfunction(L, _XPLMMapProjectionID_to_string);
	lua_setfield(L, -2, "__tostring");

	lua_pushcfunction(L, _XPLMMapProjectionID_compare);
	lua_setfield(L, -2, "__eq");
*/

	lua_register(L, "XPLMMapProjectionID", _XPLMMapProjectionID_Constructor);

	lua_pop(L, 1);
}

static void cb_XPLMMapDrawingCallback_f(XPLMMapLayerID inLayer, const float * inMapBoundsLeftTopRightBottom, float zoomRatio, float mapUnitsPerUserInterfaceUnit, XPLMMapStyle mapStyle, XPLMMapProjectionID projection, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapDrawingCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "u?ddiur", inLayer, inMapBoundsLeftTopRightBottom, zoomRatio, mapUnitsPerUserInterfaceUnit, mapStyle, projection, cb->get_capture()))
		{
		}
	}
}

static void cb_XPLMMapIconDrawingCallback_f(XPLMMapLayerID inLayer, const float * inMapBoundsLeftTopRightBottom, float zoomRatio, float mapUnitsPerUserInterfaceUnit, XPLMMapStyle mapStyle, XPLMMapProjectionID projection, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapIconDrawingCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "u?ddiur", inLayer, inMapBoundsLeftTopRightBottom, zoomRatio, mapUnitsPerUserInterfaceUnit, mapStyle, projection, cb->get_capture()))
		{
		}
	}
}

static void cb_XPLMMapLabelDrawingCallback_f(XPLMMapLayerID inLayer, const float * inMapBoundsLeftTopRightBottom, float zoomRatio, float mapUnitsPerUserInterfaceUnit, XPLMMapStyle mapStyle, XPLMMapProjectionID projection, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapLabelDrawingCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "u?ddiur", inLayer, inMapBoundsLeftTopRightBottom, zoomRatio, mapUnitsPerUserInterfaceUnit, mapStyle, projection, cb->get_capture()))
		{
		}
	}
}

static void cb_XPLMMapPrepareCacheCallback_f(XPLMMapLayerID inLayer, const float * inTotalMapBoundsLeftTopRightBottom, XPLMMapProjectionID projection, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapPrepareCacheCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "u?ur", inLayer, inTotalMapBoundsLeftTopRightBottom, projection, cb->get_capture()))
		{
		}
	}
}

static void cb_XPLMMapWillBeDeletedCallback_f(XPLMMapLayerID inLayer, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapWillBeDeletedCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "ur", inLayer, cb->get_capture()))
		{
		}
	}
}
/*
 * XPLMCreateMapLayer_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCreateMapLayer_t XPLMCreateMapLayer_t_from_table(lua_State* L, int stackpos)
{
	XPLMCreateMapLayer_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, -1, "refcon");
	int refcon_0_regindex = capture_lua_value(L, -1);
	lua_pop(L, 1);
	out.structSize = sizeof(out);
	lua_pop(L, 1);

	lua_getfield(L, -1, "mapToCreateLayerIn");
	if (!lua_isnil(L, -1))
	{
		out.mapToCreateLayerIn = static_cast<const char *>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "layerType");
	if (!lua_isnil(L, -1))
	{
		out.layerType = static_cast<XPLMMapLayerType>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "willBeDeletedCallback");
	 std::shared_ptr<notify_cb_t> cb_capture_0 = wrap_first_lua_func(L, -1, "XPLMMapWillBeDeletedCallback_f", refcon_0_regindex);
	lua_pop(L, 1);

	lua_getfield(L, -1, "prepCacheCallback");
	wrap_next_lua_func(cb_capture_0, -1, "XPLMMapPrepareCacheCallback_f");
	lua_pop(L, 1);

	lua_getfield(L, -1, "drawCallback");
	wrap_next_lua_func(cb_capture_0, -1, "XPLMMapDrawingCallback_f");
	lua_pop(L, 1);

	lua_getfield(L, -1, "iconCallback");
	wrap_next_lua_func(cb_capture_0, -1, "XPLMMapIconDrawingCallback_f");
	lua_pop(L, 1);

	lua_getfield(L, -1, "labelCallback");
	wrap_next_lua_func(cb_capture_0, -1, "XPLMMapLabelDrawingCallback_f");
	lua_pop(L, 1);

	lua_getfield(L, -1, "showUiToggle");
	if (!lua_isnil(L, -1))
	{
		out.showUiToggle = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "layerName");
	if (!lua_isnil(L, -1))
	{
		out.layerName = static_cast<const char *>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "refcon");
	if (!lua_isnil(L, -1))
	{
		out.refcon = static_cast<void*>(xlua_checkuserdata<void*>(L, -1, "Expected userdata<void*>"));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCreateMapLayer_t_to_table(lua_State* L, XPLMCreateMapLayer_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "mapToCreateLayerIn");
	lua_pushstring(L, src.mapToCreateLayerIn);
	lua_settable(L, -3);

	lua_pushstring(L, "layerType");
	lua_pushinteger(L, src.layerType);
	lua_settable(L, -3);

	lua_pushstring(L, "willBeDeletedCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "prepCacheCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "drawCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "iconCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "labelCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "showUiToggle");
	lua_pushinteger(L, src.showUiToggle);
	lua_settable(L, -3);

	lua_pushstring(L, "layerName");
	lua_pushstring(L, src.layerName);
	lua_settable(L, -3);

	lua_pushstring(L, "refcon");
	xlua_pushuserdata<void*>(L, src.refcon);
	lua_settable(L, -3);
}

int MakeXPLMCreateMapLayer_t(lua_State* L)
{
	XPLMCreateMapLayer_t out = {};
	out.structSize = sizeof(XPLMCreateMapLayer_t);
	XPLMCreateMapLayer_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCreateMapLayer(lua_State* L)
{
	XPLMCreateMapLayer_t inParams = XPLMCreateMapLayer_t_from_table(L, 1);

	XPLMMapLayerID res = XPLMCreateMapLayer(&inParams);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMMapLayerID>(L, res);
	}

	return 1;
}

int XLuaDestroyMapLayer(lua_State* L)
{
	XPLMMapLayerID inLayer = {};
	if (lua_isuserdata(L, 1))
	{
		inLayer = xlua_checkuserdata<XPLMMapLayerID>(L, 1, "Expected userdata<XPLMMapLayerID>");
	}

	int res = XPLMDestroyMapLayer(inLayer);
	lua_pushboolean(L, res);

	return 1;
}

static void cb_XPLMMapCreatedCallback_f(const char * mapIdentifier, void* inRefcon)
{
	notify_cb_t const* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMMapCreatedCallback_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "sr", mapIdentifier, cb->get_capture()))
		{
		}
	}
}

int XLuaRegisterMapCreationHook(lua_State* L)
{
	int refcon_regindex = capture_lua_value(L, 2);
	CleanupStoredCallbacks(L, refcon_regindex);

	std::shared_ptr<notify_cb_t> cb_capture_0 = wrap_first_lua_func(L, 1, "XPLMMapCreatedCallback_f", refcon_regindex);

	XPLMRegisterMapCreationHook(cb_XPLMMapCreatedCallback_f, cb_capture_0.get());

	return 0;
}

int XLuaMapExists(lua_State* L)
{
	const char * mapIdentifier = xlua_checkstring(L, 1);

	int res = XPLMMapExists(mapIdentifier);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaDrawMapIconFromSheet(lua_State* L)
{
	XPLMMapLayerID layer = {};
	if (lua_isuserdata(L, 1))
	{
		layer = xlua_checkuserdata<XPLMMapLayerID>(L, 1, "Expected userdata<XPLMMapLayerID>");
	}
	const char * inPngPath = xlua_checkstring(L, 2);
	int s = xlua_checkinteger(L, 3);
	int t = xlua_checkinteger(L, 4);
	int ds = xlua_checkinteger(L, 5);
	int dt = xlua_checkinteger(L, 6);
	float mapX = xlua_checknumber(L, 7);
	float mapY = xlua_checknumber(L, 8);
	XPLMMapOrientation orientation = xlua_checkinteger(L, 9);
	float rotationDegrees = xlua_checknumber(L, 10);
	float mapWidth = xlua_checknumber(L, 11);

	XPLMDrawMapIconFromSheet(layer, inPngPath, s, t, ds, dt, mapX, mapY, orientation, rotationDegrees, mapWidth);

	return 0;
}

int XLuaDrawMapLabel(lua_State* L)
{
	XPLMMapLayerID layer = {};
	if (lua_isuserdata(L, 1))
	{
		layer = xlua_checkuserdata<XPLMMapLayerID>(L, 1, "Expected userdata<XPLMMapLayerID>");
	}
	const char * inText = xlua_checkstring(L, 2);
	float mapX = xlua_checknumber(L, 3);
	float mapY = xlua_checknumber(L, 4);
	XPLMMapOrientation orientation = xlua_checkinteger(L, 5);
	float rotationDegrees = xlua_checknumber(L, 6);

	XPLMDrawMapLabel(layer, inText, mapX, mapY, orientation, rotationDegrees);

	return 0;
}

int XLuaMapProject(lua_State* L)
{
	XPLMMapProjectionID projection = {};
	if (lua_isuserdata(L, 1))
	{
		projection = xlua_checkuserdata<XPLMMapProjectionID>(L, 1, "Expected userdata<XPLMMapProjectionID>");
	}
	double latitude = xlua_checknumber(L, 2);
	double longitude = xlua_checknumber(L, 3);
	float outX;
	float outY;

	XPLMMapProject(projection, latitude, longitude, &outX, &outY);

	lua_createtable(L, 0, 2); // 0 array slots and 2 key-value pairs

	lua_pushstring(L, "outX");

	lua_pushnumber(L, outX);
	lua_settable(L, -3);

	lua_pushstring(L, "outY");

	lua_pushnumber(L, outY);
	lua_settable(L, -3);

	return 1;
}

int XLuaMapUnproject(lua_State* L)
{
	XPLMMapProjectionID projection = {};
	if (lua_isuserdata(L, 1))
	{
		projection = xlua_checkuserdata<XPLMMapProjectionID>(L, 1, "Expected userdata<XPLMMapProjectionID>");
	}
	float mapX = xlua_checknumber(L, 2);
	float mapY = xlua_checknumber(L, 3);
	double outLatitude;
	double outLongitude;

	XPLMMapUnproject(projection, mapX, mapY, &outLatitude, &outLongitude);

	lua_createtable(L, 0, 2); // 0 array slots and 2 key-value pairs

	lua_pushstring(L, "outLatitude");

	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");

	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	return 1;
}

int XLuaMapScaleMeter(lua_State* L)
{
	XPLMMapProjectionID projection = {};
	if (lua_isuserdata(L, 1))
	{
		projection = xlua_checkuserdata<XPLMMapProjectionID>(L, 1, "Expected userdata<XPLMMapProjectionID>");
	}
	float mapX = xlua_checknumber(L, 2);
	float mapY = xlua_checknumber(L, 3);

	float res = XPLMMapScaleMeter(projection, mapX, mapY);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaMapGetNorthHeading(lua_State* L)
{
	XPLMMapProjectionID projection = {};
	if (lua_isuserdata(L, 1))
	{
		projection = xlua_checkuserdata<XPLMMapProjectionID>(L, 1, "Expected userdata<XPLMMapProjectionID>");
	}
	float mapX = xlua_checknumber(L, 2);
	float mapY = xlua_checknumber(L, 3);

	float res = XPLMMapGetNorthHeading(projection, mapX, mapY);
	lua_pushnumber(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
