#ifndef _Glua_XPLMDataAccess_h_
#define _Glua_XPLMDataAccess_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMDataAccess
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMDataAccess.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMDataRefInfo_t XPLMDataRefInfo_t_from_table(lua_State* L, int stackpos);
void XPLMDataRefInfo_t_to_table(lua_State* L, XPLMDataRefInfo_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMDataRef* Make_XPLMDataRef(lua_State* L, XPLMDataRef const& init);
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


XPLMDataRef* Make_XPLMDataRef(lua_State* L, XPLMDataRef const& init)
{
	XPLMDataRef* ud = static_cast<XPLMDataRef*>(lua_newuserdata(L, sizeof(XPLMDataRef)));
	memcpy(ud, &init, sizeof(XPLMDataRef));

	luaL_getmetatable(L, "_mt_XPLMDataRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMDataRef_Constructor(lua_State* L)
{
	Make_XPLMDataRef(L, nullptr);
	return 1;
}

static int _XPLMDataRef_compare(lua_State* L)
{
	XPLMDataRef const test1 = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	XPLMDataRef const test2 = xlua_checkuserdata<XPLMDataRef>(L, 2, "Expected XPLMDataRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMDataRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMDataRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMDataRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMDataRef_tostring
	lua_pushcfunction(L, _XPLMDataRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMDataRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMDataRef", _XPLMDataRef_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMDataRefInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMDataRefInfo_t XPLMDataRefInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMDataRefInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "name");
	if (!lua_isnil(L, -1))
	{
		out.name = static_cast<const char *>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "type");
	if (!lua_isnil(L, -1))
	{
		out.type = static_cast<XPLMDataTypeID>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "writable");
	if (!lua_isnil(L, -1))
	{
		out.writable = static_cast<int>(xlua_checkboolean(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "owner");
	if (!lua_isnil(L, -1))
	{
		out.owner = static_cast<XPLMPluginID>(xlua_checkuserdata<XPLMPluginID>(L, -1, "Expected XPLMPluginID"));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMDataRefInfo_t_to_table(lua_State* L, XPLMDataRefInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "name");
	lua_pushstring(L, src.name);
	lua_settable(L, -3);

	lua_pushstring(L, "type");
	lua_pushinteger(L, src.type);
	lua_settable(L, -3);

	lua_pushstring(L, "writable");
	lua_pushboolean(L, src.writable);
	lua_settable(L, -3);

	lua_pushstring(L, "owner");
	xlua_pushuserdata<XPLMPluginID>(L, src.owner);
	lua_settable(L, -3);
}

int MakeXPLMDataRefInfo_t(lua_State* L)
{
	XPLMDataRefInfo_t out = {};
	out.structSize = sizeof(XPLMDataRefInfo_t);
	XPLMDataRefInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCountDataRefs(lua_State* L)
{
	int res = XPLMCountDataRefs();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDataRefsByIndex(lua_State* L)
{
	int offset = xlua_checkinteger(L, 1);
	int count = xlua_checkinteger(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);
	clear_table(L, 3);

	if (offset < 0)
	{
		luaL_argerror(L, 3, "Table outDataRefs offset (offset) must be at least 0.");				// Never returns.
		return {};
	}

	XPLMDataRef* outDataRefs = (count > 0 ? new XPLMDataRef[count]{} : nullptr);

	XPLMGetDataRefsByIndex(offset, count, outDataRefs);

	if (outDataRefs != nullptr)
	{
		for (size_t i = 0; i < count; ++i)
		{
			xlua_pushuserdata<XPLMDataRef>(L, outDataRefs[i]);
			lua_rawseti(L, 3, i + 1);
		}

		delete[] outDataRefs;
	}

	return 0;
}

int XLuaGetDataRefInfo(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	XPLMDataRefInfo_t outInfo = {};
	outInfo.structSize = sizeof(XPLMDataRefInfo_t);

	XPLMGetDataRefInfo(inDataRef, &outInfo);
	XPLMDataRefInfo_t_to_table(L, outInfo);

	return 1;
}

int XLuaFindDataRef(lua_State* L)
{
	const char * inDataRefName = xlua_checkstring(L, 1);

	XPLMDataRef res = XPLMFindDataRef(inDataRefName);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMDataRef(L, res);
	}

	return 1;
}

int XLuaCanWriteDataRef(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	int res = XPLMCanWriteDataRef(inDataRef);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaIsDataRefGood(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	int res = XPLMIsDataRefGood(inDataRef);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaGetDataRefTypes(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	XPLMDataTypeID res = XPLMGetDataRefTypes(inDataRef);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDatai(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	int res = XPLMGetDatai(inDataRef);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDatai(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	int inValue = xlua_checkinteger(L, 2);

	XPLMSetDatai(inDataRef, inValue);

	return 0;
}

int XLuaGetDataf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	float res = XPLMGetDataf(inDataRef);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaSetDataf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	float inValue = xlua_checknumber(L, 2);

	XPLMSetDataf(inDataRef, inValue);

	return 0;
}

int XLuaGetDatad(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	double res = XPLMGetDatad(inDataRef);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaSetDatad(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	double inValue = xlua_checknumber(L, 2);

	XPLMSetDatad(inDataRef, inValue);

	return 0;
}

int XLuaGetDatavi(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	if (!lua_isnil(L, 2))
	{
		luaL_checktype(L, 2, LUA_TTABLE);
		clear_table(L, 2);
	}

	int inOffset = xlua_checkinteger(L, 3);
	int inMax = xlua_checkinteger(L, 4);
	if (inOffset < 0)
	{
		luaL_argerror(L, 2, "Table outValues offset (inOffset) must be at least 0.");				// Never returns.
		return {};
	}

	int* outValues = (lua_istable(L, 2) && inMax > 0 ? new int[inMax]{} : nullptr);

	int res = XPLMGetDatavi(inDataRef, outValues, inOffset, inMax);
	lua_pushinteger(L, res);

	if (outValues != nullptr)
	{
		for (size_t i = 0; i < inMax; ++i)
		{
			xlua_pushinteger(L, outValues[i]);
			lua_rawseti(L, 2, i + 1);
		}

		delete[] outValues;
	}

	return 1;
}

int XLuaSetDatavi(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	luaL_checktype(L, 2, LUA_TTABLE);

	int inoffset = xlua_checkinteger(L, 3);
	int inCount = xlua_checkinteger(L, 4);
	if (inoffset < 0)
	{
		luaL_argerror(L, 2, "Table inValues offset (inoffset) must be at least 0.");				// Never returns.
		return {};
	}

	int inValues_len = lua_objlen(L, 2);
	inValues_len = std::min(inValues_len, static_cast<int>(inCount));
	int* inValues = new int[inValues_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < inValues_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		inValues[i] = xlua_checkinteger(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMSetDatavi(inDataRef, inValues, inoffset, inCount);

	if (inValues != nullptr)
	{
		delete[] inValues;
	}

	return 0;
}

int XLuaGetDatavf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	if (!lua_isnil(L, 2))
	{
		luaL_checktype(L, 2, LUA_TTABLE);
		clear_table(L, 2);
	}

	int inOffset = xlua_checkinteger(L, 3);
	int inMax = xlua_checkinteger(L, 4);
	if (inOffset < 0)
	{
		luaL_argerror(L, 2, "Table outValues offset (inOffset) must be at least 0.");				// Never returns.
		return {};
	}

	float* outValues = (lua_istable(L, 2) && inMax > 0 ? new float[inMax]{} : nullptr);

	int res = XPLMGetDatavf(inDataRef, outValues, inOffset, inMax);
	lua_pushinteger(L, res);

	if (outValues != nullptr)
	{
		for (size_t i = 0; i < inMax; ++i)
		{
			xlua_pushnumber(L, outValues[i]);
			lua_rawseti(L, 2, i + 1);
		}

		delete[] outValues;
	}

	return 1;
}

int XLuaSetDatavf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	luaL_checktype(L, 2, LUA_TTABLE);

	int inoffset = xlua_checkinteger(L, 3);
	int inCount = xlua_checkinteger(L, 4);
	if (inoffset < 0)
	{
		luaL_argerror(L, 2, "Table inValues offset (inoffset) must be at least 0.");				// Never returns.
		return {};
	}

	int inValues_len = lua_objlen(L, 2);
	inValues_len = std::min(inValues_len, static_cast<int>(inCount));
	float* inValues = new float[inValues_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < inValues_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		inValues[i] = xlua_checknumber(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMSetDatavf(inDataRef, inValues, inoffset, inCount);

	if (inValues != nullptr)
	{
		delete[] inValues;
	}

	return 0;
}

int XLuaGetDatab(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	if (!lua_isnil(L, 2))
	{
		luaL_checktype(L, 2, LUA_TTABLE);
		clear_table(L, 2);
	}

	int inOffset = xlua_checkinteger(L, 3);
	int inMaxBytes = xlua_checkinteger(L, 4);
	if (inOffset < 0)
	{
		luaL_argerror(L, 2, "Table outValue offset (inOffset) must be at least 0.");				// Never returns.
		return {};
	}

	uint8_t* outValue = (lua_istable(L, 2) && inMaxBytes > 0 ? new uint8_t[inMaxBytes]{} : nullptr);

	int res = XPLMGetDatab(inDataRef, outValue, inOffset, inMaxBytes);
	lua_pushinteger(L, res);

	if (outValue != nullptr)
	{
		for (size_t i = 0; i < inMaxBytes; ++i)
		{
			xlua_pushbyte(L, outValue[i]);
			lua_rawseti(L, 2, i + 1);
		}

		delete[] outValue;
	}

	return 1;
}

int XLuaSetDatab(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}
	luaL_checktype(L, 2, LUA_TTABLE);

	int inOffset = xlua_checkinteger(L, 3);
	int inLength = xlua_checkinteger(L, 4);
	if (inOffset < 0)
	{
		luaL_argerror(L, 2, "Table inValue offset (inOffset) must be at least 0.");				// Never returns.
		return {};
	}

	int inValue_len = lua_objlen(L, 2);
	inValue_len = std::min(inValue_len, static_cast<int>(inLength));
	uint8_t* inValue = new uint8_t[inValue_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < inValue_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		inValue[i] = xlua_checkbyte(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMSetDatab(inDataRef, inValue, inOffset, inLength);

	if (inValue != nullptr)
	{
		delete[] inValue;
	}

	return 0;
}

static int cb_XPLMGetDatai_f(void* inRefcon)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDatai_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", inRefcon_cb->get_capture()))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatai_f(void* inRefcon, int inValue)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDatai_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "ri", inRefcon_cb->get_capture(), inValue))
		{
		}
	}
}

static float cb_XPLMGetDataf_f(void* inRefcon)
{
	float res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDataf_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", inRefcon_cb->get_capture()))
		{
			res = luaL_checknumber(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDataf_f(void* inRefcon, float inValue)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDataf_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rd", inRefcon_cb->get_capture(), inValue))
		{
		}
	}
}

static double cb_XPLMGetDatad_f(void* inRefcon)
{
	double res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDatad_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", inRefcon_cb->get_capture()))
		{
			res = luaL_checknumber(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatad_f(void* inRefcon, double inValue)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDatad_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rd", inRefcon_cb->get_capture(), inValue))
		{
		}
	}
}

static int cb_XPLMGetDatavi_f(void* inRefcon, int outValues[], int inOffset, int inMax)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDatavi_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table outValues offset (inOffset) must be at least 0.");				// Never returns.
			return {};
		}

		if (outValues != nullptr)
		{
			lua_createtable(L, inMax, 0);
		}
		else
		{
			lua_pushnil(L);
		}
		int outValues_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "rrii", inRefcon_cb->get_capture(), outValues_ref, inOffset, inMax))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}

		if (outValues != nullptr)
		{
			for (int i = 0; i < inMax; ++i)
			{
				lua_rawgeti(L, outValues_ref, i + 1);
				outValues[i] = xlua_checkinteger(L, -1);
				lua_pop(L, 1);
			}
		}

		luaL_unref(L, LUA_REGISTRYINDEX, outValues_ref);
	}

	return res;
}

static void cb_XPLMSetDatavi_f(void* inRefcon, int inValues[], int inOffset, int inCount)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDatavi_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table inValues offset (inOffset) must be at least 0.");				// Never returns.
			return;
		}

		lua_createtable(L, inCount, 0);
		if (inValues != nullptr)
		{
			for (size_t i = 0; i < inCount; ++i)
			{
				xlua_pushinteger(L, inValues[i]);
				lua_rawseti(L, -2, i + 1);
			}
		}
		int inValues_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rrii", inRefcon_cb->get_capture(), inValues_ref, inOffset, inCount))
		{
		}

		if (inValues != nullptr)
		{
		}

		luaL_unref(L, LUA_REGISTRYINDEX, inValues_ref);
	}
}

static int cb_XPLMGetDatavf_f(void* inRefcon, float outValues[], int inOffset, int inMax)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDatavf_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table outValues offset (inOffset) must be at least 0.");				// Never returns.
			return {};
		}

		if (outValues != nullptr)
		{
			lua_createtable(L, inMax, 0);
		}
		else
		{
			lua_pushnil(L);
		}
		int outValues_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "rrii", inRefcon_cb->get_capture(), outValues_ref, inOffset, inMax))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}

		if (outValues != nullptr)
		{
			for (int i = 0; i < inMax; ++i)
			{
				lua_rawgeti(L, outValues_ref, i + 1);
				outValues[i] = xlua_checknumber(L, -1);
				lua_pop(L, 1);
			}
		}

		luaL_unref(L, LUA_REGISTRYINDEX, outValues_ref);
	}

	return res;
}

static void cb_XPLMSetDatavf_f(void* inRefcon, float inValues[], int inOffset, int inCount)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDatavf_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table inValues offset (inOffset) must be at least 0.");				// Never returns.
			return;
		}

		lua_createtable(L, inCount, 0);
		if (inValues != nullptr)
		{
			for (size_t i = 0; i < inCount; ++i)
			{
				xlua_pushnumber(L, inValues[i]);
				lua_rawseti(L, -2, i + 1);
			}
		}
		int inValues_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rrii", inRefcon_cb->get_capture(), inValues_ref, inOffset, inCount))
		{
		}

		if (inValues != nullptr)
		{
		}

		luaL_unref(L, LUA_REGISTRYINDEX, inValues_ref);
	}
}

static int cb_XPLMGetDatab_f(void* inRefcon, void* outValue, int inOffset, int inMaxLength)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMGetDatab_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table outValue offset (inOffset) must be at least 0.");				// Never returns.
			return {};
		}

		if (outValue != nullptr)
		{
			lua_createtable(L, inMaxLength, 0);
		}
		else
		{
			lua_pushnil(L);
		}
		int outValue_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "rrii", inRefcon_cb->get_capture(), outValue_ref, inOffset, inMaxLength))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}

		if (outValue != nullptr)
		{
			for (int i = 0; i < inMaxLength; ++i)
			{
				lua_rawgeti(L, outValue_ref, i + 1);
				static_cast<uint8_t*>(outValue)[i] = xlua_checkbyte(L, -1);
				lua_pop(L, 1);
			}
		}

		luaL_unref(L, LUA_REGISTRYINDEX, outValue_ref);
	}

	return res;
}

static void cb_XPLMSetDatab_f(void* inRefcon, void* inValue, int inOffset, int inLength)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMSetDatab_f");
	if (L)
	{
		if (inOffset < 0)
		{
			luaL_argerror(L, 2, "Table inValue offset (inOffset) must be at least 0.");				// Never returns.
			return;
		}

		lua_createtable(L, inLength, 0);
		if (inValue != nullptr)
		{
			for (size_t i = 0; i < inLength; ++i)
			{
				xlua_pushbyte(L, static_cast<uint8_t*>(inValue)[i]);
				lua_rawseti(L, -2, i + 1);
			}
		}
		int inValue_ref = luaL_ref(L, LUA_REGISTRYINDEX);

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rrii", inRefcon_cb->get_capture(), inValue_ref, inOffset, inLength))
		{
		}

		if (inValue != nullptr)
		{
		}

		luaL_unref(L, LUA_REGISTRYINDEX, inValue_ref);
	}
}

int XLuaRegisterDataAccessor(lua_State* L)
{
	const char * inDataName = xlua_checkstring(L, 1);
	XPLMDataTypeID inDataType = xlua_checkinteger(L, 2);
	bool inIsWritable = xlua_checkboolean(L, 3);

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 16);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 4, true, "XPLMGetDatai_f");

	std::shared_ptr<notify_cb_t> cb_capture_1 = capture_lua_value(L, 17);
	xlua_persist_userref(L, cb_capture_1);
	wrap_next_lua_func(cb_capture_1, 5, true, "XPLMSetDatai_f");
	wrap_next_lua_func(cb_capture_0, 6, true, "XPLMGetDataf_f");
	wrap_next_lua_func(cb_capture_1, 7, true, "XPLMSetDataf_f");
	wrap_next_lua_func(cb_capture_0, 8, true, "XPLMGetDatad_f");
	wrap_next_lua_func(cb_capture_1, 9, true, "XPLMSetDatad_f");
	wrap_next_lua_func(cb_capture_0, 10, true, "XPLMGetDatavi_f");
	wrap_next_lua_func(cb_capture_1, 11, true, "XPLMSetDatavi_f");
	wrap_next_lua_func(cb_capture_0, 12, true, "XPLMGetDatavf_f");
	wrap_next_lua_func(cb_capture_1, 13, true, "XPLMSetDatavf_f");
	wrap_next_lua_func(cb_capture_0, 14, true, "XPLMGetDatab_f");
	wrap_next_lua_func(cb_capture_1, 15, true, "XPLMSetDatab_f");

	XPLMDataRef res = XPLMRegisterDataAccessor(inDataName, inDataType, inIsWritable, (cb_capture_0 ? cb_XPLMGetDatai_f : nullptr), (cb_capture_1 ? cb_XPLMSetDatai_f : nullptr), (cb_capture_0 ? cb_XPLMGetDataf_f : nullptr), (cb_capture_1 ? cb_XPLMSetDataf_f : nullptr), (cb_capture_0 ? cb_XPLMGetDatad_f : nullptr), (cb_capture_1 ? cb_XPLMSetDatad_f : nullptr), (cb_capture_0 ? cb_XPLMGetDatavi_f : nullptr), (cb_capture_1 ? cb_XPLMSetDatavi_f : nullptr), (cb_capture_0 ? cb_XPLMGetDatavf_f : nullptr), (cb_capture_1 ? cb_XPLMSetDatavf_f : nullptr), (cb_capture_0 ? cb_XPLMGetDatab_f : nullptr), (cb_capture_1 ? cb_XPLMSetDatab_f : nullptr), cb_capture_0.get(), cb_capture_1.get());
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMDataRef(L, res);
	}

	return 1;
}

int XLuaUnregisterDataAccessor(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	}

	XPLMUnregisterDataAccessor(inDataRef);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
