#ifndef _Glua_XPLMSound_h_
#define _Glua_XPLMSound_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMSound
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"
#if defined(XPLM) || defined(SIM)
#include "fmod.hpp"
#endif				// XPLM|SIM
#if defined(XPLM) || defined(SIM)
#include "fmod_studio.hpp"
#endif				// XPLM|SIM


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMSound.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


#ifdef __cplusplus
}
#endif

#endif
