#ifndef _Glua_XPLMDefs_h_
#define _Glua_XPLMDefs_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMDefs
 ***************************************************************************/
#include <optional>


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMDefs.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init)
{
	XPLMPluginID* ud = static_cast<XPLMPluginID*>(lua_newuserdata(L, sizeof(XPLMPluginID)));
	memcpy(ud, &init, sizeof(XPLMPluginID));

	luaL_getmetatable(L, "_mt_XPLMPluginID");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMPluginID_Constructor(lua_State* L)
{
	XPLMPluginID defval = XPLM_NO_PLUGIN_ID;				// TODO: Example only! Do we need a 'defaultvalue' attribute somewhere?
	if (lua_gettop(L) > 0)
	{
		defval = luaL_checkinteger(L, 1);
	}

	Make_XPLMPluginID(L, defval);
	return 1;
}

static int _XPLMPluginID_compare(lua_State* L)
{
	XPLMPluginID const test1 = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected XPLMPluginID");
	XPLMPluginID const test2 = xlua_checkuserdata<XPLMPluginID>(L, 2, "Expected XPLMPluginID");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMPluginID(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMPluginID");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMPluginID");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMPluginID_tostring
	lua_pushcfunction(L, _XPLMPluginID_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMPluginID_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMPluginID", _XPLMPluginID_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMFixedString150_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos)
{
	XPLMFixedString150_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "buffer");
	strncpy(out.buffer, luaL_checkstring(L, -1), 150);
	out.buffer[149] = 0;
	lua_pop(L, 1);
	lua_pop(L, 1);

	return out;
}

void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src)
{
	lua_newtable(L);

	std::string tmp(src.buffer, 150-1);		// Enforce a null terminator.
	lua_pushstring(L, "buffer");
	lua_pushstring(L, tmp.c_str());
	lua_settable(L, -3);
}

int MakeXPLMFixedString150_t(lua_State* L)
{
	XPLMFixedString150_t out = {};
	XPLMFixedString150_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

#ifdef __cplusplus
}
#endif

#endif
