#ifndef _Glua_XPLMInstance_h_
#define _Glua_XPLMInstance_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMInstance
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"
#include "XPLMScenery.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMInstance.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMDrawInfoDouble_t XPLMDrawInfoDouble_t_from_table(lua_State* L, int stackpos);
void XPLMDrawInfoDouble_t_to_table(lua_State* L, XPLMDrawInfoDouble_t const& src);
XPLMDrawInfo_t XPLMDrawInfo_t_from_table(lua_State* L, int stackpos);
void XPLMDrawInfo_t_to_table(lua_State* L, XPLMDrawInfo_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);
XPLMProbeInfo_t XPLMProbeInfo_t_from_table(lua_State* L, int stackpos);
void XPLMProbeInfo_t_to_table(lua_State* L, XPLMProbeInfo_t const& src);

//
// Typedefs
//
XPLMInstanceRef* Make_XPLMInstanceRef(lua_State* L, XPLMInstanceRef const& init);
XPLMObjectRef* Make_XPLMObjectRef(lua_State* L, XPLMObjectRef const& init);
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);
XPLMProbeRef* Make_XPLMProbeRef(lua_State* L, XPLMProbeRef const& init);


XPLMInstanceRef* Make_XPLMInstanceRef(lua_State* L, XPLMInstanceRef const& init)
{
	XPLMInstanceRef* ud = static_cast<XPLMInstanceRef*>(lua_newuserdata(L, sizeof(XPLMInstanceRef)));
	memcpy(ud, &init, sizeof(XPLMInstanceRef));

	luaL_getmetatable(L, "_mt_XPLMInstanceRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMInstanceRef_Constructor(lua_State* L)
{
	Make_XPLMInstanceRef(L, nullptr);
	return 1;
}

static int _XPLMInstanceRef_compare(lua_State* L)
{
	XPLMInstanceRef const test1 = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected XPLMInstanceRef");
	XPLMInstanceRef const test2 = xlua_checkuserdata<XPLMInstanceRef>(L, 2, "Expected XPLMInstanceRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMInstanceRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMInstanceRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMInstanceRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMInstanceRef_tostring
	lua_pushcfunction(L, _XPLMInstanceRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMInstanceRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMInstanceRef", _XPLMInstanceRef_Constructor);

	lua_pop(L, 1);
}

int XLuaCreateInstance(lua_State* L)
{
	XPLMObjectRef obj = {};
	if (lua_isuserdata(L, 1))
	{
		obj = xlua_checkuserdata<XPLMObjectRef>(L, 1, "Expected XPLMObjectRef");
	}
	luaL_checktype(L, 2, LUA_TTABLE);


	int datarefs_len = lua_objlen(L, 2);
	char const** datarefs = new char const*[datarefs_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < datarefs_len; ++i)
	{
		lua_rawgeti(L, 2, i + 1);
		datarefs[i] = xlua_checkstring(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMInstanceRef res = XPLMCreateInstance(obj, datarefs);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMInstanceRef(L, res);
	}

	if (datarefs != nullptr)
	{
		delete[] datarefs;
	}

	return 1;
}

int XLuaInstanceSetAutoShift(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected XPLMInstanceRef");
	}

	XPLMInstanceSetAutoShift(instance);

	return 0;
}

int XLuaDestroyInstance(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected XPLMInstanceRef");
	}

	XPLMDestroyInstance(instance);

	return 0;
}

int XLuaInstanceSetPosition(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected XPLMInstanceRef");
	}
	XPLMDrawInfo_t new_position = XPLMDrawInfo_t_from_table(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);


	int data_len = lua_objlen(L, 3);
	float* data = new float[data_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < data_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		data[i] = xlua_checknumber(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMInstanceSetPosition(instance, &new_position, data);

	if (data != nullptr)
	{
		delete[] data;
	}

	return 0;
}

int XLuaInstanceSetPositionDouble(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected XPLMInstanceRef");
	}
	XPLMDrawInfoDouble_t new_position = XPLMDrawInfoDouble_t_from_table(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);


	int data_len = lua_objlen(L, 3);
	float* data = new float[data_len + 1]{};		// Some APIs expect null-terminated arrays.

	for (int i = 0; i < data_len; ++i)
	{
		lua_rawgeti(L, 3, i + 1);
		data[i] = xlua_checknumber(L, -1);
		lua_pop(L, 1);
	}
	
	XPLMInstanceSetPositionDouble(instance, &new_position, data);

	if (data != nullptr)
	{
		delete[] data;
	}

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
