#ifndef _Glua_XPLMDataAccess_h_
#define _Glua_XPLMDataAccess_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMDataAccess
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMDataAccess.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

XPLMDataRefInfo_t XPLMDataRefInfo_t_from_table(lua_State* L, int stackpos);
void XPLMDataRefInfo_t_to_table(lua_State* L, XPLMDataRefInfo_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

XPLMDataRef* Make_XPLMDataRef(lua_State* L, XPLMDataRef const& init)
{
	XPLMDataRef* ud = static_cast<XPLMDataRef*>(lua_newuserdata(L, sizeof(XPLMDataRef)));
	memcpy(ud, &init, sizeof(XPLMDataRef));

	luaL_getmetatable(L, "_mt_XPLMDataRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMDataRef_Constructor(lua_State* L)
{
	Make_XPLMDataRef(L, nullptr);
	return 1;
}

static int _XPLMDataRef_compare(lua_State* L)
{
	XPLMDataRef const test1 = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected XPLMDataRef");
	XPLMDataRef const test2 = xlua_checkuserdata<XPLMDataRef>(L, 2, "Expected XPLMDataRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMDataRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMDataRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMDataRef");
	lua_setfield(L, -2, "__name");

/*	lua_pushcfunction(L, _XPLMDataRef_to_string);
	lua_setfield(L, -2, "__tostring");

	lua_pushcfunction(L, _XPLMDataRef_compare);
	lua_setfield(L, -2, "__eq");
*/

	lua_register(L, "XPLMDataRef", _XPLMDataRef_Constructor);

	lua_pop(L, 1);
}

int XLuaCountDataRefs(lua_State* L)
{
	int res = XPLMCountDataRefs();
	lua_pushinteger(L, res);

	return 1;
}
/*
 * XPLMDataRefInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMDataRefInfo_t XPLMDataRefInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMDataRefInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);
	lua_pop(L, 1);

	lua_getfield(L, -1, "name");
	if (!lua_isnil(L, -1))
	{
		out.name = static_cast<const char *>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "type");
	if (!lua_isnil(L, -1))
	{
		out.type = static_cast<XPLMDataTypeID>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "writable");
	if (!lua_isnil(L, -1))
	{
		out.writable = static_cast<int>(xlua_checkboolean(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "owner");
	if (!lua_isnil(L, -1))
	{
		out.owner = static_cast<XPLMPluginID>(xlua_checkuserdata<XPLMPluginID>(L, -1, "Expected userdata<XPLMPluginID>"));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMDataRefInfo_t_to_table(lua_State* L, XPLMDataRefInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "name");
	lua_pushstring(L, src.name);
	lua_settable(L, -3);

	lua_pushstring(L, "type");
	lua_pushinteger(L, src.type);
	lua_settable(L, -3);

	lua_pushstring(L, "writable");
	lua_pushinteger(L, src.writable);
	lua_settable(L, -3);

	lua_pushstring(L, "owner");
	xlua_pushuserdata<XPLMPluginID>(L, src.owner);
	lua_settable(L, -3);
}

int MakeXPLMDataRefInfo_t(lua_State* L)
{
	XPLMDataRefInfo_t out = {};
	out.structSize = sizeof(XPLMDataRefInfo_t);
	XPLMDataRefInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaGetDataRefInfo(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	XPLMDataRefInfo_t outInfo;
	outInfo.structSize = sizeof(XPLMDataRefInfo_t);

	XPLMGetDataRefInfo(inDataRef, &outInfo);
	XPLMDataRefInfo_t_to_table(L, outInfo);

	return 1;
}

int XLuaFindDataRef(lua_State* L)
{
	const char * inDataRefName = xlua_checkstring(L, 1);

	XPLMDataRef res = XPLMFindDataRef(inDataRefName);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMDataRef>(L, res);
	}

	return 1;
}

int XLuaCanWriteDataRef(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	int res = XPLMCanWriteDataRef(inDataRef);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaIsDataRefGood(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	int res = XPLMIsDataRefGood(inDataRef);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaGetDataRefTypes(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	XPLMDataTypeID res = XPLMGetDataRefTypes(inDataRef);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDatai(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	int res = XPLMGetDatai(inDataRef);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDatai(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	int inValue = xlua_checkinteger(L, 2);

	XPLMSetDatai(inDataRef, inValue);

	return 0;
}

int XLuaGetDataf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	float res = XPLMGetDataf(inDataRef);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaSetDataf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	float inValue = xlua_checknumber(L, 2);

	XPLMSetDataf(inDataRef, inValue);

	return 0;
}

int XLuaGetDatad(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	double res = XPLMGetDatad(inDataRef);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaSetDatad(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	double inValue = xlua_checknumber(L, 2);

	XPLMSetDatad(inDataRef, inValue);

	return 0;
}

int XLuaGetDatavi(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	int outValues;
	int inOffset = xlua_checkinteger(L, 2);
	int inMax = xlua_checkinteger(L, 3);

	int res = XPLMGetDatavi(inDataRef, &outValues, inOffset, inMax);
	lua_pushinteger(L, res);

	lua_pushinteger(L, outValues);

	return 2;
}

int XLuaGetDatavf(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}
	float outValues;
	int inOffset = xlua_checkinteger(L, 2);
	int inMax = xlua_checkinteger(L, 3);

	int res = XPLMGetDatavf(inDataRef, &outValues, inOffset, inMax);
	lua_pushinteger(L, res);

	lua_pushnumber(L, outValues);

	return 2;
}

static int cb_XPLMGetDatai_f(void* inRefcon)
{
	int res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDatai_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", cb->origRefconRegIndex))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatai_f(void* inRefcon, int inValue)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDatai_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "ri", cb->origRefconRegIndex, inValue))
		{
		}
	}
}

static float cb_XPLMGetDataf_f(void* inRefcon)
{
	float res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDataf_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", cb->origRefconRegIndex))
		{
			res = luaL_checknumber(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDataf_f(void* inRefcon, float inValue)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDataf_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rd", cb->origRefconRegIndex, inValue))
		{
		}
	}
}

static double cb_XPLMGetDatad_f(void* inRefcon)
{
	double res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDatad_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r", cb->origRefconRegIndex))
		{
			res = luaL_checknumber(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatad_f(void* inRefcon, double inValue)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDatad_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "rd", cb->origRefconRegIndex, inValue))
		{
		}
	}
}

static int cb_XPLMGetDatavi_f(void* inRefcon, int * outValues, int inOffset, int inMax)
{
	int res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDatavi_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r?ii", cb->origRefconRegIndex, outValues, inOffset, inMax))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatavi_f(void* inRefcon, int * inValues, int inOffset, int inCount)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDatavi_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r?ii", cb->origRefconRegIndex, inValues, inOffset, inCount))
		{
		}
	}
}

static int cb_XPLMGetDatavf_f(void* inRefcon, float * outValues, int inOffset, int inMax)
{
	int res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDatavf_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "r?ii", cb->origRefconRegIndex, outValues, inOffset, inMax))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatavf_f(void* inRefcon, float * inValues, int inOffset, int inCount)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDatavf_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r?ii", cb->origRefconRegIndex, inValues, inOffset, inCount))
		{
		}
	}
}

static int cb_XPLMGetDatab_f(void* inRefcon, void * outValue, int inOffset, int inMaxLength)
{
	int res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMGetDatab_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "ruii", cb->origRefconRegIndex, outValue, inOffset, inMaxLength))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static void cb_XPLMSetDatab_f(void* inRefcon, void * inValue, int inOffset, int inLength)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMSetDatab_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "ruii", cb->origRefconRegIndex, inValue, inOffset, inLength))
		{
		}
	}
}

int XLuaRegisterDataAccessor(lua_State* L)
{
	const char * inDataName = xlua_checkstring(L, 1);
	XPLMDataTypeID inDataType = xlua_checkinteger(L, 2);
	int inIsWritable = xlua_checkinteger(L, 3);
	int refcon_regindex = capture_lua_value(L, 16);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 4, "XPLMGetDatai_f", refcon_regindex);
	refcon_regindex = capture_lua_value(L, 17);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_1 = wrap_first_lua_func(L, 5, "XPLMSetDatai_f", refcon_regindex);
	wrap_next_lua_func(cb_capture_0, 6, "XPLMGetDataf_f");
	wrap_next_lua_func(cb_capture_1, 7, "XPLMSetDataf_f");
	wrap_next_lua_func(cb_capture_0, 8, "XPLMGetDatad_f");
	wrap_next_lua_func(cb_capture_1, 9, "XPLMSetDatad_f");
	wrap_next_lua_func(cb_capture_0, 10, "XPLMGetDatavi_f");
	wrap_next_lua_func(cb_capture_1, 11, "XPLMSetDatavi_f");
	wrap_next_lua_func(cb_capture_0, 12, "XPLMGetDatavf_f");
	wrap_next_lua_func(cb_capture_1, 13, "XPLMSetDatavf_f");
	wrap_next_lua_func(cb_capture_0, 14, "XPLMGetDatab_f");
	wrap_next_lua_func(cb_capture_1, 15, "XPLMSetDatab_f");

	XPLMDataRef res = XPLMRegisterDataAccessor(inDataName, inDataType, inIsWritable, cb_XPLMGetDatai_f, cb_XPLMSetDatai_f, cb_XPLMGetDataf_f, cb_XPLMSetDataf_f, cb_XPLMGetDatad_f, cb_XPLMSetDatad_f, cb_XPLMGetDatavi_f, cb_XPLMSetDatavi_f, cb_XPLMGetDatavf_f, cb_XPLMSetDatavf_f, cb_XPLMGetDatab_f, cb_XPLMSetDatab_f, cb_capture_0, cb_capture_1);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMDataRef>(L, res);
	}

	return 1;
}

int XLuaUnregisterDataAccessor(lua_State* L)
{
	XPLMDataRef inDataRef = {};
	if (lua_isuserdata(L, 1))
	{
		inDataRef = xlua_checkuserdata<XPLMDataRef>(L, 1, "Expected userdata<XPLMDataRef>");
	}

	XPLMUnregisterDataAccessor(inDataRef);

	return 0;
}

static void cb_XPLMDataChanged_f(void* inRefcon)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMDataChanged_f");
	if (L)
	{
		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r", cb->origRefconRegIndex))
		{
		}
	}
}

int XLuaShareData(lua_State* L)
{
	const char * inDataName = xlua_checkstring(L, 1);
	XPLMDataTypeID inDataType = xlua_checkinteger(L, 2);
	int refcon_regindex = capture_lua_value(L, 4);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 3, "XPLMDataChanged_f", refcon_regindex);

	int res = XPLMShareData(inDataName, inDataType, cb_XPLMDataChanged_f, cb_capture_0);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaUnshareData(lua_State* L)
{
	const char * inDataName = xlua_checkstring(L, 1);
	XPLMDataTypeID inDataType = xlua_checkinteger(L, 2);
	int refcon_regindex = capture_lua_value(L, 4);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 3, "XPLMDataChanged_f", refcon_regindex);

	int res = XPLMUnshareData(inDataName, inDataType, cb_XPLMDataChanged_f, cb_capture_0);
	lua_pushboolean(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
