#ifndef _Glua_XPLMDisplay_h_
#define _Glua_XPLMDisplay_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMDisplay
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMDisplay.h"
#undef XPLM_DEPRECATED

#include "xpfuncs.h"
#include "module.h"
#include "lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMCreateAvionics_t XPLMCreateAvionics_t_from_table(lua_State* L, int stackpos);
void XPLMCreateAvionics_t_to_table(lua_State* L, XPLMCreateAvionics_t const& src);
XPLMCustomizeAvionics_t XPLMCustomizeAvionics_t_from_table(lua_State* L, int stackpos);
void XPLMCustomizeAvionics_t_to_table(lua_State* L, XPLMCustomizeAvionics_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//
XPLMAvionicsID* Make_XPLMAvionicsID(lua_State* L, XPLMAvionicsID const& init);
XPLMHotKeyID* Make_XPLMHotKeyID(lua_State* L, XPLMHotKeyID const& init);
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);


static int cb_XPLMAvionicsCallback_f(XPLMDeviceID inDeviceID, int inIsBefore, void* inRefcon)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsCallback_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "ibr", inDeviceID, static_cast<bool>(inIsBefore), inRefcon_cb->get_capture()))
		{
			res = xlua_checkboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}
	}

	return res;
}

static int cb_XPLMAvionicsMouse_f(int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsMouse_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
		{
			res = xlua_checkboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}
	}

	return res;
}

static int cb_XPLMAvionicsMouseWheel_f(int x, int y, int wheel, int clicks, void* inRefcon)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsMouseWheel_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiiir", x, y, wheel, clicks, inRefcon_cb->get_capture()))
		{
			res = xlua_checkboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}
	}

	return res;
}

static XPLMCursorStatus cb_XPLMAvionicsCursor_f(int x, int y, void* inRefcon)
{
	XPLMCursorStatus res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsCursor_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iir", x, y, inRefcon_cb->get_capture()))
		{
			res = luaL_checkinteger(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}

static int cb_XPLMAvionicsKeyboard_f(char inKey, XPLMKeyFlags inFlags, char inVirtualKey, void* inRefcon, int losingFocus)
{
	int res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsKeyboard_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "sisrb", inKey, inFlags, inVirtualKey, inRefcon_cb->get_capture(), static_cast<bool>(losingFocus)))
		{
			res = xlua_checkboolean(L, -1) ? 1 : 0;
			lua_pop(L, 1);
		}
	}

	return res;
}

XPLMAvionicsID* Make_XPLMAvionicsID(lua_State* L, XPLMAvionicsID const& init)
{
	XPLMAvionicsID* ud = static_cast<XPLMAvionicsID*>(lua_newuserdata(L, sizeof(XPLMAvionicsID)));
	memcpy(ud, &init, sizeof(XPLMAvionicsID));

	luaL_getmetatable(L, "_mt_XPLMAvionicsID");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMAvionicsID_Constructor(lua_State* L)
{
	Make_XPLMAvionicsID(L, nullptr);
	return 1;
}

static int _XPLMAvionicsID_compare(lua_State* L)
{
	XPLMAvionicsID const test1 = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	XPLMAvionicsID const test2 = xlua_checkuserdata<XPLMAvionicsID>(L, 2, "Expected XPLMAvionicsID");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMAvionicsID(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMAvionicsID");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMAvionicsID");
	lua_setfield(L, -2, "__name");

/*	lua_pushcfunction(L, _XPLMAvionicsID_to_string);
	lua_setfield(L, -2, "__tostring");

	lua_pushcfunction(L, _XPLMAvionicsID_compare);
	lua_setfield(L, -2, "__eq");
*/

	lua_register(L, "XPLMAvionicsID", _XPLMAvionicsID_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMCustomizeAvionics_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCustomizeAvionics_t XPLMCustomizeAvionics_t_from_table(lua_State* L, int stackpos)
{
	XPLMCustomizeAvionics_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "refcon");
	std::shared_ptr<notify_cb_t> refcon_cb = capture_lua_value(L, -1);
	lua_pop(L, 1);
	xlua_persist_userref(L, refcon_cb);
	out.refcon = refcon_cb.get();

	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "deviceId");
	if (!lua_isnil(L, -1))
	{
		out.deviceId = static_cast<XPLMDeviceID>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "drawCallbackBefore");
	if (wrap_next_lua_func(refcon_cb, -1, true, "drawCallbackBefore"))
	{
		out.drawCallbackBefore = [](XPLMDeviceID inDeviceID, int inIsBefore, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "drawCallbackBefore");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "ibr", inDeviceID, static_cast<bool>(inIsBefore), inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "drawCallbackAfter");
	if (wrap_next_lua_func(refcon_cb, -1, true, "drawCallbackAfter"))
	{
		out.drawCallbackAfter = [](XPLMDeviceID inDeviceID, int inIsBefore, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "drawCallbackAfter");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "ibr", inDeviceID, static_cast<bool>(inIsBefore), inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelClickCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "bezelClickCallback"))
	{
		out.bezelClickCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelClickCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelRightClickCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "bezelRightClickCallback"))
	{
		out.bezelRightClickCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelRightClickCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelScrollCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "bezelScrollCallback"))
	{
		out.bezelScrollCallback = [](int x, int y, int wheel, int clicks, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelScrollCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiiir", x, y, wheel, clicks, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelCursorCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "bezelCursorCallback"))
	{
		out.bezelCursorCallback = [](int x, int y, void* inRefcon)
		{
			XPLMCursorStatus res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelCursorCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iir", x, y, inRefcon_cb->get_capture()))
				{
					res = luaL_checkinteger(L, -1);
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenTouchCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "screenTouchCallback"))
	{
		out.screenTouchCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenTouchCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenRightTouchCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "screenRightTouchCallback"))
	{
		out.screenRightTouchCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenRightTouchCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenScrollCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "screenScrollCallback"))
	{
		out.screenScrollCallback = [](int x, int y, int wheel, int clicks, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenScrollCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiiir", x, y, wheel, clicks, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenCursorCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "screenCursorCallback"))
	{
		out.screenCursorCallback = [](int x, int y, void* inRefcon)
		{
			XPLMCursorStatus res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenCursorCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iir", x, y, inRefcon_cb->get_capture()))
				{
					res = luaL_checkinteger(L, -1);
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "keyboardCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "XPLMAvionicsKeyboard_f"))
	{
		out.keyboardCallback = cb_XPLMAvionicsKeyboard_f;
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCustomizeAvionics_t_to_table(lua_State* L, XPLMCustomizeAvionics_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "deviceId");
	lua_pushinteger(L, src.deviceId);
	lua_settable(L, -3);

	lua_pushstring(L, "refcon");
	xlua_pushuserdata<void*>(L, src.refcon);
	lua_settable(L, -3);
}

int MakeXPLMCustomizeAvionics_t(lua_State* L)
{
	XPLMCustomizeAvionics_t out = {};
	out.structSize = sizeof(XPLMCustomizeAvionics_t);
	XPLMCustomizeAvionics_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaRegisterAvionicsCallbacksEx(lua_State* L)
{
	XPLMCustomizeAvionics_t inParams = XPLMCustomizeAvionics_t_from_table(L, 1);

	XPLMAvionicsID res = XPLMRegisterAvionicsCallbacksEx(&inParams);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMAvionicsID(L, res);
	}

	return 1;
}

int XLuaGetAvionicsHandle(lua_State* L)
{
	XPLMDeviceID inDeviceID = xlua_checkinteger(L, 1);

	XPLMAvionicsID res = XPLMGetAvionicsHandle(inDeviceID);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMAvionicsID(L, res);
	}

	return 1;
}

int XLuaUnregisterAvionicsCallbacks(lua_State* L)
{
	XPLMAvionicsID inAvionicsId = {};
	if (lua_isuserdata(L, 1))
	{
		inAvionicsId = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	XPLMUnregisterAvionicsCallbacks(inAvionicsId);

	return 0;
}

static void cb_XPLMAvionicsScreenCallback_f(void* inRefcon)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsScreenCallback_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r", inRefcon_cb->get_capture()))
		{
		}
	}
}

static void cb_XPLMAvionicsBezelCallback_f(float inAmbiantR, float inAmbiantG, float inAmbiantB, void* inRefcon)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsBezelCallback_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "dddr", inAmbiantR, inAmbiantG, inAmbiantB, inRefcon_cb->get_capture()))
		{
		}
	}
}

static float cb_XPLMAvionicsBrightness_f(float inRheoValue, float inAmbiantBrightness, float inBusVoltsRatio, void* inRefcon)
{
	float res = {};
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMAvionicsBrightness_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "dddr", inRheoValue, inAmbiantBrightness, inBusVoltsRatio, inRefcon_cb->get_capture()))
		{
			res = luaL_checknumber(L, -1);
			lua_pop(L, 1);
		}
	}

	return res;
}
/*
 * XPLMCreateAvionics_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCreateAvionics_t XPLMCreateAvionics_t_from_table(lua_State* L, int stackpos)
{
	XPLMCreateAvionics_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, stackpos, "refcon");
	std::shared_ptr<notify_cb_t> refcon_cb = capture_lua_value(L, -1);
	lua_pop(L, 1);
	xlua_persist_userref(L, refcon_cb);
	out.refcon = refcon_cb.get();

	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "screenWidth");
	if (!lua_isnil(L, -1))
	{
		out.screenWidth = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenHeight");
	if (!lua_isnil(L, -1))
	{
		out.screenHeight = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelWidth");
	if (!lua_isnil(L, -1))
	{
		out.bezelWidth = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelHeight");
	if (!lua_isnil(L, -1))
	{
		out.bezelHeight = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenOffsetX");
	if (!lua_isnil(L, -1))
	{
		out.screenOffsetX = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenOffsetY");
	if (!lua_isnil(L, -1))
	{
		out.screenOffsetY = static_cast<int>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "drawOnDemand");
	if (!lua_isnil(L, -1))
	{
		out.drawOnDemand = static_cast<int>(xlua_checkboolean(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelDrawCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "XPLMAvionicsBezelCallback_f"))
	{
		out.bezelDrawCallback = cb_XPLMAvionicsBezelCallback_f;
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "drawCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "XPLMAvionicsScreenCallback_f"))
	{
		out.drawCallback = cb_XPLMAvionicsScreenCallback_f;
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelClickCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "bezelClickCallback"))
	{
		out.bezelClickCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelClickCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelRightClickCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "bezelRightClickCallback"))
	{
		out.bezelRightClickCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelRightClickCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelScrollCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "bezelScrollCallback"))
	{
		out.bezelScrollCallback = [](int x, int y, int wheel, int clicks, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelScrollCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiiir", x, y, wheel, clicks, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "bezelCursorCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "bezelCursorCallback"))
	{
		out.bezelCursorCallback = [](int x, int y, void* inRefcon)
		{
			XPLMCursorStatus res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "bezelCursorCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iir", x, y, inRefcon_cb->get_capture()))
				{
					res = luaL_checkinteger(L, -1);
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenTouchCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "screenTouchCallback"))
	{
		out.screenTouchCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenTouchCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenRightTouchCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "screenRightTouchCallback"))
	{
		out.screenRightTouchCallback = [](int x, int y, XPLMMouseStatus inMouse, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenRightTouchCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiir", x, y, inMouse, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenScrollCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "screenScrollCallback"))
	{
		out.screenScrollCallback = [](int x, int y, int wheel, int clicks, void* inRefcon)
		{
			int res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenScrollCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iiiir", x, y, wheel, clicks, inRefcon_cb->get_capture()))
				{
					res = xlua_checkboolean(L, -1) ? 1 : 0;
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "screenCursorCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "screenCursorCallback"))
	{
		out.screenCursorCallback = [](int x, int y, void* inRefcon)
		{
			XPLMCursorStatus res = {};
			notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

			lua_State* L = setup_lua_callback(inRefcon_cb, "screenCursorCallback");
			if (L)
			{

				if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "iir", x, y, inRefcon_cb->get_capture()))
				{
					res = luaL_checkinteger(L, -1);
					lua_pop(L, 1);
				}
			}

			return res;
		};
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "keyboardCallback");
	if (wrap_next_lua_func(refcon_cb, -1, false, "XPLMAvionicsKeyboard_f"))
	{
		out.keyboardCallback = cb_XPLMAvionicsKeyboard_f;
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "brightnessCallback");
	if (wrap_next_lua_func(refcon_cb, -1, true, "XPLMAvionicsBrightness_f"))
	{
		out.brightnessCallback = cb_XPLMAvionicsBrightness_f;
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "deviceID");
	if (!lua_isnil(L, -1))
	{
		out.deviceID = static_cast<char const*>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "deviceName");
	if (!lua_isnil(L, -1))
	{
		out.deviceName = static_cast<char const *>(luaL_checkstring(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCreateAvionics_t_to_table(lua_State* L, XPLMCreateAvionics_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "screenWidth");
	lua_pushinteger(L, src.screenWidth);
	lua_settable(L, -3);

	lua_pushstring(L, "screenHeight");
	lua_pushinteger(L, src.screenHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "bezelWidth");
	lua_pushinteger(L, src.bezelWidth);
	lua_settable(L, -3);

	lua_pushstring(L, "bezelHeight");
	lua_pushinteger(L, src.bezelHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "screenOffsetX");
	lua_pushinteger(L, src.screenOffsetX);
	lua_settable(L, -3);

	lua_pushstring(L, "screenOffsetY");
	lua_pushinteger(L, src.screenOffsetY);
	lua_settable(L, -3);

	lua_pushstring(L, "drawOnDemand");
	lua_pushboolean(L, src.drawOnDemand);
	lua_settable(L, -3);

	lua_pushstring(L, "bezelDrawCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "drawCallback");
	luaL_loadstring(L, "function() end");
	lua_settable(L, -3);

	lua_pushstring(L, "deviceID");
	lua_pushstring(L, src.deviceID);
	lua_settable(L, -3);

	lua_pushstring(L, "deviceName");
	lua_pushstring(L, src.deviceName);
	lua_settable(L, -3);

	lua_pushstring(L, "refcon");
	xlua_pushuserdata<void*>(L, src.refcon);
	lua_settable(L, -3);
}

int MakeXPLMCreateAvionics_t(lua_State* L)
{
	XPLMCreateAvionics_t out = {};
	out.structSize = sizeof(XPLMCreateAvionics_t);
	XPLMCreateAvionics_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCreateAvionicsEx(lua_State* L)
{
	XPLMCreateAvionics_t inParams = XPLMCreateAvionics_t_from_table(L, 1);

	XPLMAvionicsID res = XPLMCreateAvionicsEx(&inParams);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMAvionicsID(L, res);
	}

	return 1;
}

int XLuaDestroyAvionics(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	XPLMDestroyAvionics(inHandle);

	return 0;
}

int XLuaIsAvionicsBound(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	int res = XPLMIsAvionicsBound(inHandle);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaSetAvionicsBrightnessRheo(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	float brightness = xlua_checknumber(L, 2);

	XPLMSetAvionicsBrightnessRheo(inHandle, brightness);

	return 0;
}

int XLuaGetAvionicsBrightnessRheo(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	float res = XPLMGetAvionicsBrightnessRheo(inHandle);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaGetAvionicsBusVoltsRatio(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	float res = XPLMGetAvionicsBusVoltsRatio(inHandle);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaIsCursorOverAvionics(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	int outX = {};
	int outY = {};

	int res = XPLMIsCursorOverAvionics(inHandle, &outX, &outY);
	lua_pushboolean(L, res);

	lua_createtable(L, 0, 2);

	lua_pushstring(L, "outX");
	lua_pushinteger(L, outX);
	lua_settable(L, -3);

	lua_pushstring(L, "outY");
	lua_pushinteger(L, outY);
	lua_settable(L, -3);

	return 2;
}

int XLuaAvionicsNeedsDrawing(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	XPLMAvionicsNeedsDrawing(inHandle);

	return 0;
}

int XLuaSetAvionicsPopupVisible(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	bool inVisible = xlua_checkboolean(L, 2);

	XPLMSetAvionicsPopupVisible(inHandle, inVisible);

	return 0;
}

int XLuaIsAvionicsPopupVisible(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	int res = XPLMIsAvionicsPopupVisible(inHandle);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaPopOutAvionics(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	XPLMPopOutAvionics(inHandle);

	return 0;
}

int XLuaIsAvionicsPoppedOut(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	int res = XPLMIsAvionicsPoppedOut(inHandle);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaTakeAvionicsKeyboardFocus(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	XPLMTakeAvionicsKeyboardFocus(inHandle);

	return 0;
}

int XLuaHasAvionicsKeyboardFocus(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}

	int res = XPLMHasAvionicsKeyboardFocus(inHandle);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaGetAvionicsGeometry(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	int outLeft = {};
	int outTop = {};
	int outRight = {};
	int outBottom = {};

	XPLMGetAvionicsGeometry(inHandle, &outLeft, &outTop, &outRight, &outBottom);

	lua_createtable(L, 0, 4);

	lua_pushstring(L, "outLeft");
	lua_pushinteger(L, outLeft);
	lua_settable(L, -3);

	lua_pushstring(L, "outTop");
	lua_pushinteger(L, outTop);
	lua_settable(L, -3);

	lua_pushstring(L, "outRight");
	lua_pushinteger(L, outRight);
	lua_settable(L, -3);

	lua_pushstring(L, "outBottom");
	lua_pushinteger(L, outBottom);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetAvionicsGeometry(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	int inLeft = xlua_checkinteger(L, 2);
	int inTop = xlua_checkinteger(L, 3);
	int inRight = xlua_checkinteger(L, 4);
	int inBottom = xlua_checkinteger(L, 5);

	XPLMSetAvionicsGeometry(inHandle, inLeft, inTop, inRight, inBottom);

	return 0;
}

int XLuaGetAvionicsGeometryOS(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	int outLeft = {};
	int outTop = {};
	int outRight = {};
	int outBottom = {};

	XPLMGetAvionicsGeometryOS(inHandle, &outLeft, &outTop, &outRight, &outBottom);

	lua_createtable(L, 0, 4);

	lua_pushstring(L, "outLeft");
	lua_pushinteger(L, outLeft);
	lua_settable(L, -3);

	lua_pushstring(L, "outTop");
	lua_pushinteger(L, outTop);
	lua_settable(L, -3);

	lua_pushstring(L, "outRight");
	lua_pushinteger(L, outRight);
	lua_settable(L, -3);

	lua_pushstring(L, "outBottom");
	lua_pushinteger(L, outBottom);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetAvionicsGeometryOS(lua_State* L)
{
	XPLMAvionicsID inHandle = {};
	if (lua_isuserdata(L, 1))
	{
		inHandle = xlua_checkuserdata<XPLMAvionicsID>(L, 1, "Expected XPLMAvionicsID");
	}
	int inLeft = xlua_checkinteger(L, 2);
	int inTop = xlua_checkinteger(L, 3);
	int inRight = xlua_checkinteger(L, 4);
	int inBottom = xlua_checkinteger(L, 5);

	XPLMSetAvionicsGeometryOS(inHandle, inLeft, inTop, inRight, inBottom);

	return 0;
}

static void cb_XPLMHotKey_f(void* inRefcon)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMHotKey_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "r", inRefcon_cb->get_capture()))
		{
		}
	}
}

XPLMHotKeyID* Make_XPLMHotKeyID(lua_State* L, XPLMHotKeyID const& init)
{
	XPLMHotKeyID* ud = static_cast<XPLMHotKeyID*>(lua_newuserdata(L, sizeof(XPLMHotKeyID)));
	memcpy(ud, &init, sizeof(XPLMHotKeyID));

	luaL_getmetatable(L, "_mt_XPLMHotKeyID");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMHotKeyID_Constructor(lua_State* L)
{
	Make_XPLMHotKeyID(L, nullptr);
	return 1;
}

static int _XPLMHotKeyID_compare(lua_State* L)
{
	XPLMHotKeyID const test1 = xlua_checkuserdata<XPLMHotKeyID>(L, 1, "Expected XPLMHotKeyID");
	XPLMHotKeyID const test2 = xlua_checkuserdata<XPLMHotKeyID>(L, 2, "Expected XPLMHotKeyID");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMHotKeyID(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMHotKeyID");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMHotKeyID");
	lua_setfield(L, -2, "__name");

/*	lua_pushcfunction(L, _XPLMHotKeyID_to_string);
	lua_setfield(L, -2, "__tostring");

	lua_pushcfunction(L, _XPLMHotKeyID_compare);
	lua_setfield(L, -2, "__eq");
*/

	lua_register(L, "XPLMHotKeyID", _XPLMHotKeyID_Constructor);

	lua_pop(L, 1);
}

int XLuaRegisterHotKey(lua_State* L)
{
	std::string inVirtualKey_s = luaL_checkstring(L, 1);
	if (inVirtualKey_s.size() != 1)
	{
		luaL_argerror(L, 1, "inVirtualKey must be exactly one character");				// Never returns.
		return 0;
	}
	char inVirtualKey = inVirtualKey_s[0];
	XPLMKeyFlags inFlags = xlua_checkinteger(L, 2);
	const char * inDescription = xlua_checkstring(L, 3);

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 5);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 4, false, "XPLMHotKey_f");

	XPLMHotKeyID res = XPLMRegisterHotKey(inVirtualKey, inFlags, inDescription, cb_XPLMHotKey_f, cb_capture_0.get());
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMHotKeyID(L, res);
	}

	return 1;
}

int XLuaUnregisterHotKey(lua_State* L)
{
	XPLMHotKeyID inHotKey = {};
	if (lua_isuserdata(L, 1))
	{
		inHotKey = xlua_checkuserdata<XPLMHotKeyID>(L, 1, "Expected XPLMHotKeyID");
	}

	XPLMUnregisterHotKey(inHotKey);

	return 0;
}

int XLuaCountHotKeys(lua_State* L)
{
	int res = XPLMCountHotKeys();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetNthHotKey(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);

	XPLMHotKeyID res = XPLMGetNthHotKey(inIndex);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMHotKeyID(L, res);
	}

	return 1;
}

int XLuaGetHotKeyInfo(lua_State* L)
{
	XPLMHotKeyID inHotKey = {};
	if (lua_isuserdata(L, 1))
	{
		inHotKey = xlua_checkuserdata<XPLMHotKeyID>(L, 1, "Expected XPLMHotKeyID");
	}
	char outVirtualKey[1] = {};
	XPLMKeyFlags outFlags = {};
	char outDescription[512] = {};
	XPLMPluginID outPlugin = {};

	XPLMGetHotKeyInfo(inHotKey, outVirtualKey, &outFlags, outDescription, &outPlugin);

	lua_createtable(L, 0, 4);

	lua_pushstring(L, "outVirtualKey");
	lua_pushstring(L, outVirtualKey);
	lua_settable(L, -3);

	lua_pushstring(L, "outFlags");
	lua_pushinteger(L, outFlags);
	lua_settable(L, -3);

	lua_pushstring(L, "outDescription");
	lua_pushstring(L, outDescription);
	lua_settable(L, -3);

	lua_pushstring(L, "outPlugin");
	xlua_pushuserdata<XPLMPluginID>(L, outPlugin);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetHotKeyCombination(lua_State* L)
{
	XPLMHotKeyID inHotKey = {};
	if (lua_isuserdata(L, 1))
	{
		inHotKey = xlua_checkuserdata<XPLMHotKeyID>(L, 1, "Expected XPLMHotKeyID");
	}
	std::string inVirtualKey_s = luaL_checkstring(L, 2);
	if (inVirtualKey_s.size() != 1)
	{
		luaL_argerror(L, 2, "inVirtualKey must be exactly one character");				// Never returns.
		return 0;
	}
	char inVirtualKey = inVirtualKey_s[0];
	XPLMKeyFlags inFlags = xlua_checkinteger(L, 3);

	XPLMSetHotKeyCombination(inHotKey, inVirtualKey, inFlags);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
