#ifndef _Glua_XPLMScenery_h_
#define _Glua_XPLMScenery_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMScenery
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMScenery.h"
#undef XPLM_DEPRECATED

#include "xpfuncs.h"
#include "module.h"
#include "lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMDrawInfoDouble_t XPLMDrawInfoDouble_t_from_table(lua_State* L, int stackpos);
void XPLMDrawInfoDouble_t_to_table(lua_State* L, XPLMDrawInfoDouble_t const& src);
XPLMDrawInfo_t XPLMDrawInfo_t_from_table(lua_State* L, int stackpos);
void XPLMDrawInfo_t_to_table(lua_State* L, XPLMDrawInfo_t const& src);
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);
XPLMProbeInfo_t XPLMProbeInfo_t_from_table(lua_State* L, int stackpos);
void XPLMProbeInfo_t_to_table(lua_State* L, XPLMProbeInfo_t const& src);

//
// Typedefs
//
XPLMObjectRef* Make_XPLMObjectRef(lua_State* L, XPLMObjectRef const& init);
XPLMPluginID* Make_XPLMPluginID(lua_State* L, XPLMPluginID const& init);
XPLMProbeRef* Make_XPLMProbeRef(lua_State* L, XPLMProbeRef const& init);


XPLMProbeRef* Make_XPLMProbeRef(lua_State* L, XPLMProbeRef const& init)
{
	XPLMProbeRef* ud = static_cast<XPLMProbeRef*>(lua_newuserdata(L, sizeof(XPLMProbeRef)));
	memcpy(ud, &init, sizeof(XPLMProbeRef));

	luaL_getmetatable(L, "_mt_XPLMProbeRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMProbeRef_Constructor(lua_State* L)
{
	Make_XPLMProbeRef(L, nullptr);
	return 1;
}

static int _XPLMProbeRef_compare(lua_State* L)
{
	XPLMProbeRef const test1 = xlua_checkuserdata<XPLMProbeRef>(L, 1, "Expected XPLMProbeRef");
	XPLMProbeRef const test2 = xlua_checkuserdata<XPLMProbeRef>(L, 2, "Expected XPLMProbeRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMProbeRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMProbeRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMProbeRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMProbeRef_tostring
	lua_pushcfunction(L, _XPLMProbeRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMProbeRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMProbeRef", _XPLMProbeRef_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMProbeInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMProbeInfo_t XPLMProbeInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMProbeInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "locationX");
	if (!lua_isnil(L, -1))
	{
		out.locationX = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "locationY");
	if (!lua_isnil(L, -1))
	{
		out.locationY = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "locationZ");
	if (!lua_isnil(L, -1))
	{
		out.locationZ = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "normalX");
	if (!lua_isnil(L, -1))
	{
		out.normalX = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "normalY");
	if (!lua_isnil(L, -1))
	{
		out.normalY = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "normalZ");
	if (!lua_isnil(L, -1))
	{
		out.normalZ = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "velocityX");
	if (!lua_isnil(L, -1))
	{
		out.velocityX = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "velocityY");
	if (!lua_isnil(L, -1))
	{
		out.velocityY = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "velocityZ");
	if (!lua_isnil(L, -1))
	{
		out.velocityZ = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "is_wet");
	if (!lua_isnil(L, -1))
	{
		out.is_wet = static_cast<int>(xlua_checkboolean(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMProbeInfo_t_to_table(lua_State* L, XPLMProbeInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "locationX");
	lua_pushnumber(L, src.locationX);
	lua_settable(L, -3);

	lua_pushstring(L, "locationY");
	lua_pushnumber(L, src.locationY);
	lua_settable(L, -3);

	lua_pushstring(L, "locationZ");
	lua_pushnumber(L, src.locationZ);
	lua_settable(L, -3);

	lua_pushstring(L, "normalX");
	lua_pushnumber(L, src.normalX);
	lua_settable(L, -3);

	lua_pushstring(L, "normalY");
	lua_pushnumber(L, src.normalY);
	lua_settable(L, -3);

	lua_pushstring(L, "normalZ");
	lua_pushnumber(L, src.normalZ);
	lua_settable(L, -3);

	lua_pushstring(L, "velocityX");
	lua_pushnumber(L, src.velocityX);
	lua_settable(L, -3);

	lua_pushstring(L, "velocityY");
	lua_pushnumber(L, src.velocityY);
	lua_settable(L, -3);

	lua_pushstring(L, "velocityZ");
	lua_pushnumber(L, src.velocityZ);
	lua_settable(L, -3);

	lua_pushstring(L, "is_wet");
	lua_pushboolean(L, src.is_wet);
	lua_settable(L, -3);
}

int MakeXPLMProbeInfo_t(lua_State* L)
{
	XPLMProbeInfo_t out = {};
	out.structSize = sizeof(XPLMProbeInfo_t);
	XPLMProbeInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaCreateProbe(lua_State* L)
{
	XPLMProbeType inProbeType = xlua_checkinteger(L, 1);

	XPLMProbeRef res = XPLMCreateProbe(inProbeType);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMProbeRef(L, res);
	}

	return 1;
}

int XLuaDestroyProbe(lua_State* L)
{
	XPLMProbeRef inProbe = {};
	if (lua_isuserdata(L, 1))
	{
		inProbe = xlua_checkuserdata<XPLMProbeRef>(L, 1, "Expected XPLMProbeRef");
	}

	XPLMDestroyProbe(inProbe);

	return 0;
}

int XLuaProbeTerrainXYZ(lua_State* L)
{
	XPLMProbeRef inProbe = {};
	if (lua_isuserdata(L, 1))
	{
		inProbe = xlua_checkuserdata<XPLMProbeRef>(L, 1, "Expected XPLMProbeRef");
	}
	float inX = xlua_checknumber(L, 2);
	float inY = xlua_checknumber(L, 3);
	float inZ = xlua_checknumber(L, 4);
	XPLMProbeInfo_t outInfo = XPLMProbeInfo_t_from_table(L, 5);

	XPLMProbeResult res = XPLMProbeTerrainXYZ(inProbe, inX, inY, inZ, &outInfo);
	lua_pushinteger(L, res);
	XPLMProbeInfo_t_to_table(L, outInfo);

	return 2;
}

int XLuaGetMagneticVariation(lua_State* L)
{
	double latitude = xlua_checknumber(L, 1);
	double longitude = xlua_checknumber(L, 2);

	float res = XPLMGetMagneticVariation(latitude, longitude);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaDegTrueToDegMagnetic(lua_State* L)
{
	float headingDegreesTrue = xlua_checknumber(L, 1);

	float res = XPLMDegTrueToDegMagnetic(headingDegreesTrue);
	lua_pushnumber(L, res);

	return 1;
}

int XLuaDegMagneticToDegTrue(lua_State* L)
{
	float headingDegreesMagnetic = xlua_checknumber(L, 1);

	float res = XPLMDegMagneticToDegTrue(headingDegreesMagnetic);
	lua_pushnumber(L, res);

	return 1;
}

XPLMObjectRef* Make_XPLMObjectRef(lua_State* L, XPLMObjectRef const& init)
{
	XPLMObjectRef* ud = static_cast<XPLMObjectRef*>(lua_newuserdata(L, sizeof(XPLMObjectRef)));
	memcpy(ud, &init, sizeof(XPLMObjectRef));

	luaL_getmetatable(L, "_mt_XPLMObjectRef");
	lua_setmetatable(L, -2);

	return ud;
}

static int _XPLMObjectRef_Constructor(lua_State* L)
{
	Make_XPLMObjectRef(L, nullptr);
	return 1;
}

static int _XPLMObjectRef_compare(lua_State* L)
{
	XPLMObjectRef const test1 = xlua_checkuserdata<XPLMObjectRef>(L, 1, "Expected XPLMObjectRef");
	XPLMObjectRef const test2 = xlua_checkuserdata<XPLMObjectRef>(L, 2, "Expected XPLMObjectRef");

	lua_pushboolean(L, test1 == test2);
	return 1;
}

void RegType_XPLMObjectRef(lua_State* L)
{
	luaL_newmetatable(L, "_mt_XPLMObjectRef");
	lua_pushvalue(L, -1);
	lua_setfield(L, -2, "__index");

	lua_pushstring(L, "XPLMObjectRef");
	lua_setfield(L, -2, "__name");

#ifdef HAVE_XPLMObjectRef_tostring
	lua_pushcfunction(L, _XPLMObjectRef_tostring);
	lua_setfield(L, -2, "__tostring");
#endif

	lua_pushcfunction(L, _XPLMObjectRef_compare);
	lua_setfield(L, -2, "__eq");

	lua_register(L, "XPLMObjectRef", _XPLMObjectRef_Constructor);

	lua_pop(L, 1);
}
/*
 * XPLMDrawInfo_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMDrawInfo_t XPLMDrawInfo_t_from_table(lua_State* L, int stackpos)
{
	XPLMDrawInfo_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "z");
	if (!lua_isnil(L, -1))
	{
		out.z = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pitch");
	if (!lua_isnil(L, -1))
	{
		out.pitch = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "heading");
	if (!lua_isnil(L, -1))
	{
		out.heading = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "roll");
	if (!lua_isnil(L, -1))
	{
		out.roll = static_cast<float>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMDrawInfo_t_to_table(lua_State* L, XPLMDrawInfo_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "z");
	lua_pushnumber(L, src.z);
	lua_settable(L, -3);

	lua_pushstring(L, "pitch");
	lua_pushnumber(L, src.pitch);
	lua_settable(L, -3);

	lua_pushstring(L, "heading");
	lua_pushnumber(L, src.heading);
	lua_settable(L, -3);

	lua_pushstring(L, "roll");
	lua_pushnumber(L, src.roll);
	lua_settable(L, -3);
}

int MakeXPLMDrawInfo_t(lua_State* L)
{
	XPLMDrawInfo_t out = {};
	out.structSize = sizeof(XPLMDrawInfo_t);
	XPLMDrawInfo_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */
/*
 * XPLMDrawInfoDouble_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMDrawInfoDouble_t XPLMDrawInfoDouble_t_from_table(lua_State* L, int stackpos)
{
	XPLMDrawInfoDouble_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);
	out.structSize = sizeof(out);

	lua_getfield(L, stackpos, "x");
	if (!lua_isnil(L, -1))
	{
		out.x = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "y");
	if (!lua_isnil(L, -1))
	{
		out.y = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "z");
	if (!lua_isnil(L, -1))
	{
		out.z = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "pitch");
	if (!lua_isnil(L, -1))
	{
		out.pitch = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "heading");
	if (!lua_isnil(L, -1))
	{
		out.heading = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, stackpos, "roll");
	if (!lua_isnil(L, -1))
	{
		out.roll = static_cast<double>(luaL_checknumber(L, -1));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMDrawInfoDouble_t_to_table(lua_State* L, XPLMDrawInfoDouble_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "x");
	lua_pushnumber(L, src.x);
	lua_settable(L, -3);

	lua_pushstring(L, "y");
	lua_pushnumber(L, src.y);
	lua_settable(L, -3);

	lua_pushstring(L, "z");
	lua_pushnumber(L, src.z);
	lua_settable(L, -3);

	lua_pushstring(L, "pitch");
	lua_pushnumber(L, src.pitch);
	lua_settable(L, -3);

	lua_pushstring(L, "heading");
	lua_pushnumber(L, src.heading);
	lua_settable(L, -3);

	lua_pushstring(L, "roll");
	lua_pushnumber(L, src.roll);
	lua_settable(L, -3);
}

int MakeXPLMDrawInfoDouble_t(lua_State* L)
{
	XPLMDrawInfoDouble_t out = {};
	out.structSize = sizeof(XPLMDrawInfoDouble_t);
	XPLMDrawInfoDouble_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

static void cb_XPLMObjectLoaded_f(XPLMObjectRef inObject, void* inRefcon)
{
	notify_cb_t const* inRefcon_cb = static_cast<notify_cb_t*>(inRefcon);

	lua_State* L = setup_lua_callback(inRefcon_cb, "XPLMObjectLoaded_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "ur", inObject, inRefcon_cb->get_capture()))
		{
		}
	}
}

int XLuaLoadObject(lua_State* L)
{
	const char * inPath = xlua_checkstring(L, 1);

	XPLMObjectRef res = XPLMLoadObject(inPath);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		Make_XPLMObjectRef(L, res);
	}

	return 1;
}

int XLuaLoadObjectAsync(lua_State* L)
{
	const char * inPath = xlua_checkstring(L, 1);

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 3);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 2, false, "XPLMObjectLoaded_f");

	XPLMLoadObjectAsync(inPath, cb_XPLMObjectLoaded_f, cb_capture_0.get());

	return 0;
}

int XLuaUnloadObject(lua_State* L)
{
	XPLMObjectRef inObject = {};
	if (lua_isuserdata(L, 1))
	{
		inObject = xlua_checkuserdata<XPLMObjectRef>(L, 1, "Expected XPLMObjectRef");
	}

	XPLMUnloadObject(inObject);

	return 0;
}

static void cb_XPLMLibraryEnumerator_f(const char * inFilePath, void* inRef)
{
	notify_cb_t const* inRef_cb = static_cast<notify_cb_t*>(inRef);

	lua_State* L = setup_lua_callback(inRef_cb, "XPLMLibraryEnumerator_f");
	if (L)
	{

		if (0 == fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "sr", inFilePath, inRef_cb->get_capture()))
		{
		}
	}
}

int XLuaLookupObjects(lua_State* L)
{
	const char * inPath = xlua_checkstring(L, 1);
	float inLatitude = xlua_checknumber(L, 2);
	float inLongitude = xlua_checknumber(L, 3);

	std::shared_ptr<notify_cb_t> cb_capture_0 = capture_lua_value(L, 5);
	xlua_persist_userref(L, cb_capture_0);
	wrap_next_lua_func(cb_capture_0, 4, false, "XPLMLibraryEnumerator_f");

	int res = XPLMLookupObjects(inPath, inLatitude, inLongitude, cb_XPLMLibraryEnumerator_f, cb_capture_0.get());
	lua_pushinteger(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
