#ifndef _Glua_XPLMPlugin_h_
#define _Glua_XPLMPlugin_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMPlugin
 ***************************************************************************/

#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMPlugin.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>


int XLuaGetMyID(lua_State* L)
{
	XPLMPluginID res = XPLMGetMyID();
	xlua_pushuserdata<XPLMPluginID>(L, res);

	return 1;
}

int XLuaCountPlugins(lua_State* L)
{
	int res = XPLMCountPlugins();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetNthPlugin(lua_State* L)
{
	int inIndex = luaL_checkinteger(L, 1);

	XPLMPluginID res = XPLMGetNthPlugin(inIndex);
	xlua_pushuserdata<XPLMPluginID>(L, res);

	return 1;
}

int XLuaFindPluginByPath(lua_State* L)
{
	const char * inPath = luaL_checkstring(L, 1);

	XPLMPluginID res = XPLMFindPluginByPath(inPath);
	xlua_pushuserdata<XPLMPluginID>(L, res);

	return 1;
}

int XLuaFindPluginBySignature(lua_State* L)
{
	const char * inSignature = luaL_checkstring(L, 1);

	XPLMPluginID res = XPLMFindPluginBySignature(inSignature);
	xlua_pushuserdata<XPLMPluginID>(L, res);

	return 1;
}

int XLuaGetPluginInfo(lua_State* L)
{
	XPLMPluginID inPlugin = {};
	if (lua_isuserdata(L, 1))
	{
		inPlugin = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected userdata<XPLMPluginID>");
	}
	char outName[256];
	char outFilePath[256];
	char outSignature[256];
	char outDescription[256];

	XPLMGetPluginInfo(inPlugin, outName, outFilePath, outSignature, outDescription);

	lua_createtable(L, 0, 4); // 0 array slots and 4 key-value pairs

	lua_pushstring(L, "outName");
	lua_pushstring(L, outName);
	lua_settable(L, -3);

	lua_pushstring(L, "outFilePath");
	lua_pushstring(L, outFilePath);
	lua_settable(L, -3);

	lua_pushstring(L, "outSignature");
	lua_pushstring(L, outSignature);
	lua_settable(L, -3);

	lua_pushstring(L, "outDescription");
	lua_pushstring(L, outDescription);
	lua_settable(L, -3);

	return 1;
}

int XLuaIsPluginEnabled(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected userdata<XPLMPluginID>");
	}

	bool res = XPLMIsPluginEnabled(inPluginID);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaEnablePlugin(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected userdata<XPLMPluginID>");
	}

	bool res = XPLMEnablePlugin(inPluginID);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaDisablePlugin(lua_State* L)
{
	XPLMPluginID inPluginID = {};
	if (lua_isuserdata(L, 1))
	{
		inPluginID = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected userdata<XPLMPluginID>");
	}

	XPLMDisablePlugin(inPluginID);

	return 0;
}

int XLuaReloadPlugins(lua_State* L)
{
	XPLMReloadPlugins();

	return 0;
}

int XLuaSendMessageToPlugin(lua_State* L)
{
	XPLMPluginID inPlugin = {};
	if (lua_isuserdata(L, 1))
	{
		inPlugin = xlua_checkuserdata<XPLMPluginID>(L, 1, "Expected userdata<XPLMPluginID>");
	}
	int inMessage = luaL_checkinteger(L, 2);
	void * inParam = {};
	if (lua_isuserdata(L, 3))
	{
		inParam = xlua_checkuserdata<void*>(L, 3, "Expected userdata<void*>");
	}

	XPLMSendMessageToPlugin(inPlugin, inMessage, inParam);

	return 0;
}

static void cb_XPLMFeatureEnumerator_f(const char * inFeature, void * inRef)
{
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRef);
	lua_State* L = setup_lua_callback(cb, "XPLMFeatureEnumerator_f");
	if (L)
	{
		fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), false, "sr", inFeature, cb->origRefconRegIndex);
	}
}

int XLuaHasFeature(lua_State* L)
{
	const char * inFeature = luaL_checkstring(L, 1);

	bool res = XPLMHasFeature(inFeature);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaIsFeatureEnabled(lua_State* L)
{
	const char * inFeature = luaL_checkstring(L, 1);

	bool res = XPLMIsFeatureEnabled(inFeature);
	lua_pushboolean(L, res);

	return 1;
}

int XLuaEnableFeature(lua_State* L)
{
	const char * inFeature = luaL_checkstring(L, 1);
	bool inEnable = xlua_checkboolean(L, 2);

	XPLMEnableFeature(inFeature, inEnable);

	return 0;
}

int XLuaEnumerateFeatures(lua_State* L)
{
	int refcon_regindex = capture_lua_value(L, 2);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 1, "XPLMFeatureEnumerator_f", refcon_regindex);

	XPLMEnumerateFeatures(cb_XPLMFeatureEnumerator_f, cb_capture_0);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
