#ifndef _Glua_XPLMGraphics_h_
#define _Glua_XPLMGraphics_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMGraphics
 ***************************************************************************/

#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMGraphics.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

int XLuaSetGraphicsState(lua_State* L)
{
	bool inEnableFog = xlua_checkboolean(L, 1);
	int inNumberTexUnits = luaL_checkinteger(L, 2);
	bool inEnableLighting = xlua_checkboolean(L, 3);
	bool inEnableAlphaTesting = xlua_checkboolean(L, 4);
	bool inEnableAlphaBlending = xlua_checkboolean(L, 5);
	bool inEnableDepthTesting = xlua_checkboolean(L, 6);
	bool inEnableDepthWriting = xlua_checkboolean(L, 7);

	XPLMSetGraphicsState(inEnableFog, inNumberTexUnits, inEnableLighting, inEnableAlphaTesting, inEnableAlphaBlending, inEnableDepthTesting, inEnableDepthWriting);

	return 0;
}

int XLuaBindTexture2d(lua_State* L)
{
	int inTextureNum = luaL_checkinteger(L, 1);
	int inTextureUnit = luaL_checkinteger(L, 2);

	XPLMBindTexture2d(inTextureNum, inTextureUnit);

	return 0;
}

int XLuaGenerateTextureNumbers(lua_State* L)
{
	int outTextureIDs;
	int inCount = luaL_checkinteger(L, 1);

	XPLMGenerateTextureNumbers(&outTextureIDs, inCount);

	lua_createtable(L, 0, 1); // 0 array slots and 1 key-value pairs

	lua_pushstring(L, "outTextureIDs");
	lua_pushinteger(L, outTextureIDs);
	lua_settable(L, -3);

	return 1;
}

int XLuaGetTexture(lua_State* L)
{
	XPLMTextureID inTexture = luaL_checkinteger(L, 1);

	int res = XPLMGetTexture(inTexture);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaWorldToLocal(lua_State* L)
{
	double inLatitude = luaL_checknumber(L, 1);
	double inLongitude = luaL_checknumber(L, 2);
	double inAltitude = luaL_checknumber(L, 3);
	double outX;
	double outY;
	double outZ;

	XPLMWorldToLocal(inLatitude, inLongitude, inAltitude, &outX, &outY, &outZ);

	lua_createtable(L, 0, 3); // 0 array slots and 3 key-value pairs

	lua_pushstring(L, "outX");
	lua_pushnumber(L, outX);
	lua_settable(L, -3);

	lua_pushstring(L, "outY");
	lua_pushnumber(L, outY);
	lua_settable(L, -3);

	lua_pushstring(L, "outZ");
	lua_pushnumber(L, outZ);
	lua_settable(L, -3);

	return 1;
}

int XLuaLocalToWorld(lua_State* L)
{
	double inX = luaL_checknumber(L, 1);
	double inY = luaL_checknumber(L, 2);
	double inZ = luaL_checknumber(L, 3);
	double outLatitude;
	double outLongitude;
	double outAltitude;

	XPLMLocalToWorld(inX, inY, inZ, &outLatitude, &outLongitude, &outAltitude);

	lua_createtable(L, 0, 3); // 0 array slots and 3 key-value pairs

	lua_pushstring(L, "outLatitude");
	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");
	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushnumber(L, outAltitude);
	lua_settable(L, -3);

	return 1;
}

int XLuaDrawTranslucentDarkBox(lua_State* L)
{
	int inLeft = luaL_checkinteger(L, 1);
	int inTop = luaL_checkinteger(L, 2);
	int inRight = luaL_checkinteger(L, 3);
	int inBottom = luaL_checkinteger(L, 4);

	XPLMDrawTranslucentDarkBox(inLeft, inTop, inRight, inBottom);

	return 0;
}

int XLuaDrawNumber(lua_State* L)
{
	luaL_checktype(L, 1, LUA_TTABLE);
	size_t inColorRGB_len = lua_objlen(L, 1);
	if (inColorRGB_len != 3)
	{
		luaL_argerror(L, 1, "Array 'inColorRGB' must have 3 elements.\n");
		return 0;
	}
	float* inColorRGB = new float[inColorRGB_len];
	for (size_t i = 1; i <= inColorRGB_len; ++i)
	{
		lua_rawgeti(L, 1, i);
		inColorRGB[i] = lua_tonumber(L, -1);
		lua_pop(L, 1);
	}

	int inXOffset = luaL_checkinteger(L, 2);
	int inYOffset = luaL_checkinteger(L, 3);
	double inValue = luaL_checknumber(L, 4);
	int inDigits = luaL_checkinteger(L, 5);
	int inDecimals = luaL_checkinteger(L, 6);
	bool inShowSign = xlua_checkboolean(L, 7);
	XPLMFontID inFontID = luaL_checkinteger(L, 8);

	XPLMDrawNumber(inColorRGB, inXOffset, inYOffset, inValue, inDigits, inDecimals, inShowSign, inFontID);
	delete[] inColorRGB;

	return 0;
}

int XLuaGetFontDimensions(lua_State* L)
{
	XPLMFontID inFontID = luaL_checkinteger(L, 1);
	int outCharWidth;
	int outCharHeight;
	int outDigitsOnly;

	XPLMGetFontDimensions(inFontID, &outCharWidth, &outCharHeight, &outDigitsOnly);

	lua_createtable(L, 0, 3); // 0 array slots and 3 key-value pairs

	lua_pushstring(L, "outCharWidth");
	lua_pushinteger(L, outCharWidth);
	lua_settable(L, -3);

	lua_pushstring(L, "outCharHeight");
	lua_pushinteger(L, outCharHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "outDigitsOnly");
	lua_pushinteger(L, outDigitsOnly);
	lua_settable(L, -3);

	return 1;
}

int XLuaMeasureString(lua_State* L)
{
	XPLMFontID inFontID = luaL_checkinteger(L, 1);
	const char * inChar = luaL_checkstring(L, 2);
	int inNumChars = luaL_checkinteger(L, 3);

	float res = XPLMMeasureString(inFontID, inChar, inNumChars);
	lua_pushnumber(L, res);

	return 1;
}

#ifdef __cplusplus
}
#endif

#endif
