#ifndef _Glua_XPLMInstance_h_
#define _Glua_XPLMInstance_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMInstance
 ***************************************************************************/

#include "XPLMDefs.h"
#include "XPLMScenery.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMInstance.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

extern XPLMDrawInfoDouble_t XPLMDrawInfoDouble_t_from_table(lua_State* L, int stackpos);
extern void XPLMDrawInfoDouble_t_to_table(lua_State* L, XPLMDrawInfoDouble_t const& src);
extern XPLMDrawInfo_t XPLMDrawInfo_t_from_table(lua_State* L, int stackpos);
extern void XPLMDrawInfo_t_to_table(lua_State* L, XPLMDrawInfo_t const& src);
extern XPLMProbeInfo_t XPLMProbeInfo_t_from_table(lua_State* L, int stackpos);
extern void XPLMProbeInfo_t_to_table(lua_State* L, XPLMProbeInfo_t const& src);

int XLuaInstanceSetAutoShift(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected userdata<XPLMInstanceRef>");
	}

	XPLMInstanceSetAutoShift(instance);

	return 0;
}

int XLuaDestroyInstance(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected userdata<XPLMInstanceRef>");
	}

	XPLMDestroyInstance(instance);

	return 0;
}

int XLuaInstanceSetPosition(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected userdata<XPLMInstanceRef>");
	}
	XPLMDrawInfo_t new_position = XPLMDrawInfo_t_from_table(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);
	size_t data_len = lua_objlen(L, 3);
	if (data_len == 0)
	{
		luaL_argerror(L, 3, "Array 'data' must have at least one element.\n");
		return 0;
	}
	float* data = new float[data_len];
	for (size_t i = 1; i <= data_len; ++i)
	{
		lua_rawgeti(L, 3, i);
		data[i] = lua_tonumber(L, -1);
		lua_pop(L, 1);
	}


	XPLMInstanceSetPosition(instance, &new_position, data);
	delete[] data;

	return 0;
}

int XLuaInstanceSetPositionDouble(lua_State* L)
{
	XPLMInstanceRef instance = {};
	if (lua_isuserdata(L, 1))
	{
		instance = xlua_checkuserdata<XPLMInstanceRef>(L, 1, "Expected userdata<XPLMInstanceRef>");
	}
	XPLMDrawInfoDouble_t new_position = XPLMDrawInfoDouble_t_from_table(L, 2);
	luaL_checktype(L, 3, LUA_TTABLE);
	size_t data_len = lua_objlen(L, 3);
	if (data_len == 0)
	{
		luaL_argerror(L, 3, "Array 'data' must have at least one element.\n");
		return 0;
	}
	float* data = new float[data_len];
	for (size_t i = 1; i <= data_len; ++i)
	{
		lua_rawgeti(L, 3, i);
		data[i] = lua_tonumber(L, -1);
		lua_pop(L, 1);
	}


	XPLMInstanceSetPositionDouble(instance, &new_position, data);
	delete[] data;

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
