#ifndef _Glua_XPLMProcessing_h_
#define _Glua_XPLMProcessing_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMProcessing
 ***************************************************************************/

#include "XPLMDefs.h"

// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#define XPLM_DEPRECATED
#include "XPLMProcessing.h"
#undef XPLM_DEPRECATED

#include "../xpfuncs.h"
#include "../module.h"
#include "../lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

extern XPLMCreateFlightLoop_t XPLMCreateFlightLoop_t_from_table(lua_State* L, int stackpos);
extern void XPLMCreateFlightLoop_t_to_table(lua_State* L, XPLMCreateFlightLoop_t const& src);

static float cb_XPLMFlightLoop_f(float inElapsedSinceLastCall, float inElapsedTimeSinceLastFlightLoop, int inCounter, void * inRefcon)
{
	float res = {};
	notify_cb_t* cb = static_cast<notify_cb_t*>(inRefcon);
	lua_State* L = setup_lua_callback(cb, "XPLMFlightLoop_f");
	if (L)
	{
		fmt_pcall_stdvars(L, module::debug_proc_from_interp(L), true, "ffir", inElapsedSinceLastCall, inElapsedTimeSinceLastFlightLoop, inCounter, cb->origRefconRegIndex);
		res = luaL_checknumber(L, 1);
		lua_pop(L, 1);
	}

	return res;
}
/*
 * XPLMCreateFlightLoop_t
 * 
 * Creation and transfer between C struct and Lua table
 *
 */

XPLMCreateFlightLoop_t XPLMCreateFlightLoop_t_from_table(lua_State* L, int stackpos)
{
	XPLMCreateFlightLoop_t out = {};

	luaL_checktype(L, stackpos, LUA_TTABLE);

	lua_getfield(L, -1, "refcon");
	int refcon_0_regindex = capture_lua_value(L, -1);
	lua_pop(L, 1);
	out.structSize = sizeof(out);
	lua_pop(L, 1);

	lua_getfield(L, -1, "phase");
	if (lua_isnil(L, -1))
	{
		out.phase = static_cast<XPLMFlightLoopPhaseType>(luaL_checkinteger(L, -1));
	}
	lua_pop(L, 1);

	lua_getfield(L, -1, "callbackFunc");
	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, -1, "XPLMFlightLoop_f", refcon_0_regindex);
	lua_pop(L, 1);

	lua_getfield(L, -1, "refcon");
	if (lua_isnil(L, -1))
	{
		out.refcon = static_cast<void *>(xlua_checkuserdata<void*>(L, -1, "Expected userdata<void*>"));
	}
	lua_pop(L, 1);

	return out;
}

void XPLMCreateFlightLoop_t_to_table(lua_State* L, XPLMCreateFlightLoop_t const& src)
{
	lua_newtable(L);

	lua_pushstring(L, "phase");
	lua_pushinteger(L, src.phase);
	lua_settable(L, -3);

	lua_pushstring(L, "refcon");
	xlua_pushuserdata<void*>(L, src.refcon);
	lua_settable(L, -3);
}

int MakeXPLMCreateFlightLoop_t(lua_State* L)
{
	XPLMCreateFlightLoop_t out = {};
	out.structSize = sizeof(XPLMCreateFlightLoop_t);
	XPLMCreateFlightLoop_t_to_table(L, out);
	return 1;
}
/*
 * END Creation and transfer between C struct and Lua table
 *
 */

int XLuaGetElapsedTime(lua_State* L)
{
	float res = XPLMGetElapsedTime();
	lua_pushnumber(L, res);

	return 1;
}

int XLuaGetCycleNumber(lua_State* L)
{
	int res = XPLMGetCycleNumber();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaRegisterFlightLoopCallback(lua_State* L)
{
	int refcon_regindex = capture_lua_value(L, 3);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 1, "XPLMFlightLoop_f", refcon_regindex);
	float inInterval = luaL_checknumber(L, 2);

	XPLMRegisterFlightLoopCallback(cb_XPLMFlightLoop_f, inInterval, cb_capture_0);

	return 0;
}

int XLuaUnregisterFlightLoopCallback(lua_State* L)
{
	int refcon_regindex = capture_lua_value(L, 2);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 1, "XPLMFlightLoop_f", refcon_regindex);

	XPLMUnregisterFlightLoopCallback(cb_XPLMFlightLoop_f, cb_capture_0);

	return 0;
}

int XLuaSetFlightLoopCallbackInterval(lua_State* L)
{
	int refcon_regindex = capture_lua_value(L, 4);
	CleanupStoredCallbacks(L, refcon_regindex);

	notify_cb_t* cb_capture_0 = wrap_first_lua_func(L, 1, "XPLMFlightLoop_f", refcon_regindex);
	float inInterval = luaL_checknumber(L, 2);
	bool inRelativeToNow = xlua_checkboolean(L, 3);

	XPLMSetFlightLoopCallbackInterval(cb_XPLMFlightLoop_f, inInterval, inRelativeToNow, cb_capture_0);

	return 0;
}

int XLuaCreateFlightLoop(lua_State* L)
{
	XPLMCreateFlightLoop_t inParams = XPLMCreateFlightLoop_t_from_table(L, 1);

	XPLMFlightLoopID res = XPLMCreateFlightLoop(&inParams);
	if (res == nullptr)
	{
		lua_pushnil(L);
	}
	else
	{
		xlua_pushuserdata<XPLMFlightLoopID>(L, res);
	}

	return 1;
}

int XLuaDestroyFlightLoop(lua_State* L)
{
	XPLMFlightLoopID inFlightLoopID = {};
	if (lua_isuserdata(L, 1))
	{
		inFlightLoopID = xlua_checkuserdata<XPLMFlightLoopID>(L, 1, "Expected userdata<XPLMFlightLoopID>");
	}

	XPLMDestroyFlightLoop(inFlightLoopID);

	return 0;
}

int XLuaScheduleFlightLoop(lua_State* L)
{
	XPLMFlightLoopID inFlightLoopID = {};
	if (lua_isuserdata(L, 1))
	{
		inFlightLoopID = xlua_checkuserdata<XPLMFlightLoopID>(L, 1, "Expected userdata<XPLMFlightLoopID>");
	}
	float inInterval = luaL_checknumber(L, 2);
	bool inRelativeToNow = xlua_checkboolean(L, 3);

	XPLMScheduleFlightLoop(inFlightLoopID, inInterval, inRelativeToNow);

	return 0;
}

#ifdef __cplusplus
}
#endif

#endif
