#ifndef _Glua_XPLMNavigation_h_
#define _Glua_XPLMNavigation_h_

/*
 * This file is auto-generated by header_parser, part of the SDK. Do not
 * hand-edit!
 *
 */

/***************************************************************************
 * XPLMNavigation
 ***************************************************************************/
#include <optional>
#include "XPLMDefs.h"


// We need the XPLM_DEPRECATED marker because Lua is interpreted - old Lua scripts will always use the latest SDK.
#if MOBILE
	#define XPLM_DEPRECATED
#endif
#include "XPLMNavigation.h"
// XPLMUtilities.h supplies XPLMReturnString, which the codegen emits inside
// every const-char*-returning callback wrapper to round-trip through the
// host-managed return slot.
#include "XPLMUtilities.h"
#if MOBILE
	#undef XPLM_DEPRECATED
#endif

#include "shared_xpfuncs.h"
#include "module.h"
#include "shared_lua_helpers.h"

extern "C" {

#include <lua.h>
#include <lauxlib.h>

//
// Struct C/Lua conversion helpers
//
XPLMFixedString150_t XPLMFixedString150_t_from_table(lua_State* L, int stackpos);
void XPLMFixedString150_t_to_table(lua_State* L, XPLMFixedString150_t const& src);

//
// Typedefs
//


void RegEnum_XPLMNavType(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_Nav_Unknown");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_Nav_Airport");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_Nav_NDB");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "xplm_Nav_VOR");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "xplm_Nav_ILS");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "xplm_Nav_Localizer");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "xplm_Nav_GlideSlope");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "xplm_Nav_OuterMarker");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "xplm_Nav_MiddleMarker");
	lua_pushinteger(L, 256);
	lua_setfield(L, -2, "xplm_Nav_InnerMarker");
	lua_pushinteger(L, 512);
	lua_setfield(L, -2, "xplm_Nav_Fix");
	lua_pushinteger(L, 1024);
	lua_setfield(L, -2, "xplm_Nav_DME");
	lua_pushinteger(L, 2048);
	lua_setfield(L, -2, "xplm_Nav_LatLon");
	lua_pushinteger(L, 4096);
	lua_setfield(L, -2, "xplm_Nav_TACAN");
	lua_setglobal(L, "XPLMNavType");
}

int XLuaGetFirstNavAid(lua_State* L)
{
	XPLMNavRef res = XPLMGetFirstNavAid();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetNextNavAid(lua_State* L)
{
	XPLMNavRef inNavAidRef = xlua_checkinteger(L, 1);

	XPLMNavRef res = XPLMGetNextNavAid(inNavAidRef);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFindFirstNavAidOfType(lua_State* L)
{
	XPLMNavType inType = xlua_checkinteger(L, 1);

	XPLMNavRef res = XPLMFindFirstNavAidOfType(inType);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFindLastNavAidOfType(lua_State* L)
{
	XPLMNavType inType = xlua_checkinteger(L, 1);

	XPLMNavRef res = XPLMFindLastNavAidOfType(inType);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaFindNavAid(lua_State* L)
{
	std::optional<std::string> inNameFragment = xlua_checkoptstring(L, 1);
	std::optional<std::string> inIDFragment = xlua_checkoptstring(L, 2);
	std::optional<float> inLat = xlua_checkoptfloat(L, 3);
	std::optional<float> inLon = xlua_checkoptfloat(L, 4);
	std::optional<int> inFrequency = xlua_checkoptint(L, 5);
	XPLMNavType inType = xlua_checkinteger(L, 6);

	XPLMNavRef res = XPLMFindNavAid((inNameFragment ? inNameFragment->c_str() : nullptr), (inIDFragment ? inIDFragment->c_str() : nullptr), (inLat ? &*inLat : nullptr), (inLon ? &*inLon : nullptr), (inFrequency ? &*inFrequency : nullptr), inType);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetNavAidInfo(lua_State* L)
{
	XPLMNavRef inRef = xlua_checkinteger(L, 1);
	XPLMNavType outType = {};
	float outLatitude = {};
	float outLongitude = {};
	float outHeight = {};
	int outFrequency = {};
	float outHeading = {};
	char outID[32] = {};
	char outName[256] = {};
	char outReg[1] = {};

	XPLMGetNavAidInfo(inRef, &outType, &outLatitude, &outLongitude, &outHeight, &outFrequency, &outHeading, outID, outName, outReg);

	lua_createtable(L, 0, 9);

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outLatitude");
	lua_pushnumber(L, outLatitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLongitude");
	lua_pushnumber(L, outLongitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outHeight");
	lua_pushnumber(L, outHeight);
	lua_settable(L, -3);

	lua_pushstring(L, "outFrequency");
	lua_pushinteger(L, outFrequency);
	lua_settable(L, -3);

	lua_pushstring(L, "outHeading");
	lua_pushnumber(L, outHeading);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outName");
	lua_pushstring(L, outName);
	lua_settable(L, -3);

	lua_pushstring(L, "outReg");
	lua_pushstring(L, outReg);
	lua_settable(L, -3);

	return 1;
}

int XLuaCountFMSEntries(lua_State* L)
{
	int res = XPLMCountFMSEntries();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDisplayedFMSEntry(lua_State* L)
{
	int res = XPLMGetDisplayedFMSEntry();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDestinationFMSEntry(lua_State* L)
{
	int res = XPLMGetDestinationFMSEntry();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDisplayedFMSEntry(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);

	XPLMSetDisplayedFMSEntry(inIndex);

	return 0;
}

int XLuaSetDestinationFMSEntry(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);

	XPLMSetDestinationFMSEntry(inIndex);

	return 0;
}

int XLuaGetFMSEntryInfo(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	XPLMNavType outType = {};
	char outID[256] = {};
	XPLMNavRef outRef = {};
	int outAltitude = {};
	float outLat = {};
	float outLon = {};

	XPLMGetFMSEntryInfo(inIndex, &outType, outID, &outRef, &outAltitude, &outLat, &outLon);

	lua_createtable(L, 0, 6);

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outRef");
	lua_pushinteger(L, outRef);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushinteger(L, outAltitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLat");
	lua_pushnumber(L, outLat);
	lua_settable(L, -3);

	lua_pushstring(L, "outLon");
	lua_pushnumber(L, outLon);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetFMSEntryInfo(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	XPLMNavRef inRef = xlua_checkinteger(L, 2);
	int inAltitudeFt = xlua_checkinteger(L, 3);

	XPLMSetFMSEntryInfo(inIndex, inRef, inAltitudeFt);

	return 0;
}

int XLuaSetFMSEntryLatLon(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);
	float inLat = xlua_checknumber(L, 2);
	float inLon = xlua_checknumber(L, 3);
	int inAltitudeFt = xlua_checkinteger(L, 4);

	XPLMSetFMSEntryLatLon(inIndex, inLat, inLon, inAltitudeFt);

	return 0;
}

int XLuaClearFMSEntry(lua_State* L)
{
	int inIndex = xlua_checkinteger(L, 1);

	XPLMClearFMSEntry(inIndex);

	return 0;
}

void RegEnum_XPLMNavFlightPlan(lua_State* L)
{
	lua_newtable(L);
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "xplm_Fpl_Pilot_Primary");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "xplm_Fpl_CoPilot_Primary");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "xplm_Fpl_Pilot_Approach");
	lua_pushinteger(L, 3);
	lua_setfield(L, -2, "xplm_Fpl_CoPilot_Approach");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "xplm_Fpl_Pilot_Temporary");
	lua_pushinteger(L, 5);
	lua_setfield(L, -2, "xplm_Fpl_CoPilot_Temporary");
	lua_setglobal(L, "XPLMNavFlightPlan");
}

int XLuaCountFMSFlightPlanEntries(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);

	int res = XPLMCountFMSFlightPlanEntries(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDisplayedFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);

	int res = XPLMGetDisplayedFMSFlightPlanEntry(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetDestinationFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);

	int res = XPLMGetDestinationFMSFlightPlanEntry(inFlightPlan);
	lua_pushinteger(L, res);

	return 1;
}

int XLuaSetDisplayedFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);

	XPLMSetDisplayedFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaSetDestinationFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);

	XPLMSetDestinationFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaSetDirectToFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);

	XPLMSetDirectToFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaGetFMSFlightPlanEntryInfo(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);
	XPLMNavType outType = {};
	char outID[256] = {};
	XPLMNavRef outRef = {};
	int outAltitude = {};
	float outLat = {};
	float outLon = {};

	XPLMGetFMSFlightPlanEntryInfo(inFlightPlan, inIndex, &outType, outID, &outRef, &outAltitude, &outLat, &outLon);

	lua_createtable(L, 0, 6);

	lua_pushstring(L, "outType");
	lua_pushinteger(L, outType);
	lua_settable(L, -3);

	lua_pushstring(L, "outID");
	lua_pushstring(L, outID);
	lua_settable(L, -3);

	lua_pushstring(L, "outRef");
	lua_pushinteger(L, outRef);
	lua_settable(L, -3);

	lua_pushstring(L, "outAltitude");
	lua_pushinteger(L, outAltitude);
	lua_settable(L, -3);

	lua_pushstring(L, "outLat");
	lua_pushnumber(L, outLat);
	lua_settable(L, -3);

	lua_pushstring(L, "outLon");
	lua_pushnumber(L, outLon);
	lua_settable(L, -3);

	return 1;
}

int XLuaSetFMSFlightPlanEntryInfo(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);
	XPLMNavRef inRef = xlua_checkinteger(L, 3);
	int inAltitudeFt = xlua_checkinteger(L, 4);

	XPLMSetFMSFlightPlanEntryInfo(inFlightPlan, inIndex, inRef, inAltitudeFt);

	return 0;
}

int XLuaSetFMSFlightPlanEntryLatLon(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);
	float inLat = xlua_checknumber(L, 3);
	float inLon = xlua_checknumber(L, 4);
	int inAltitudeFt = xlua_checkinteger(L, 5);

	XPLMSetFMSFlightPlanEntryLatLon(inFlightPlan, inIndex, inLat, inLon, inAltitudeFt);

	return 0;
}

int XLuaSetFMSFlightPlanEntryLatLonWithId(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);
	float inLat = xlua_checknumber(L, 3);
	float inLon = xlua_checknumber(L, 4);
	int inAltitudeFt = xlua_checkinteger(L, 5);
	const char* inId = xlua_checkstring(L, 6);
	unsigned int inIdLength = xlua_checkinteger(L, 7);

	XPLMSetFMSFlightPlanEntryLatLonWithId(inFlightPlan, inIndex, inLat, inLon, inAltitudeFt, inId, inIdLength);

	return 0;
}

int XLuaClearFMSFlightPlanEntry(lua_State* L)
{
	XPLMNavFlightPlan inFlightPlan = xlua_checkinteger(L, 1);
	int inIndex = xlua_checkinteger(L, 2);

	XPLMClearFMSFlightPlanEntry(inFlightPlan, inIndex);

	return 0;
}

int XLuaLoadFMSFlightPlan(lua_State* L)
{
	int inDevice = xlua_checkinteger(L, 1);
	const char * inBuffer = xlua_checkstring(L, 2);
	unsigned int inBufferLen = xlua_checkinteger(L, 3);

	XPLMLoadFMSFlightPlan(inDevice, inBuffer, inBufferLen);

	return 0;
}

int XLuaGetGPSDestinationType(lua_State* L)
{
	XPLMNavType res = XPLMGetGPSDestinationType();
	lua_pushinteger(L, res);

	return 1;
}

int XLuaGetGPSDestination(lua_State* L)
{
	XPLMNavRef res = XPLMGetGPSDestination();
	lua_pushinteger(L, res);

	return 1;
}

void RegDefines_XPLMNavigation(lua_State* L)
{
	lua_pushinteger(L, -1);
	lua_setglobal(L, "XPLM_NAV_NOT_FOUND");
}

#ifdef __cplusplus
}
#endif

#endif
