name: XLua Build

on: [push]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xlua_win
        path: build/win_x64/xlua.xpl
        if-no-files-found: error

  build-mac:
    runs-on: macos-11
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: yes
      - name: Setup Credentials
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_DEV_CERTIFICATE_PASSWORD }}

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Sign
        run: |
          codesign --sign "Developer ID Application: Laminar Research (LPH4NFE92D)" \
                   --timestamp \
                   --options runtime \
                   build/mac_x64/mac.xpl

      - name: Notarize
        run: |
          zip -r xlua_mac.zip build/mac_x64/mac.xpl
          xcrun notarytool submit xlua_mac.zip \
              --apple-id "${APPLE_ID}" \
              --team-id "${APPLE_TEAM_ID}" \
              --password "${APP_SPECIFIC_PASSWORD}" \
              --wait \
              --timeout 10m

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xlua_mac
          path: build/mac_x64/mac.xpl
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/x-plane/xlua_builder:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xlua_lin
          path: build/lin_x64/lin.xpl
          if-no-files-found: error
